// <auto-generated>
// 이 파일은 UILayerAddressConstantsGenerator에 의해 자동 생성됩니다.
// 수동으로 수정하지 마세요.
// </auto-generated>

namespace CookApps.TeamBattle.UIManagements
{
    internal static class UILayerConstants
    {
        public static string GetUILayerAddress(string uiLayerName)
        {
            return uiLayerName switch
            {
                "BattleReadyMain" => "Prefabs/UI/00_Main/BattleReadyMain.prefab",
                "InGameMain" => "Prefabs/UI/00_Main/IngameMain.prefab",
                "InGameMain_New" => "Prefabs/UI/00_Main/IngameMain_New.prefab",
                "InGameTestMain" => "Prefabs/UI/00_Main/IngameTestMain.prefab",
                "LobbyMain" => "Prefabs/UI/00_Main/LobbyMain.prefab",
                "NaninovelMain" => "Prefabs/UI/00_Main/NaninovelMain.prefab",
                "AutoChessClassicResultPopup" => "Prefabs/UI/01_Pops/AutoChessClassicResultPopup.prefab",
                "ChapterListPopup" => "Prefabs/UI/01_Pops/ChapterListPopup.prefab",
                "DialoguePopup" => "Prefabs/UI/01_Pops/DialoguePopup.prefab",
                "DungeonTrialPopup" => "Prefabs/UI/01_Pops/DungeonTrialPopup.prefab",
                "GachaPopup" => "Prefabs/UI/01_Pops/GachaPopup.prefab",
                "InGameDungeonResultPopup" => "Prefabs/UI/01_Pops/InGameDungeonResultPopup.prefab",
                "InGameDungeonTrialResultPopup" => "Prefabs/UI/01_Pops/InGameDungeonTrialResultPopup.prefab",
                "InGameResultPopup" => "Prefabs/UI/01_Pops/InGameResultPopup.prefab",
                "LoadingPopup" => "Prefabs/UI/01_Pops/LoadingPopup.prefab",
                "CharacterDetailMainLayerPopup" => "Prefabs/UI/01_Pops/CharacterCollectionPopup/CharacterDetail_Main_Layer_Popup.prefab",
                "InfoDetailTooltipPopup" => "Prefabs/UI/01_Pops/CharacterCollectionPopup/InfoDetailTooltipPopup.prefab",
                "NonSkillTooltipPopup" => "Prefabs/UI/01_Pops/CharacterCollectionPopup/PassiveSkillTooltipPopup.prefab",
                "SkillTooltipPopup" => "Prefabs/UI/01_Pops/CharacterCollectionPopup/SkillTooltipPopup.prefab",
                "SynergyTooltipInGamePopup" => "Prefabs/UI/01_Pops/CharacterCollectionPopup/SynergyTooltipInGamePopup.prefab",
                "SynergyTooltipPopup" => "Prefabs/UI/01_Pops/CharacterCollectionPopup/SynergyTooltipPopup.prefab",
                "AccountLevelUpWindowPopup" => "Prefabs/UI/01_Pops/WindowPopup/AccountLevelUpWindowPopup.prefab",
                "ChapterClearWindowPopup" => "Prefabs/UI/01_Pops/WindowPopup/ChapterClearWindowPopup.prefab",
                "ChapterMain" => "Prefabs/UI/01_Pops/WindowPopup/ChapterMain.prefab",
                "CommanderSkillPopup" => "Prefabs/UI/01_Pops/WindowPopup/CommanderSkillPopup.prefab",
                "EndTestgamePopup" => "Prefabs/UI/01_Pops/WindowPopup/EndTestgamePopup.prefab",
                "IdleRewardIncreasedPopup" => "Prefabs/UI/01_Pops/WindowPopup/IdleRewardIncreasedPopup.prefab",
                "IdleRewardPopup" => "Prefabs/UI/01_Pops/WindowPopup/IdleRewardPopup.prefab",
                "ImageInfoPop" => "Prefabs/UI/01_Pops/WindowPopup/ImageInfoPop.prefab",
                "InGameExitPopup" => "Prefabs/UI/01_Pops/WindowPopup/InGameExitPopup.prefab",
                "ItemConsumeEventPopup" => "Prefabs/UI/01_Pops/WindowPopup/ItemConsumeEventPopup.prefab",
                "ItemTooltipPopup" => "Prefabs/UI/01_Pops/WindowPopup/ItemTooltipPopup.prefab",
                "NicknamePopup" => "Prefabs/UI/01_Pops/WindowPopup/NicknamePopup.prefab",
                "QuestPopup" => "Prefabs/UI/01_Pops/WindowPopup/QuestPopup.prefab",
                "RewardResultPopup" => "Prefabs/UI/01_Pops/WindowPopup/RewardResultPopup.prefab",
                "SessionTimeEventPopup" => "Prefabs/UI/01_Pops/WindowPopup/SessionTimeEventPopup.prefab",
                "SettingPopup" => "Prefabs/UI/01_Pops/WindowPopup/SettingPopup.prefab",
                "ShopBannerPopup" => "Prefabs/UI/01_Pops/WindowPopup/ShopBannerPopup.prefab",
                "SystemConfirmPopup" => "Prefabs/UI/01_Pops/WindowPopup/SystemConfirmPopup.prefab",
                "ToastSystemPopup" => "Prefabs/UI/01_Pops/WindowPopup/ToastSystemPopup.prefab",
                "ElpisBuildLayer" => "Prefabs/UI/Building/BuildingMainLayer.prefab",
                "ElpisCommandCenterResultPopup" => "Prefabs/UI/CommandCenter/CommandCenterLevel.prefab",
                "ElpisCommandCenterPopup" => "Prefabs/UI/CommandCenter/CommandCenterMainLayer.prefab",
                "ElpisCoreResearchLayer" => "Prefabs/UI/CoreResearch/CoreResearchMainLayer.prefab",
                "BattleStatisticsPopup" => "Prefabs/UI/InGame/BattleStatisticsPopup.prefab",
                "CharacterInfoInGamePopup" => "Prefabs/UI/InGame/CharacterInfoIngamePopup.prefab",
                "EnemySkillTooltipPopup" => "Prefabs/UI/InGame/EnemySkillTooltipPopup.prefab",
                "FilterTooltipInIngamePopup" => "Prefabs/UI/InGame/FilterTooltipInIngamePopup.prefab",
                "SkillTooltipPopup_1" => "Prefabs/UI/InGame/RightSkillTooltipPopup.prefab",
                "SynergyTooltipIngameMiniPopup" => "Prefabs/UI/InGame/SynergyTooltipIngameMiniPopup.prefab",
                "LoadingMain" => "Prefabs/UI/Loading/LoadingMain.prefab",
                "TopCurrencyAndMenuBar" => "Prefabs/UI/Top/TopCurrencyAndMenuBar.prefab",
                "DownloadConfirmPopup" => "Assets/_Project/Addressables/BuiltIn/UI/Prefabs/Popup/DownloadConfirmPopup.prefab",
                "DownloadProgressPopup" => "Assets/_Project/Addressables/BuiltIn/UI/Prefabs/Popup/DownloadProgressPopup.prefab",
                "NicknamePopup_1" => "Naninovel/Spawn/Etc/NicknamePopup",
                "CharacterCollectionPopup" => "Prefabs/UI/01_Pops/CharacterCollectionPopup/CharacterCollectionPopup.prefab",
                "TitleMain" => "Assets/_Project/Splash_STK/Prefab/SplashUI.prefab",
                _ => string.Empty
            };
        }

        public static string GetSceneAddress(string sceneName)
        {
            return sceneName switch
            {
                "Naninovel" => "Assets/_Project/Addressables/Remote/0. Scenes/Naninovel.unity",
                "InGame_New" => "Assets/_Project/Addressables/Remote/0. Scenes/InGame_New.unity",
                "Lobby" => "Assets/_Project/Addressables/Remote/0. Scenes/Lobby.unity",
                "InGame" => "Assets/_Project/Addressables/Remote/0. Scenes/InGame.unity",
                "SceneLoading" => "Assets/_Project/Addressables/Remote/0. Scenes/SceneLoading.unity",
                "BattleReady" => "Assets/_Project/Addressables/Remote/0. Scenes/BattleReady.unity",
                "InGameTest" => "Assets/_Project/Addressables/Remote/0. Scenes/InGameTest.unity",
                "Title" => "Assets/_Project/Addressables/BuiltIn/0. Scenes/Title.unity",
                _ => string.Empty
            };
        }
    }
}
