// <auto-generated>
// 이 파일은 UILayerAddressConstantsGenerator에 의해 자동 생성됩니다.
// 수동으로 수정하지 마세요.
// </auto-generated>

namespace CookApps.TeamBattle.UIManagements
{
    internal static class UILayerConstants
    {
        public static string GetUILayerAddress(string uiLayerName)
        {
            return uiLayerName switch
            {
                _ => string.Empty
            };
        }

        public static string GetSceneAddress(string sceneName)
        {
            return sceneName switch
            {
                "Naninovel" => "Assets/_Project/Addressables/Remote/Scenes/Naninovel.unity",
                "Lobby" => "Assets/_Project/Addressables/Remote/Scenes/Lobby.unity",
                "InGame" => "Assets/_Project/Addressables/Remote/Scenes/InGame.unity",
                "SceneLoading" => "Assets/_Project/Addressables/Remote/Scenes/SceneLoading.unity",
                "BattleReady" => "Assets/_Project/Addressables/Remote/0. Scenes/BattleReady.unity",
                "SkillScene" => "Assets/_Project/Addressables/Remote/Scenes/SkillScene.unity",
                "Title" => "Assets/_Project/Addressables/BuiltIn/Scenes/Title.unity",
                _ => string.Empty
            };
        }
    }
}
