// Auto-generated by AnimKeyframeExtractor — DO NOT EDIT
// Source folder: Mob
using CookApps.BattleSystem;

namespace CookApps.AutoChess
{
    public static partial class AnimKeyframeData
    {
        /// <summary>Mob 폴더의 키프레임 데이터 등록</summary>
        public static void Register_Mob()
        {
            ExecuteTimes[163296] = 0.2500f; // 10206 Back_ATK
            ClipLengths[163296] = 0.7083f;
            ClipEvents[163296] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[163297] = 0.2500f; // 10206 Back_ATK2
            ClipLengths[163297] = 0.9375f;
            ClipEvents[163297] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[163298] = 0.5000f; // 10206 Back_SKL
            ClipLengths[163298] = 1.0417f;
            ClipEvents[163298] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[163299] = 0.4000f; // 10206 Back_SKL2 (fallback)
            ClipLengths[163299] = 1.0000f;

            ExecuteTimes[163304] = 0.2500f; // 10206 Front_ATK
            ClipLengths[163304] = 0.7083f;
            ClipEvents[163304] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[163305] = 0.2500f; // 10206 Front_ATK2
            ClipLengths[163305] = 1.0000f;
            ClipEvents[163305] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[163306] = 0.5000f; // 10206 Front_SKL
            ClipLengths[163306] = 1.0417f;
            ClipEvents[163306] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[163307] = 1.8750f; // 10206 Front_SKL2
            ClipLengths[163307] = 3.0000f;
            ClipEvents[163307] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[481616016] = 0.2500f; // 30101001 Back_ATK
            ClipLengths[481616016] = 0.7083f;
            ClipEvents[481616016] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616017] = 0.2500f; // 30101001 Back_ATK2
            ClipLengths[481616017] = 0.9375f;
            ClipEvents[481616017] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[481616018] = 0.5000f; // 30101001 Back_SKL
            ClipLengths[481616018] = 0.7083f;
            ClipEvents[481616018] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616019] = 0.4000f; // 30101001 Back_SKL2 (fallback)
            ClipLengths[481616019] = 1.0000f;

            ExecuteTimes[481616024] = 0.2500f; // 30101001 Front_ATK
            ClipLengths[481616024] = 0.7083f;
            ClipEvents[481616024] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616025] = 0.2500f; // 30101001 Front_ATK2
            ClipLengths[481616025] = 1.0000f;
            ClipEvents[481616025] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616026] = 0.5000f; // 30101001 Front_SKL
            ClipLengths[481616026] = 0.7083f;
            ClipEvents[481616026] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616027] = 1.8750f; // 30101001 Front_SKL2
            ClipLengths[481616027] = 3.0000f;
            ClipEvents[481616027] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[481616032] = 0.2500f; // 30101002 Back_ATK
            ClipLengths[481616032] = 0.7083f;
            ClipEvents[481616032] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616033] = 0.2500f; // 30101002 Back_ATK2
            ClipLengths[481616033] = 0.9375f;
            ClipEvents[481616033] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[481616034] = 0.5000f; // 30101002 Back_SKL
            ClipLengths[481616034] = 0.7083f;
            ClipEvents[481616034] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616035] = 0.4000f; // 30101002 Back_SKL2 (fallback)
            ClipLengths[481616035] = 1.0000f;

            ExecuteTimes[481616040] = 0.2500f; // 30101002 Front_ATK
            ClipLengths[481616040] = 0.7083f;
            ClipEvents[481616040] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616041] = 0.2500f; // 30101002 Front_ATK2
            ClipLengths[481616041] = 1.0000f;
            ClipEvents[481616041] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616042] = 0.5000f; // 30101002 Front_SKL
            ClipLengths[481616042] = 0.7083f;
            ClipEvents[481616042] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616043] = 1.8750f; // 30101002 Front_SKL2
            ClipLengths[481616043] = 3.0000f;
            ClipEvents[481616043] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[481616048] = 0.2500f; // 30101003 Back_ATK
            ClipLengths[481616048] = 0.7083f;
            ClipEvents[481616048] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616049] = 0.2500f; // 30101003 Back_ATK2
            ClipLengths[481616049] = 0.9375f;
            ClipEvents[481616049] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[481616050] = 0.5000f; // 30101003 Back_SKL
            ClipLengths[481616050] = 0.7083f;
            ClipEvents[481616050] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616051] = 0.4000f; // 30101003 Back_SKL2 (fallback)
            ClipLengths[481616051] = 1.0000f;

            ExecuteTimes[481616056] = 0.2500f; // 30101003 Front_ATK
            ClipLengths[481616056] = 0.7083f;
            ClipEvents[481616056] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616057] = 0.2500f; // 30101003 Front_ATK2
            ClipLengths[481616057] = 1.0000f;
            ClipEvents[481616057] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616058] = 0.5000f; // 30101003 Front_SKL
            ClipLengths[481616058] = 0.7083f;
            ClipEvents[481616058] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616059] = 1.8750f; // 30101003 Front_SKL2
            ClipLengths[481616059] = 3.0000f;
            ClipEvents[481616059] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[481616064] = 0.2500f; // 30101004 Back_ATK
            ClipLengths[481616064] = 0.7083f;
            ClipEvents[481616064] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616065] = 0.2500f; // 30101004 Back_ATK2
            ClipLengths[481616065] = 0.9375f;
            ClipEvents[481616065] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[481616066] = 0.5000f; // 30101004 Back_SKL
            ClipLengths[481616066] = 1.0417f;
            ClipEvents[481616066] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616067] = 0.4000f; // 30101004 Back_SKL2 (fallback)
            ClipLengths[481616067] = 1.0000f;

            ExecuteTimes[481616072] = 0.2500f; // 30101004 Front_ATK
            ClipLengths[481616072] = 0.7083f;
            ClipEvents[481616072] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616073] = 0.2500f; // 30101004 Front_ATK2
            ClipLengths[481616073] = 1.0000f;
            ClipEvents[481616073] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616074] = 0.5000f; // 30101004 Front_SKL
            ClipLengths[481616074] = 1.0417f;
            ClipEvents[481616074] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616075] = 1.8750f; // 30101004 Front_SKL2
            ClipLengths[481616075] = 3.0000f;
            ClipEvents[481616075] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[481616080] = 0.2500f; // 30101005 Back_ATK
            ClipLengths[481616080] = 0.7083f;
            ClipEvents[481616080] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616081] = 0.2500f; // 30101005 Back_ATK2
            ClipLengths[481616081] = 0.9375f;
            ClipEvents[481616081] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[481616082] = 0.5000f; // 30101005 Back_SKL
            ClipLengths[481616082] = 0.7083f;
            ClipEvents[481616082] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616083] = 0.4000f; // 30101005 Back_SKL2 (fallback)
            ClipLengths[481616083] = 1.0000f;

            ExecuteTimes[481616088] = 0.2500f; // 30101005 Front_ATK
            ClipLengths[481616088] = 0.7083f;
            ClipEvents[481616088] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616089] = 0.2500f; // 30101005 Front_ATK2
            ClipLengths[481616089] = 1.0000f;
            ClipEvents[481616089] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616090] = 0.5000f; // 30101005 Front_SKL
            ClipLengths[481616090] = 0.7083f;
            ClipEvents[481616090] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616091] = 1.8750f; // 30101005 Front_SKL2
            ClipLengths[481616091] = 3.0000f;
            ClipEvents[481616091] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[481616096] = 0.2500f; // 30101006 Back_ATK
            ClipLengths[481616096] = 0.7083f;
            ClipEvents[481616096] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616097] = 0.2500f; // 30101006 Back_ATK2
            ClipLengths[481616097] = 0.9375f;
            ClipEvents[481616097] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[481616098] = 0.5000f; // 30101006 Back_SKL
            ClipLengths[481616098] = 1.0417f;
            ClipEvents[481616098] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616099] = 0.4000f; // 30101006 Back_SKL2 (fallback)
            ClipLengths[481616099] = 1.0000f;

            ExecuteTimes[481616104] = 0.2500f; // 30101006 Front_ATK
            ClipLengths[481616104] = 0.7083f;
            ClipEvents[481616104] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616105] = 0.2500f; // 30101006 Front_ATK2
            ClipLengths[481616105] = 1.0000f;
            ClipEvents[481616105] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616106] = 0.5000f; // 30101006 Front_SKL
            ClipLengths[481616106] = 1.0417f;
            ClipEvents[481616106] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616107] = 1.8750f; // 30101006 Front_SKL2
            ClipLengths[481616107] = 3.0000f;
            ClipEvents[481616107] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[481616112] = 0.2500f; // 30101007 Back_ATK
            ClipLengths[481616112] = 0.7083f;
            ClipEvents[481616112] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616113] = 0.2500f; // 30101007 Back_ATK2
            ClipLengths[481616113] = 0.9375f;
            ClipEvents[481616113] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[481616114] = 0.5000f; // 30101007 Back_SKL
            ClipLengths[481616114] = 1.0417f;
            ClipEvents[481616114] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616115] = 0.4000f; // 30101007 Back_SKL2 (fallback)
            ClipLengths[481616115] = 1.0000f;

            ExecuteTimes[481616120] = 0.2500f; // 30101007 Front_ATK
            ClipLengths[481616120] = 0.7083f;
            ClipEvents[481616120] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616121] = 0.2500f; // 30101007 Front_ATK2
            ClipLengths[481616121] = 1.0000f;
            ClipEvents[481616121] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616122] = 0.5000f; // 30101007 Front_SKL
            ClipLengths[481616122] = 1.0417f;
            ClipEvents[481616122] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616123] = 1.8750f; // 30101007 Front_SKL2
            ClipLengths[481616123] = 3.0000f;
            ClipEvents[481616123] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[481616128] = 0.2500f; // 30101008 Back_ATK
            ClipLengths[481616128] = 0.7083f;
            ClipEvents[481616128] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616129] = 0.2500f; // 30101008 Back_ATK2
            ClipLengths[481616129] = 0.9375f;
            ClipEvents[481616129] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[481616130] = 0.5000f; // 30101008 Back_SKL
            ClipLengths[481616130] = 1.0417f;
            ClipEvents[481616130] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616131] = 0.4000f; // 30101008 Back_SKL2 (fallback)
            ClipLengths[481616131] = 1.0000f;

            ExecuteTimes[481616136] = 0.2500f; // 30101008 Front_ATK
            ClipLengths[481616136] = 0.7083f;
            ClipEvents[481616136] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616137] = 0.2500f; // 30101008 Front_ATK2
            ClipLengths[481616137] = 1.0000f;
            ClipEvents[481616137] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616138] = 0.5000f; // 30101008 Front_SKL
            ClipLengths[481616138] = 1.0417f;
            ClipEvents[481616138] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616139] = 1.8750f; // 30101008 Front_SKL2
            ClipLengths[481616139] = 3.0000f;
            ClipEvents[481616139] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[481616144] = 0.2500f; // 30101009 Back_ATK
            ClipLengths[481616144] = 0.7083f;
            ClipEvents[481616144] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616145] = 0.2500f; // 30101009 Back_ATK2
            ClipLengths[481616145] = 0.9375f;
            ClipEvents[481616145] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[481616146] = 0.5000f; // 30101009 Back_SKL
            ClipLengths[481616146] = 1.0417f;
            ClipEvents[481616146] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616147] = 0.4000f; // 30101009 Back_SKL2 (fallback)
            ClipLengths[481616147] = 1.0000f;

            ExecuteTimes[481616152] = 0.2500f; // 30101009 Front_ATK
            ClipLengths[481616152] = 0.7083f;
            ClipEvents[481616152] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616153] = 0.2500f; // 30101009 Front_ATK2
            ClipLengths[481616153] = 1.0000f;
            ClipEvents[481616153] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616154] = 0.5000f; // 30101009 Front_SKL
            ClipLengths[481616154] = 1.0417f;
            ClipEvents[481616154] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616155] = 1.8750f; // 30101009 Front_SKL2
            ClipLengths[481616155] = 3.0000f;
            ClipEvents[481616155] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[481616160] = 0.2500f; // 30101010 Back_ATK
            ClipLengths[481616160] = 0.7083f;
            ClipEvents[481616160] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616161] = 0.2500f; // 30101010 Back_ATK2
            ClipLengths[481616161] = 0.9375f;
            ClipEvents[481616161] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[481616162] = 0.5000f; // 30101010 Back_SKL
            ClipLengths[481616162] = 1.0417f;
            ClipEvents[481616162] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616163] = 0.4000f; // 30101010 Back_SKL2 (fallback)
            ClipLengths[481616163] = 1.0000f;

            ExecuteTimes[481616168] = 0.2500f; // 30101010 Front_ATK
            ClipLengths[481616168] = 0.7083f;
            ClipEvents[481616168] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[481616169] = 0.2500f; // 30101010 Front_ATK2
            ClipLengths[481616169] = 1.0000f;
            ClipEvents[481616169] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616170] = 0.5000f; // 30101010 Front_SKL
            ClipLengths[481616170] = 1.0417f;
            ClipEvents[481616170] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[481616171] = 1.8750f; // 30101010 Front_SKL2
            ClipLengths[481616171] = 3.0000f;
            ClipEvents[481616171] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[483232016] = 0.2500f; // 30202001 Back_ATK
            ClipLengths[483232016] = 0.7083f;
            ClipEvents[483232016] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[483232017] = 0.2500f; // 30202001 Back_ATK2
            ClipLengths[483232017] = 0.9375f;
            ClipEvents[483232017] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[483232018] = 0.5000f; // 30202001 Back_SKL
            ClipLengths[483232018] = 0.7083f;
            ClipEvents[483232018] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[483232019] = 0.4000f; // 30202001 Back_SKL2 (fallback)
            ClipLengths[483232019] = 1.0000f;

            ExecuteTimes[483232024] = 0.2500f; // 30202001 Front_ATK
            ClipLengths[483232024] = 0.7083f;
            ClipEvents[483232024] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[483232025] = 0.2500f; // 30202001 Front_ATK2
            ClipLengths[483232025] = 1.0000f;
            ClipEvents[483232025] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[483232026] = 0.5000f; // 30202001 Front_SKL
            ClipLengths[483232026] = 0.7083f;
            ClipEvents[483232026] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[483232027] = 1.8750f; // 30202001 Front_SKL2
            ClipLengths[483232027] = 3.0000f;
            ClipEvents[483232027] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[483232032] = 0.2500f; // 30202002 Back_ATK
            ClipLengths[483232032] = 0.7083f;
            ClipEvents[483232032] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[483232033] = 0.2500f; // 30202002 Back_ATK2
            ClipLengths[483232033] = 0.9375f;
            ClipEvents[483232033] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[483232034] = 0.5000f; // 30202002 Back_SKL
            ClipLengths[483232034] = 0.7083f;
            ClipEvents[483232034] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[483232035] = 0.4000f; // 30202002 Back_SKL2 (fallback)
            ClipLengths[483232035] = 1.0000f;

            ExecuteTimes[483232040] = 0.2500f; // 30202002 Front_ATK
            ClipLengths[483232040] = 0.7083f;
            ClipEvents[483232040] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[483232041] = 0.2500f; // 30202002 Front_ATK2
            ClipLengths[483232041] = 1.0000f;
            ClipEvents[483232041] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[483232042] = 0.5000f; // 30202002 Front_SKL
            ClipLengths[483232042] = 0.7083f;
            ClipEvents[483232042] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[483232043] = 1.8750f; // 30202002 Front_SKL2
            ClipLengths[483232043] = 3.0000f;
            ClipEvents[483232043] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[483232048] = 0.2500f; // 30202003 Back_ATK
            ClipLengths[483232048] = 0.7083f;
            ClipEvents[483232048] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[483232049] = 0.2500f; // 30202003 Back_ATK2
            ClipLengths[483232049] = 0.9375f;
            ClipEvents[483232049] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[483232050] = 0.5000f; // 30202003 Back_SKL
            ClipLengths[483232050] = 0.7083f;
            ClipEvents[483232050] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[483232051] = 0.4000f; // 30202003 Back_SKL2 (fallback)
            ClipLengths[483232051] = 1.0000f;

            ExecuteTimes[483232056] = 0.2500f; // 30202003 Front_ATK
            ClipLengths[483232056] = 0.7083f;
            ClipEvents[483232056] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[483232057] = 0.2500f; // 30202003 Front_ATK2
            ClipLengths[483232057] = 1.0000f;
            ClipEvents[483232057] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[483232058] = 0.5000f; // 30202003 Front_SKL
            ClipLengths[483232058] = 0.7083f;
            ClipEvents[483232058] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[483232059] = 1.8750f; // 30202003 Front_SKL2
            ClipLengths[483232059] = 3.0000f;
            ClipEvents[483232059] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[483232064] = 0.2500f; // 30202004 Back_ATK
            ClipLengths[483232064] = 0.7083f;
            ClipEvents[483232064] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[483232065] = 0.2500f; // 30202004 Back_ATK2
            ClipLengths[483232065] = 0.9375f;
            ClipEvents[483232065] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[483232066] = 0.5000f; // 30202004 Back_SKL
            ClipLengths[483232066] = 1.0417f;
            ClipEvents[483232066] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[483232067] = 0.4000f; // 30202004 Back_SKL2 (fallback)
            ClipLengths[483232067] = 1.0000f;

            ExecuteTimes[483232072] = 0.2500f; // 30202004 Front_ATK
            ClipLengths[483232072] = 0.7083f;
            ClipEvents[483232072] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[483232073] = 0.2500f; // 30202004 Front_ATK2
            ClipLengths[483232073] = 1.0000f;
            ClipEvents[483232073] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[483232074] = 0.5000f; // 30202004 Front_SKL
            ClipLengths[483232074] = 1.0417f;
            ClipEvents[483232074] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[483232075] = 1.8750f; // 30202004 Front_SKL2
            ClipLengths[483232075] = 3.0000f;
            ClipEvents[483232075] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[484848016] = 0.2500f; // 30303001 Back_ATK
            ClipLengths[484848016] = 0.7083f;
            ClipEvents[484848016] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[484848017] = 0.2500f; // 30303001 Back_ATK2
            ClipLengths[484848017] = 0.9375f;
            ClipEvents[484848017] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[484848018] = 0.5000f; // 30303001 Back_SKL
            ClipLengths[484848018] = 1.0417f;
            ClipEvents[484848018] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[484848019] = 0.4000f; // 30303001 Back_SKL2 (fallback)
            ClipLengths[484848019] = 1.0000f;

            ExecuteTimes[484848024] = 0.2500f; // 30303001 Front_ATK
            ClipLengths[484848024] = 0.7083f;
            ClipEvents[484848024] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[484848025] = 0.2500f; // 30303001 Front_ATK2
            ClipLengths[484848025] = 1.0000f;
            ClipEvents[484848025] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[484848026] = 0.5000f; // 30303001 Front_SKL
            ClipLengths[484848026] = 1.0417f;
            ClipEvents[484848026] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[484848027] = 1.8750f; // 30303001 Front_SKL2
            ClipLengths[484848027] = 3.0000f;
            ClipEvents[484848027] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[484848032] = 0.2500f; // 30303002 Back_ATK
            ClipLengths[484848032] = 0.7083f;
            ClipEvents[484848032] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[484848033] = 0.2500f; // 30303002 Back_ATK2
            ClipLengths[484848033] = 0.9375f;
            ClipEvents[484848033] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[484848034] = 0.5000f; // 30303002 Back_SKL
            ClipLengths[484848034] = 1.0417f;
            ClipEvents[484848034] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[484848035] = 0.4000f; // 30303002 Back_SKL2 (fallback)
            ClipLengths[484848035] = 1.0000f;

            ExecuteTimes[484848040] = 0.2500f; // 30303002 Front_ATK
            ClipLengths[484848040] = 0.7083f;
            ClipEvents[484848040] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[484848041] = 0.2500f; // 30303002 Front_ATK2
            ClipLengths[484848041] = 1.0000f;
            ClipEvents[484848041] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[484848042] = 0.5000f; // 30303002 Front_SKL
            ClipLengths[484848042] = 1.0417f;
            ClipEvents[484848042] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[484848043] = 1.8750f; // 30303002 Front_SKL2
            ClipLengths[484848043] = 3.0000f;
            ClipEvents[484848043] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[484848048] = 0.2500f; // 30303003 Back_ATK
            ClipLengths[484848048] = 0.7083f;
            ClipEvents[484848048] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[484848049] = 0.2500f; // 30303003 Back_ATK2
            ClipLengths[484848049] = 0.9375f;
            ClipEvents[484848049] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[484848050] = 0.5000f; // 30303003 Back_SKL
            ClipLengths[484848050] = 1.0417f;
            ClipEvents[484848050] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[484848051] = 0.4000f; // 30303003 Back_SKL2 (fallback)
            ClipLengths[484848051] = 1.0000f;

            ExecuteTimes[484848056] = 0.2500f; // 30303003 Front_ATK
            ClipLengths[484848056] = 0.7083f;
            ClipEvents[484848056] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[484848057] = 0.2500f; // 30303003 Front_ATK2
            ClipLengths[484848057] = 1.0000f;
            ClipEvents[484848057] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[484848058] = 0.5000f; // 30303003 Front_SKL
            ClipLengths[484848058] = 1.0417f;
            ClipEvents[484848058] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[484848059] = 1.8750f; // 30303003 Front_SKL2
            ClipLengths[484848059] = 3.0000f;
            ClipEvents[484848059] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[484848064] = 0.2500f; // 30303004 Back_ATK
            ClipLengths[484848064] = 0.7083f;
            ClipEvents[484848064] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[484848065] = 0.2500f; // 30303004 Back_ATK2
            ClipLengths[484848065] = 0.9375f;
            ClipEvents[484848065] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[484848066] = 0.5000f; // 30303004 Back_SKL
            ClipLengths[484848066] = 1.0417f;
            ClipEvents[484848066] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[484848067] = 0.4000f; // 30303004 Back_SKL2 (fallback)
            ClipLengths[484848067] = 1.0000f;

            ExecuteTimes[484848072] = 0.2500f; // 30303004 Front_ATK
            ClipLengths[484848072] = 0.7083f;
            ClipEvents[484848072] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[484848073] = 0.2500f; // 30303004 Front_ATK2
            ClipLengths[484848073] = 1.0000f;
            ClipEvents[484848073] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[484848074] = 0.5000f; // 30303004 Front_SKL
            ClipLengths[484848074] = 1.0417f;
            ClipEvents[484848074] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[484848075] = 1.8750f; // 30303004 Front_SKL2
            ClipLengths[484848075] = 3.0000f;
            ClipEvents[484848075] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[484848080] = 0.2500f; // 30303005 Back_ATK
            ClipLengths[484848080] = 0.7083f;
            ClipEvents[484848080] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[484848081] = 0.2500f; // 30303005 Back_ATK2
            ClipLengths[484848081] = 0.9375f;
            ClipEvents[484848081] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[484848082] = 0.5000f; // 30303005 Back_SKL
            ClipLengths[484848082] = 1.0417f;
            ClipEvents[484848082] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[484848083] = 0.4000f; // 30303005 Back_SKL2 (fallback)
            ClipLengths[484848083] = 1.0000f;

            ExecuteTimes[484848088] = 0.2500f; // 30303005 Front_ATK
            ClipLengths[484848088] = 0.7083f;
            ClipEvents[484848088] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[484848089] = 0.2500f; // 30303005 Front_ATK2
            ClipLengths[484848089] = 1.0000f;
            ClipEvents[484848089] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[484848090] = 0.5000f; // 30303005 Front_SKL
            ClipLengths[484848090] = 1.0417f;
            ClipEvents[484848090] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[484848091] = 1.8750f; // 30303005 Front_SKL2
            ClipLengths[484848091] = 3.0000f;
            ClipEvents[484848091] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[484848096] = 0.2500f; // 30303006 Back_ATK
            ClipLengths[484848096] = 0.7083f;
            ClipEvents[484848096] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[484848097] = 0.2500f; // 30303006 Back_ATK2
            ClipLengths[484848097] = 0.9375f;
            ClipEvents[484848097] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[484848098] = 0.5000f; // 30303006 Back_SKL
            ClipLengths[484848098] = 1.0417f;
            ClipEvents[484848098] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[484848099] = 0.4000f; // 30303006 Back_SKL2 (fallback)
            ClipLengths[484848099] = 1.0000f;

            ExecuteTimes[484848104] = 0.2500f; // 30303006 Front_ATK
            ClipLengths[484848104] = 0.7083f;
            ClipEvents[484848104] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[484848105] = 0.2500f; // 30303006 Front_ATK2
            ClipLengths[484848105] = 1.0000f;
            ClipEvents[484848105] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[484848106] = 0.5000f; // 30303006 Front_SKL
            ClipLengths[484848106] = 1.0417f;
            ClipEvents[484848106] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[484848107] = 1.8750f; // 30303006 Front_SKL2
            ClipLengths[484848107] = 3.0000f;
            ClipEvents[484848107] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[486464016] = 0.2500f; // 30404001 Back_ATK
            ClipLengths[486464016] = 0.7083f;
            ClipEvents[486464016] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[486464017] = 0.2500f; // 30404001 Back_ATK2
            ClipLengths[486464017] = 0.9375f;
            ClipEvents[486464017] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[486464018] = 0.5000f; // 30404001 Back_SKL
            ClipLengths[486464018] = 1.0417f;
            ClipEvents[486464018] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[486464019] = 0.4000f; // 30404001 Back_SKL2 (fallback)
            ClipLengths[486464019] = 1.0000f;

            ExecuteTimes[486464024] = 0.2500f; // 30404001 Front_ATK
            ClipLengths[486464024] = 0.7083f;
            ClipEvents[486464024] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[486464025] = 0.2500f; // 30404001 Front_ATK2
            ClipLengths[486464025] = 1.0000f;
            ClipEvents[486464025] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[486464026] = 0.5000f; // 30404001 Front_SKL
            ClipLengths[486464026] = 1.0417f;
            ClipEvents[486464026] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[486464027] = 1.8750f; // 30404001 Front_SKL2
            ClipLengths[486464027] = 3.0000f;
            ClipEvents[486464027] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[486464032] = 0.2500f; // 30404002 Back_ATK
            ClipLengths[486464032] = 0.7083f;
            ClipEvents[486464032] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[486464033] = 0.2500f; // 30404002 Back_ATK2
            ClipLengths[486464033] = 0.9375f;
            ClipEvents[486464033] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[486464034] = 0.5000f; // 30404002 Back_SKL
            ClipLengths[486464034] = 1.0417f;
            ClipEvents[486464034] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[486464035] = 0.4000f; // 30404002 Back_SKL2 (fallback)
            ClipLengths[486464035] = 1.0000f;

            ExecuteTimes[486464040] = 0.2500f; // 30404002 Front_ATK
            ClipLengths[486464040] = 0.7083f;
            ClipEvents[486464040] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[486464041] = 0.2500f; // 30404002 Front_ATK2
            ClipLengths[486464041] = 1.0000f;
            ClipEvents[486464041] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[486464042] = 0.5000f; // 30404002 Front_SKL
            ClipLengths[486464042] = 1.0417f;
            ClipEvents[486464042] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[486464043] = 1.8750f; // 30404002 Front_SKL2
            ClipLengths[486464043] = 3.0000f;
            ClipEvents[486464043] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[486464048] = 0.2500f; // 30404003 Back_ATK
            ClipLengths[486464048] = 0.7083f;
            ClipEvents[486464048] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[486464049] = 0.2500f; // 30404003 Back_ATK2
            ClipLengths[486464049] = 0.9375f;
            ClipEvents[486464049] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[486464050] = 0.5000f; // 30404003 Back_SKL
            ClipLengths[486464050] = 1.0417f;
            ClipEvents[486464050] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[486464051] = 0.4000f; // 30404003 Back_SKL2 (fallback)
            ClipLengths[486464051] = 1.0000f;

            ExecuteTimes[486464056] = 0.2500f; // 30404003 Front_ATK
            ClipLengths[486464056] = 0.7083f;
            ClipEvents[486464056] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[486464057] = 0.2500f; // 30404003 Front_ATK2
            ClipLengths[486464057] = 1.0000f;
            ClipEvents[486464057] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[486464058] = 0.5000f; // 30404003 Front_SKL
            ClipLengths[486464058] = 1.0417f;
            ClipEvents[486464058] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[486464059] = 1.8750f; // 30404003 Front_SKL2
            ClipLengths[486464059] = 3.0000f;
            ClipEvents[486464059] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[486464064] = 0.2500f; // 30404004 Back_ATK
            ClipLengths[486464064] = 0.7083f;
            ClipEvents[486464064] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[486464065] = 0.2500f; // 30404004 Back_ATK2
            ClipLengths[486464065] = 0.9375f;
            ClipEvents[486464065] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[486464066] = 0.5000f; // 30404004 Back_SKL
            ClipLengths[486464066] = 1.0417f;
            ClipEvents[486464066] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[486464067] = 0.4000f; // 30404004 Back_SKL2 (fallback)
            ClipLengths[486464067] = 1.0000f;

            ExecuteTimes[486464072] = 0.2500f; // 30404004 Front_ATK
            ClipLengths[486464072] = 0.7083f;
            ClipEvents[486464072] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[486464073] = 0.2500f; // 30404004 Front_ATK2
            ClipLengths[486464073] = 1.0000f;
            ClipEvents[486464073] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[486464074] = 0.5000f; // 30404004 Front_SKL
            ClipLengths[486464074] = 1.0417f;
            ClipEvents[486464074] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[486464075] = 1.8750f; // 30404004 Front_SKL2
            ClipLengths[486464075] = 3.0000f;
            ClipEvents[486464075] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[486464080] = 0.2500f; // 30404005 Back_ATK
            ClipLengths[486464080] = 0.7083f;
            ClipEvents[486464080] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[486464081] = 0.2500f; // 30404005 Back_ATK2
            ClipLengths[486464081] = 0.9375f;
            ClipEvents[486464081] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[486464082] = 0.5000f; // 30404005 Back_SKL
            ClipLengths[486464082] = 1.0417f;
            ClipEvents[486464082] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[486464083] = 0.4000f; // 30404005 Back_SKL2 (fallback)
            ClipLengths[486464083] = 1.0000f;

            ExecuteTimes[486464088] = 0.2500f; // 30404005 Front_ATK
            ClipLengths[486464088] = 0.7083f;
            ClipEvents[486464088] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[486464089] = 0.2500f; // 30404005 Front_ATK2
            ClipLengths[486464089] = 1.0000f;
            ClipEvents[486464089] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[486464090] = 0.5000f; // 30404005 Front_SKL
            ClipLengths[486464090] = 1.0417f;
            ClipEvents[486464090] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[486464091] = 1.8750f; // 30404005 Front_SKL2
            ClipLengths[486464091] = 3.0000f;
            ClipEvents[486464091] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[486464096] = 0.2500f; // 30404006 Back_ATK
            ClipLengths[486464096] = 0.7083f;
            ClipEvents[486464096] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[486464097] = 0.2500f; // 30404006 Back_ATK2
            ClipLengths[486464097] = 0.9375f;
            ClipEvents[486464097] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[486464098] = 0.5000f; // 30404006 Back_SKL
            ClipLengths[486464098] = 1.0417f;
            ClipEvents[486464098] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[486464099] = 0.4000f; // 30404006 Back_SKL2 (fallback)
            ClipLengths[486464099] = 1.0000f;

            ExecuteTimes[486464104] = 0.2500f; // 30404006 Front_ATK
            ClipLengths[486464104] = 0.7083f;
            ClipEvents[486464104] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[486464105] = 0.2500f; // 30404006 Front_ATK2
            ClipLengths[486464105] = 1.0000f;
            ClipEvents[486464105] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[486464106] = 0.5000f; // 30404006 Front_SKL
            ClipLengths[486464106] = 1.0417f;
            ClipEvents[486464106] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[486464107] = 1.8750f; // 30404006 Front_SKL2
            ClipLengths[486464107] = 3.0000f;
            ClipEvents[486464107] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[489696016] = 0.2500f; // 30606001 Back_ATK
            ClipLengths[489696016] = 0.7083f;
            ClipEvents[489696016] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[489696017] = 0.2500f; // 30606001 Back_ATK2
            ClipLengths[489696017] = 0.9375f;
            ClipEvents[489696017] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[489696018] = 0.5000f; // 30606001 Back_SKL
            ClipLengths[489696018] = 1.0417f;
            ClipEvents[489696018] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[489696019] = 0.4000f; // 30606001 Back_SKL2 (fallback)
            ClipLengths[489696019] = 1.0000f;

            ExecuteTimes[489696024] = 0.2500f; // 30606001 Front_ATK
            ClipLengths[489696024] = 0.7083f;
            ClipEvents[489696024] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[489696025] = 0.2500f; // 30606001 Front_ATK2
            ClipLengths[489696025] = 1.0000f;
            ClipEvents[489696025] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[489696026] = 0.5000f; // 30606001 Front_SKL
            ClipLengths[489696026] = 1.0417f;
            ClipEvents[489696026] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[489696027] = 1.8750f; // 30606001 Front_SKL2
            ClipLengths[489696027] = 3.0000f;
            ClipEvents[489696027] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[489696032] = 0.2500f; // 30606002 Back_ATK
            ClipLengths[489696032] = 0.7083f;
            ClipEvents[489696032] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[489696033] = 0.2500f; // 30606002 Back_ATK2
            ClipLengths[489696033] = 0.9375f;
            ClipEvents[489696033] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[489696034] = 0.5000f; // 30606002 Back_SKL
            ClipLengths[489696034] = 1.0417f;
            ClipEvents[489696034] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[489696035] = 0.4000f; // 30606002 Back_SKL2 (fallback)
            ClipLengths[489696035] = 1.0000f;

            ExecuteTimes[489696040] = 0.2500f; // 30606002 Front_ATK
            ClipLengths[489696040] = 0.7083f;
            ClipEvents[489696040] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[489696041] = 0.2500f; // 30606002 Front_ATK2
            ClipLengths[489696041] = 1.0000f;
            ClipEvents[489696041] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[489696042] = 0.5000f; // 30606002 Front_SKL
            ClipLengths[489696042] = 1.0417f;
            ClipEvents[489696042] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[489696043] = 1.8750f; // 30606002 Front_SKL2
            ClipLengths[489696043] = 3.0000f;
            ClipEvents[489696043] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[489696048] = 0.2500f; // 30606003 Back_ATK
            ClipLengths[489696048] = 0.7083f;
            ClipEvents[489696048] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[489696049] = 0.2500f; // 30606003 Back_ATK2
            ClipLengths[489696049] = 0.9375f;
            ClipEvents[489696049] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[489696050] = 0.5000f; // 30606003 Back_SKL
            ClipLengths[489696050] = 1.0417f;
            ClipEvents[489696050] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[489696051] = 0.4000f; // 30606003 Back_SKL2 (fallback)
            ClipLengths[489696051] = 1.0000f;

            ExecuteTimes[489696056] = 0.2500f; // 30606003 Front_ATK
            ClipLengths[489696056] = 0.7083f;
            ClipEvents[489696056] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[489696057] = 0.2500f; // 30606003 Front_ATK2
            ClipLengths[489696057] = 1.0000f;
            ClipEvents[489696057] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[489696058] = 0.5000f; // 30606003 Front_SKL
            ClipLengths[489696058] = 1.0417f;
            ClipEvents[489696058] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[489696059] = 1.8750f; // 30606003 Front_SKL2
            ClipLengths[489696059] = 3.0000f;
            ClipEvents[489696059] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[489696064] = 0.2500f; // 30606004 Back_ATK
            ClipLengths[489696064] = 0.7083f;
            ClipEvents[489696064] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[489696065] = 0.2500f; // 30606004 Back_ATK2
            ClipLengths[489696065] = 0.9375f;
            ClipEvents[489696065] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[489696066] = 0.5000f; // 30606004 Back_SKL
            ClipLengths[489696066] = 1.0417f;
            ClipEvents[489696066] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[489696067] = 0.4000f; // 30606004 Back_SKL2 (fallback)
            ClipLengths[489696067] = 1.0000f;

            ExecuteTimes[489696072] = 0.2500f; // 30606004 Front_ATK
            ClipLengths[489696072] = 0.7083f;
            ClipEvents[489696072] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[489696073] = 0.2500f; // 30606004 Front_ATK2
            ClipLengths[489696073] = 1.0000f;
            ClipEvents[489696073] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[489696074] = 0.5000f; // 30606004 Front_SKL
            ClipLengths[489696074] = 1.0417f;
            ClipEvents[489696074] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[489696075] = 1.8750f; // 30606004 Front_SKL2
            ClipLengths[489696075] = 3.0000f;
            ClipEvents[489696075] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[489696080] = 0.2500f; // 30606005 Back_ATK
            ClipLengths[489696080] = 0.7083f;
            ClipEvents[489696080] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[489696081] = 0.2500f; // 30606005 Back_ATK2
            ClipLengths[489696081] = 0.9375f;
            ClipEvents[489696081] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[489696082] = 0.5000f; // 30606005 Back_SKL
            ClipLengths[489696082] = 0.7083f;
            ClipEvents[489696082] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[489696083] = 0.4000f; // 30606005 Back_SKL2 (fallback)
            ClipLengths[489696083] = 1.0000f;

            ExecuteTimes[489696088] = 0.2500f; // 30606005 Front_ATK
            ClipLengths[489696088] = 0.7083f;
            ClipEvents[489696088] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[489696089] = 0.2500f; // 30606005 Front_ATK2
            ClipLengths[489696089] = 1.0000f;
            ClipEvents[489696089] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[489696090] = 0.5000f; // 30606005 Front_SKL
            ClipLengths[489696090] = 0.7083f;
            ClipEvents[489696090] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[489696091] = 1.8750f; // 30606005 Front_SKL2
            ClipLengths[489696091] = 3.0000f;
            ClipEvents[489696091] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[489696096] = 0.2500f; // 30606006 Back_ATK
            ClipLengths[489696096] = 0.7083f;
            ClipEvents[489696096] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[489696097] = 0.2500f; // 30606006 Back_ATK2
            ClipLengths[489696097] = 0.9375f;
            ClipEvents[489696097] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[489696098] = 0.5000f; // 30606006 Back_SKL
            ClipLengths[489696098] = 1.0417f;
            ClipEvents[489696098] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[489696099] = 0.4000f; // 30606006 Back_SKL2 (fallback)
            ClipLengths[489696099] = 1.0000f;

            ExecuteTimes[489696104] = 0.2500f; // 30606006 Front_ATK
            ClipLengths[489696104] = 0.7083f;
            ClipEvents[489696104] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[489696105] = 0.2500f; // 30606006 Front_ATK2
            ClipLengths[489696105] = 1.0000f;
            ClipEvents[489696105] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[489696106] = 0.5000f; // 30606006 Front_SKL
            ClipLengths[489696106] = 1.0417f;
            ClipEvents[489696106] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[489696107] = 1.8750f; // 30606006 Front_SKL2
            ClipLengths[489696107] = 3.0000f;
            ClipEvents[489696107] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[641712016] = 0.2500f; // 40107001 Back_ATK
            ClipLengths[641712016] = 1.0000f;
            ClipEvents[641712016] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[641712017] = 0.2500f; // 40107001 Back_ATK2
            ClipLengths[641712017] = 0.9375f;
            ClipEvents[641712017] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[641712018] = 0.8750f; // 40107001 Back_SKL
            ClipLengths[641712018] = 2.0000f;
            ClipEvents[641712018] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.8750f), (AnimationEventKey.End, 2.0000f) };

            ExecuteTimes[641712019] = 0.4000f; // 40107001 Back_SKL2 (fallback)
            ClipLengths[641712019] = 1.0000f;

            ExecuteTimes[641712024] = 0.2500f; // 40107001 Front_ATK
            ClipLengths[641712024] = 1.0000f;
            ClipEvents[641712024] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[641712025] = 0.2500f; // 40107001 Front_ATK2
            ClipLengths[641712025] = 1.0000f;
            ClipEvents[641712025] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[641712026] = 0.8750f; // 40107001 Front_SKL
            ClipLengths[641712026] = 2.0000f;
            ClipEvents[641712026] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.8750f), (AnimationEventKey.End, 2.0000f) };

            ExecuteTimes[641712027] = 1.8750f; // 40107001 Front_SKL2
            ClipLengths[641712027] = 3.0000f;
            ClipEvents[641712027] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[641712032] = 0.5000f; // 40107002 Back_ATK
            ClipLengths[641712032] = 1.5000f;
            ClipEvents[641712032] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[641712033] = 0.2500f; // 40107002 Back_ATK2
            ClipLengths[641712033] = 0.9375f;
            ClipEvents[641712033] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[641712034] = 0.7500f; // 40107002 Back_SKL
            ClipLengths[641712034] = 2.1250f;
            ClipEvents[641712034] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per3, 0.7500f), (AnimationEventKey.Execute1Per3, 1.0000f), (AnimationEventKey.Execute1Per3, 1.3750f), (AnimationEventKey.End, 2.1250f) };

            ExecuteTimes[641712035] = 0.4000f; // 40107002 Back_SKL2 (fallback)
            ClipLengths[641712035] = 1.0000f;

            ExecuteTimes[641712040] = 0.6250f; // 40107002 Front_ATK
            ClipLengths[641712040] = 1.6250f;
            ClipEvents[641712040] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.6250f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[641712041] = 0.2500f; // 40107002 Front_ATK2
            ClipLengths[641712041] = 1.0000f;
            ClipEvents[641712041] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[641712042] = 0.7500f; // 40107002 Front_SKL
            ClipLengths[641712042] = 2.1250f;
            ClipEvents[641712042] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per3, 0.7500f), (AnimationEventKey.Execute1Per3, 1.0000f), (AnimationEventKey.Execute1Per3, 1.5000f), (AnimationEventKey.End, 2.1250f) };

            ExecuteTimes[641712043] = 1.8750f; // 40107002 Front_SKL2
            ClipLengths[641712043] = 3.0000f;
            ClipEvents[641712043] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[646516816] = 0.2500f; // 40407301 Back_ATK
            ClipLengths[646516816] = 0.7083f;
            ClipEvents[646516816] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[646516817] = 0.2500f; // 40407301 Back_ATK2
            ClipLengths[646516817] = 0.9375f;
            ClipEvents[646516817] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[646516818] = 0.5000f; // 40407301 Back_SKL
            ClipLengths[646516818] = 1.0625f;
            ClipEvents[646516818] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[646516819] = 0.4000f; // 40407301 Back_SKL2 (fallback)
            ClipLengths[646516819] = 1.0000f;

            ExecuteTimes[646516824] = 0.2500f; // 40407301 Front_ATK
            ClipLengths[646516824] = 0.7083f;
            ClipEvents[646516824] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[646516825] = 0.2500f; // 40407301 Front_ATK2
            ClipLengths[646516825] = 1.0000f;
            ClipEvents[646516825] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[646516826] = 0.5000f; // 40407301 Front_SKL
            ClipLengths[646516826] = 1.0625f;
            ClipEvents[646516826] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[646516827] = 1.8750f; // 40407301 Front_SKL2
            ClipLengths[646516827] = 3.0000f;
            ClipEvents[646516827] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[646516832] = 0.2500f; // 40407302 Back_ATK
            ClipLengths[646516832] = 0.7083f;
            ClipEvents[646516832] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[646516833] = 0.2500f; // 40407302 Back_ATK2
            ClipLengths[646516833] = 0.9375f;
            ClipEvents[646516833] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[646516834] = 0.5000f; // 40407302 Back_SKL
            ClipLengths[646516834] = 1.0625f;
            ClipEvents[646516834] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[646516835] = 0.4000f; // 40407302 Back_SKL2 (fallback)
            ClipLengths[646516835] = 1.0000f;

            ExecuteTimes[646516840] = 0.2500f; // 40407302 Front_ATK
            ClipLengths[646516840] = 0.7083f;
            ClipEvents[646516840] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.6667f) };

            ExecuteTimes[646516841] = 0.2500f; // 40407302 Front_ATK2
            ClipLengths[646516841] = 1.0000f;
            ClipEvents[646516841] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[646516842] = 0.5000f; // 40407302 Front_SKL
            ClipLengths[646516842] = 1.0625f;
            ClipEvents[646516842] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[646516843] = 1.8750f; // 40407302 Front_SKL2
            ClipLengths[646516843] = 3.0000f;
            ClipEvents[646516843] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[801728016] = 0.2500f; // 50108001 Back_ATK
            ClipLengths[801728016] = 1.0417f;
            ClipEvents[801728016] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[801728017] = 0.2500f; // 50108001 Back_ATK2
            ClipLengths[801728017] = 0.9375f;
            ClipEvents[801728017] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[801728018] = 0.5000f; // 50108001 Back_SKL
            ClipLengths[801728018] = 1.0417f;
            ClipEvents[801728018] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[801728019] = 0.4000f; // 50108001 Back_SKL2 (fallback)
            ClipLengths[801728019] = 1.0000f;

            ExecuteTimes[801728024] = 0.2500f; // 50108001 Front_ATK
            ClipLengths[801728024] = 1.0417f;
            ClipEvents[801728024] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[801728025] = 0.2500f; // 50108001 Front_ATK2
            ClipLengths[801728025] = 1.0000f;
            ClipEvents[801728025] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[801728026] = 0.5000f; // 50108001 Front_SKL
            ClipLengths[801728026] = 1.0417f;
            ClipEvents[801728026] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[801728027] = 1.8750f; // 50108001 Front_SKL2
            ClipLengths[801728027] = 3.0000f;
            ClipEvents[801728027] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[803329616] = 0.2500f; // 50208101 Back_ATK
            ClipLengths[803329616] = 1.0417f;
            ClipEvents[803329616] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[803329617] = 0.2500f; // 50208101 Back_ATK2
            ClipLengths[803329617] = 0.9375f;
            ClipEvents[803329617] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[803329618] = 0.5000f; // 50208101 Back_SKL
            ClipLengths[803329618] = 1.0417f;
            ClipEvents[803329618] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[803329619] = 0.4000f; // 50208101 Back_SKL2 (fallback)
            ClipLengths[803329619] = 1.0000f;

            ExecuteTimes[803329624] = 0.2500f; // 50208101 Front_ATK
            ClipLengths[803329624] = 1.0417f;
            ClipEvents[803329624] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[803329625] = 0.2500f; // 50208101 Front_ATK2
            ClipLengths[803329625] = 1.0000f;
            ClipEvents[803329625] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[803329626] = 0.5000f; // 50208101 Front_SKL
            ClipLengths[803329626] = 1.0417f;
            ClipEvents[803329626] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[803329627] = 1.8750f; // 50208101 Front_SKL2
            ClipLengths[803329627] = 3.0000f;
            ClipEvents[803329627] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[804931216] = 0.2500f; // 50308201 Back_ATK
            ClipLengths[804931216] = 1.0417f;
            ClipEvents[804931216] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[804931217] = 0.2500f; // 50308201 Back_ATK2
            ClipLengths[804931217] = 0.9375f;
            ClipEvents[804931217] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[804931218] = 0.5000f; // 50308201 Back_SKL
            ClipLengths[804931218] = 1.0536f;
            ClipEvents[804931218] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[804931219] = 0.4000f; // 50308201 Back_SKL2 (fallback)
            ClipLengths[804931219] = 1.0000f;

            ExecuteTimes[804931224] = 0.2500f; // 50308201 Front_ATK
            ClipLengths[804931224] = 1.0417f;
            ClipEvents[804931224] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[804931225] = 0.2500f; // 50308201 Front_ATK2
            ClipLengths[804931225] = 1.0000f;
            ClipEvents[804931225] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[804931226] = 0.5000f; // 50308201 Front_SKL
            ClipLengths[804931226] = 1.0536f;
            ClipEvents[804931226] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[804931227] = 1.8750f; // 50308201 Front_SKL2
            ClipLengths[804931227] = 3.0000f;
            ClipEvents[804931227] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[809736016] = 0.2500f; // 50608501 Back_ATK
            ClipLengths[809736016] = 1.0417f;
            ClipEvents[809736016] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[809736017] = 0.2500f; // 50608501 Back_ATK2
            ClipLengths[809736017] = 0.9375f;
            ClipEvents[809736017] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[809736018] = 0.5000f; // 50608501 Back_SKL
            ClipLengths[809736018] = 1.0417f;
            ClipEvents[809736018] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[809736019] = 0.4000f; // 50608501 Back_SKL2 (fallback)
            ClipLengths[809736019] = 1.0000f;

            ExecuteTimes[809736024] = 0.2500f; // 50608501 Front_ATK
            ClipLengths[809736024] = 1.0417f;
            ClipEvents[809736024] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[809736025] = 0.2500f; // 50608501 Front_ATK2
            ClipLengths[809736025] = 1.0000f;
            ClipEvents[809736025] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[809736026] = 0.5000f; // 50608501 Front_SKL
            ClipLengths[809736026] = 1.0417f;
            ClipEvents[809736026] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[809736027] = 1.8750f; // 50608501 Front_SKL2
            ClipLengths[809736027] = 3.0000f;
            ClipEvents[809736027] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[1281744016] = 0.2500f; // 80109001 Back_ATK
            ClipLengths[1281744016] = 1.3750f;
            ClipEvents[1281744016] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per2, 0.2500f), (AnimationEventKey.Execute1Per2, 0.8750f), (AnimationEventKey.End, 1.3750f) };
            AttackHitTimes[1281744016] = new[] { 0.2500f, 0.8750f }; // 80109001 Back_ATK (2hits)

            ExecuteTimes[1281744017] = 0.2500f; // 80109001 Back_ATK2
            ClipLengths[1281744017] = 0.9375f;
            ClipEvents[1281744017] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[1281744018] = 0.5625f; // 80109001 Back_SKL
            ClipLengths[1281744018] = 1.3750f;
            ClipEvents[1281744018] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5625f), (AnimationEventKey.End, 1.3125f) };

            ExecuteTimes[1281744019] = 0.4000f; // 80109001 Back_SKL2 (fallback)
            ClipLengths[1281744019] = 1.0000f;

            ExecuteTimes[1281744024] = 0.2500f; // 80109001 Front_ATK
            ClipLengths[1281744024] = 1.3750f;
            ClipEvents[1281744024] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per2, 0.2500f), (AnimationEventKey.Execute1Per2, 0.7500f), (AnimationEventKey.End, 1.3750f) };
            AttackHitTimes[1281744024] = new[] { 0.2500f, 0.7500f }; // 80109001 Front_ATK (2hits)

            ExecuteTimes[1281744025] = 0.2500f; // 80109001 Front_ATK2
            ClipLengths[1281744025] = 1.0000f;
            ClipEvents[1281744025] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[1281744026] = 0.5625f; // 80109001 Front_SKL
            ClipLengths[1281744026] = 1.3750f;
            ClipEvents[1281744026] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5625f), (AnimationEventKey.End, 1.3125f) };

            ExecuteTimes[1281744027] = 1.8750f; // 80109001 Front_SKL2
            ClipLengths[1281744027] = 3.0000f;
            ClipEvents[1281744027] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[1281744048] = 0.2500f; // 80109003 Back_ATK
            ClipLengths[1281744048] = 1.0000f;
            ClipEvents[1281744048] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[1281744049] = 0.2500f; // 80109003 Back_ATK2
            ClipLengths[1281744049] = 0.9375f;
            ClipEvents[1281744049] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[1281744050] = 3.0000f; // 80109003 Back_SKL
            ClipLengths[1281744050] = 4.0000f;
            ClipEvents[1281744050] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 3.0000f), (AnimationEventKey.End, 3.9833f) };

            ExecuteTimes[1281744051] = 0.4000f; // 80109003 Back_SKL2 (fallback)
            ClipLengths[1281744051] = 1.0000f;

            ExecuteTimes[1281744056] = 0.2500f; // 80109003 Front_ATK
            ClipLengths[1281744056] = 1.0000f;
            ClipEvents[1281744056] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[1281744057] = 0.2500f; // 80109003 Front_ATK2
            ClipLengths[1281744057] = 1.0000f;
            ClipEvents[1281744057] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[1281744058] = 3.0000f; // 80109003 Front_SKL
            ClipLengths[1281744058] = 4.0000f;
            ClipEvents[1281744058] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 3.0000f), (AnimationEventKey.End, 3.9833f) };

            ExecuteTimes[1281744059] = 1.8750f; // 80109003 Front_SKL2
            ClipLengths[1281744059] = 3.0000f;
            ClipEvents[1281744059] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

        }
    }
}
