// Auto-generated by AnimKeyframeExtractor — DO NOT EDIT
// Source folder: Obstacle
using CookApps.BattleSystem;

namespace CookApps.AutoChess
{
    public static partial class AnimKeyframeData
    {
        /// <summary>Obstacle 폴더의 키프레임 데이터 등록</summary>
        public static void Register_Obstacle()
        {
            ExecuteTimes[1600016] = 0.2500f; // 100001 Back_ATK
            ClipLengths[1600016] = 1.0000f;
            ClipEvents[1600016] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[1600017] = 0.2500f; // 100001 Back_ATK2
            ClipLengths[1600017] = 0.9375f;
            ClipEvents[1600017] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[1600018] = 0.5000f; // 100001 Back_SKL
            ClipLengths[1600018] = 1.5000f;
            ClipEvents[1600018] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[1600019] = 0.4000f; // 100001 Back_SKL2 (fallback)
            ClipLengths[1600019] = 1.0000f;

            ExecuteTimes[1600024] = 0.1875f; // 100001 Front_ATK
            ClipLengths[1600024] = 1.0000f;
            ClipEvents[1600024] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.1875f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[1600025] = 0.2500f; // 100001 Front_ATK2
            ClipLengths[1600025] = 1.0000f;
            ClipEvents[1600025] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[1600026] = 0.5000f; // 100001 Front_SKL
            ClipLengths[1600026] = 1.5000f;
            ClipEvents[1600026] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[1600027] = 1.8750f; // 100001 Front_SKL2
            ClipLengths[1600027] = 3.0000f;
            ClipEvents[1600027] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[1600032] = 0.2500f; // 100002 Back_ATK
            ClipLengths[1600032] = 1.0000f;
            ClipEvents[1600032] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[1600033] = 0.2500f; // 100002 Back_ATK2
            ClipLengths[1600033] = 0.9375f;
            ClipEvents[1600033] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[1600034] = 0.5000f; // 100002 Back_SKL
            ClipLengths[1600034] = 1.5000f;
            ClipEvents[1600034] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[1600035] = 0.4000f; // 100002 Back_SKL2 (fallback)
            ClipLengths[1600035] = 1.0000f;

            ExecuteTimes[1600040] = 0.1875f; // 100002 Front_ATK
            ClipLengths[1600040] = 1.0000f;
            ClipEvents[1600040] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.1875f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[1600041] = 0.2500f; // 100002 Front_ATK2
            ClipLengths[1600041] = 1.0000f;
            ClipEvents[1600041] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[1600042] = 0.5000f; // 100002 Front_SKL
            ClipLengths[1600042] = 1.5000f;
            ClipEvents[1600042] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[1600043] = 1.8750f; // 100002 Front_SKL2
            ClipLengths[1600043] = 3.0000f;
            ClipEvents[1600043] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[160016] = 0.2500f; // 10001 Back_ATK
            ClipLengths[160016] = 1.0000f;
            ClipEvents[160016] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[160017] = 0.2500f; // 10001 Back_ATK2
            ClipLengths[160017] = 0.9375f;
            ClipEvents[160017] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[160018] = 0.5000f; // 10001 Back_SKL
            ClipLengths[160018] = 1.5000f;
            ClipEvents[160018] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[160019] = 0.4000f; // 10001 Back_SKL2 (fallback)
            ClipLengths[160019] = 1.0000f;

            ExecuteTimes[160024] = 0.1875f; // 10001 Front_ATK
            ClipLengths[160024] = 1.0000f;
            ClipEvents[160024] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.1875f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[160025] = 0.2500f; // 10001 Front_ATK2
            ClipLengths[160025] = 1.0000f;
            ClipEvents[160025] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[160026] = 0.5000f; // 10001 Front_SKL
            ClipLengths[160026] = 1.5000f;
            ClipEvents[160026] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[160027] = 1.8750f; // 10001 Front_SKL2
            ClipLengths[160027] = 3.0000f;
            ClipEvents[160027] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[3200016] = 0.2500f; // 200001 Back_ATK
            ClipLengths[3200016] = 1.0000f;
            ClipEvents[3200016] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[3200017] = 0.2500f; // 200001 Back_ATK2
            ClipLengths[3200017] = 0.9375f;
            ClipEvents[3200017] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[3200018] = 0.5000f; // 200001 Back_SKL
            ClipLengths[3200018] = 1.5000f;
            ClipEvents[3200018] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[3200019] = 0.4000f; // 200001 Back_SKL2 (fallback)
            ClipLengths[3200019] = 1.0000f;

            ExecuteTimes[3200024] = 0.1875f; // 200001 Front_ATK
            ClipLengths[3200024] = 1.0000f;
            ClipEvents[3200024] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.1875f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[3200025] = 0.2500f; // 200001 Front_ATK2
            ClipLengths[3200025] = 1.0000f;
            ClipEvents[3200025] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[3200026] = 0.5000f; // 200001 Front_SKL
            ClipLengths[3200026] = 1.5000f;
            ClipEvents[3200026] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[3200027] = 1.8750f; // 200001 Front_SKL2
            ClipLengths[3200027] = 3.0000f;
            ClipEvents[3200027] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[320016] = 0.2500f; // 20001 Back_ATK
            ClipLengths[320016] = 1.0000f;
            ClipEvents[320016] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[320017] = 0.2500f; // 20001 Back_ATK2
            ClipLengths[320017] = 0.9375f;
            ClipEvents[320017] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[320018] = 0.5000f; // 20001 Back_SKL
            ClipLengths[320018] = 1.5000f;
            ClipEvents[320018] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[320019] = 0.4000f; // 20001 Back_SKL2 (fallback)
            ClipLengths[320019] = 1.0000f;

            ExecuteTimes[320024] = 0.1875f; // 20001 Front_ATK
            ClipLengths[320024] = 1.0000f;
            ClipEvents[320024] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.1875f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[320025] = 0.2500f; // 20001 Front_ATK2
            ClipLengths[320025] = 1.0000f;
            ClipEvents[320025] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[320026] = 0.5000f; // 20001 Front_SKL
            ClipLengths[320026] = 1.5000f;
            ClipEvents[320026] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[320027] = 1.8750f; // 20001 Front_SKL2
            ClipLengths[320027] = 3.0000f;
            ClipEvents[320027] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[480016] = 0.2500f; // 30001 Back_ATK
            ClipLengths[480016] = 1.0000f;
            ClipEvents[480016] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[480017] = 0.2500f; // 30001 Back_ATK2
            ClipLengths[480017] = 0.9375f;
            ClipEvents[480017] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[480018] = 0.5000f; // 30001 Back_SKL
            ClipLengths[480018] = 1.5000f;
            ClipEvents[480018] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[480019] = 0.4000f; // 30001 Back_SKL2 (fallback)
            ClipLengths[480019] = 1.0000f;

            ExecuteTimes[480024] = 0.1875f; // 30001 Front_ATK
            ClipLengths[480024] = 1.0000f;
            ClipEvents[480024] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.1875f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[480025] = 0.2500f; // 30001 Front_ATK2
            ClipLengths[480025] = 1.0000f;
            ClipEvents[480025] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[480026] = 0.5000f; // 30001 Front_SKL
            ClipLengths[480026] = 1.5000f;
            ClipEvents[480026] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[480027] = 1.8750f; // 30001 Front_SKL2
            ClipLengths[480027] = 3.0000f;
            ClipEvents[480027] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[480032] = 0.2500f; // 30002 Back_ATK
            ClipLengths[480032] = 1.0000f;
            ClipEvents[480032] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[480033] = 0.2500f; // 30002 Back_ATK2
            ClipLengths[480033] = 0.9375f;
            ClipEvents[480033] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[480034] = 0.5000f; // 30002 Back_SKL
            ClipLengths[480034] = 1.5000f;
            ClipEvents[480034] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[480035] = 0.4000f; // 30002 Back_SKL2 (fallback)
            ClipLengths[480035] = 1.0000f;

            ExecuteTimes[480040] = 0.1875f; // 30002 Front_ATK
            ClipLengths[480040] = 1.0000f;
            ClipEvents[480040] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.1875f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[480041] = 0.2500f; // 30002 Front_ATK2
            ClipLengths[480041] = 1.0000f;
            ClipEvents[480041] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[480042] = 0.5000f; // 30002 Front_SKL
            ClipLengths[480042] = 1.5000f;
            ClipEvents[480042] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[480043] = 1.8750f; // 30002 Front_SKL2
            ClipLengths[480043] = 3.0000f;
            ClipEvents[480043] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[480048] = 0.2500f; // 30003 Back_ATK
            ClipLengths[480048] = 1.0000f;
            ClipEvents[480048] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[480049] = 0.2500f; // 30003 Back_ATK2
            ClipLengths[480049] = 0.9375f;
            ClipEvents[480049] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[480050] = 0.5000f; // 30003 Back_SKL
            ClipLengths[480050] = 1.5000f;
            ClipEvents[480050] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[480051] = 0.4000f; // 30003 Back_SKL2 (fallback)
            ClipLengths[480051] = 1.0000f;

            ExecuteTimes[480056] = 0.1875f; // 30003 Front_ATK
            ClipLengths[480056] = 1.0000f;
            ClipEvents[480056] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.1875f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[480057] = 0.2500f; // 30003 Front_ATK2
            ClipLengths[480057] = 1.0000f;
            ClipEvents[480057] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[480058] = 0.5000f; // 30003 Front_SKL
            ClipLengths[480058] = 1.5000f;
            ClipEvents[480058] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[480059] = 1.8750f; // 30003 Front_SKL2
            ClipLengths[480059] = 3.0000f;
            ClipEvents[480059] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[480064] = 0.2500f; // 30004 Back_ATK
            ClipLengths[480064] = 1.0000f;
            ClipEvents[480064] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[480065] = 0.2500f; // 30004 Back_ATK2
            ClipLengths[480065] = 0.9375f;
            ClipEvents[480065] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[480066] = 0.5000f; // 30004 Back_SKL
            ClipLengths[480066] = 1.5000f;
            ClipEvents[480066] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[480067] = 0.4000f; // 30004 Back_SKL2 (fallback)
            ClipLengths[480067] = 1.0000f;

            ExecuteTimes[480072] = 0.1875f; // 30004 Front_ATK
            ClipLengths[480072] = 1.0000f;
            ClipEvents[480072] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.1875f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[480073] = 0.2500f; // 30004 Front_ATK2
            ClipLengths[480073] = 1.0000f;
            ClipEvents[480073] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[480074] = 0.5000f; // 30004 Front_SKL
            ClipLengths[480074] = 1.5000f;
            ClipEvents[480074] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[480075] = 1.8750f; // 30004 Front_SKL2
            ClipLengths[480075] = 3.0000f;
            ClipEvents[480075] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[480080] = 0.2500f; // 30005 Back_ATK
            ClipLengths[480080] = 1.0000f;
            ClipEvents[480080] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[480081] = 0.2500f; // 30005 Back_ATK2
            ClipLengths[480081] = 0.9375f;
            ClipEvents[480081] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[480082] = 0.5000f; // 30005 Back_SKL
            ClipLengths[480082] = 1.5000f;
            ClipEvents[480082] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[480083] = 0.4000f; // 30005 Back_SKL2 (fallback)
            ClipLengths[480083] = 1.0000f;

            ExecuteTimes[480088] = 0.1875f; // 30005 Front_ATK
            ClipLengths[480088] = 1.0000f;
            ClipEvents[480088] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.1875f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[480089] = 0.2500f; // 30005 Front_ATK2
            ClipLengths[480089] = 1.0000f;
            ClipEvents[480089] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[480090] = 0.5000f; // 30005 Front_SKL
            ClipLengths[480090] = 1.5000f;
            ClipEvents[480090] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[480091] = 1.8750f; // 30005 Front_SKL2
            ClipLengths[480091] = 3.0000f;
            ClipEvents[480091] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

            ExecuteTimes[640016] = 0.2500f; // 40001 Back_ATK
            ClipLengths[640016] = 1.0000f;
            ClipEvents[640016] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[640017] = 0.2500f; // 40001 Back_ATK2
            ClipLengths[640017] = 0.9375f;
            ClipEvents[640017] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 0.9375f) };

            ExecuteTimes[640018] = 0.5000f; // 40001 Back_SKL
            ClipLengths[640018] = 1.5000f;
            ClipEvents[640018] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[640019] = 0.4000f; // 40001 Back_SKL2 (fallback)
            ClipLengths[640019] = 1.0000f;

            ExecuteTimes[640024] = 0.1875f; // 40001 Front_ATK
            ClipLengths[640024] = 1.0000f;
            ClipEvents[640024] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.1875f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[640025] = 0.2500f; // 40001 Front_ATK2
            ClipLengths[640025] = 1.0000f;
            ClipEvents[640025] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.2500f), (AnimationEventKey.End, 1.0000f) };

            ExecuteTimes[640026] = 0.5000f; // 40001 Front_SKL
            ClipLengths[640026] = 1.5000f;
            ClipEvents[640026] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 0.5000f), (AnimationEventKey.End, 1.5000f) };

            ExecuteTimes[640027] = 1.8750f; // 40001 Front_SKL2
            ClipLengths[640027] = 3.0000f;
            ClipEvents[640027] = new[] { (AnimationEventKey.Start, 0.0000f), (AnimationEventKey.Execute1Per1, 1.8750f), (AnimationEventKey.End, 3.0000f) };

        }
    }
}
