using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace CookApps.AutoBattler.Editor
{
#if UNITY_EDITOR
    /// <summary>
    /// OriginalSpecData.json이 변경될 때 자동으로 IdMap.cs를 생성하는 AssetPostprocessor
    /// </summary>
    public class IdMapPostprocessor : AssetPostprocessor
    {
        private static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths)
        {
            // OriginalSpecData.json이 변경되었는지 확인
            bool needsRegeneration = importedAssets.Any(path =>
                path.EndsWith("OriginalSpecData.json", System.StringComparison.OrdinalIgnoreCase));

            if (needsRegeneration)
            {
                Debug.Log("[IdMapPostprocessor] OriginalSpecData.json이 변경되었습니다. IdMap.cs를 재생성합니다...");
                IdMapGenerator.Generate();
            }
        }
    }
#endif

    public static class IdMapGenerator
    {
        [MenuItem("Tools/Generate IdMap")]
        public static void Generate()
        {
            // OriginalSpecData.json 경로
            string jsonPath = Path.Combine(Application.dataPath, "OriginalSpecData.json");
            if (!File.Exists(jsonPath))
            {
                Debug.LogError($"OriginalSpecData.json not found at: {jsonPath}");
                return;
            }

            // JSON 파일 읽기
            string jsonText = File.ReadAllText(jsonPath);
            var data = Newtonsoft.Json.JsonConvert.DeserializeObject<Dictionary<string, object>>(jsonText);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// IdMap - 자동 생성된 ID 맵입니다.");
            sb.AppendLine("// Assets > Tools > Generate IdMap 메뉴로 재생성할 수 있습니다.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace CookApps.AutoBattler");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 각종 ID에 쉽게 접근하기 위한 정적 클래스");
            sb.AppendLine("    /// 사용 예: IdMap.Item.Gold, IdMap.ElpisBuild.CommandCenter");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static partial class IdMap");
            sb.AppendLine("    {");

            // Item 중첩 클래스 생성
            GenerateItemClass(sb, data);

            sb.AppendLine();

            // ElpisBuild 중첩 클래스 생성
            GenerateElpisBuildClass(sb, data);

            sb.AppendLine("    }");
            sb.AppendLine();

            // ItemId Extension Methods 생성
            GenerateItemIdExtensions(sb, data);

            sb.AppendLine();

            // CheatCurrencyType enum 생성
            GenerateCheatCurrencyTypeEnum(sb, data);

            sb.AppendLine("}");

            // 파일 저장
            string outputPath = Path.Combine(Application.dataPath, "_Project/Scripts/Spec/IdMap.cs");
            File.WriteAllText(outputPath, sb.ToString());

            AssetDatabase.Refresh();
            Debug.Log($"IdMap.cs generated at: {outputPath}");
        }

        private static void GenerateItemClass(StringBuilder sb, Dictionary<string, object> data)
        {
            var items = new List<(string itemCode, int itemId, string itemType)>();

            // ItemCurrencyTable 처리
            if (data.ContainsKey("ItemCurrencyTable"))
            {
                var table = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ItemCurrencyData>>(data["ItemCurrencyTable"].ToString());
                foreach (var item in table)
                {
                    if (!string.IsNullOrEmpty(item.item_code))
                    {
                        items.Add((item.item_code, item.currency_id, "Currency"));
                    }
                }
            }

            // ItemConsumableTable 처리
            if (data.ContainsKey("ItemConsumableTable"))
            {
                var table = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ItemConsumableData>>(data["ItemConsumableTable"].ToString());
                foreach (var item in table)
                {
                    if (!string.IsNullOrEmpty(item.item_code))
                    {
                        items.Add((item.item_code, item.item_id, "Consumable"));
                    }
                }
            }

            // ItemMaterialTable 처리
            if (data.ContainsKey("ItemMaterialTable"))
            {
                var table = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ItemMaterialData>>(data["ItemMaterialTable"].ToString());
                foreach (var item in table)
                {
                    if (!string.IsNullOrEmpty(item.item_code))
                    {
                        items.Add((item.item_code, item.item_id, "Material"));
                    }
                }
            }

            sb.AppendLine("        public static partial class Item");
            sb.AppendLine("        {");

            // Currency 섹션
            sb.AppendLine("            // ==================== Currency Items ====================");
            foreach (var (itemCode, itemId, itemType) in items)
            {
                if (itemType == "Currency")
                {
                    sb.AppendLine($"            public static readonly ItemId {itemCode} = {itemId};");
                }
            }

            sb.AppendLine();
            sb.AppendLine("            // ==================== Consumable Items ====================");
            foreach (var (itemCode, itemId, itemType) in items)
            {
                if (itemType == "Consumable")
                {
                    sb.AppendLine($"            public static readonly ItemId {itemCode} = {itemId};");
                }
            }

            sb.AppendLine();
            sb.AppendLine("            // ==================== Material Items ====================");
            foreach (var (itemCode, itemId, itemType) in items)
            {
                if (itemType == "Material")
                {
                    sb.AppendLine($"            public static readonly ItemId {itemCode} = {itemId};");
                }
            }

            sb.AppendLine("        }");
        }

        private static void GenerateItemIdExtensions(StringBuilder sb, Dictionary<string, object> data)
        {
            var items = new List<(string itemCode, int itemId, string itemType)>();

            // ItemCurrencyTable 처리
            if (data.ContainsKey("ItemCurrencyTable"))
            {
                var table = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ItemCurrencyData>>(data["ItemCurrencyTable"].ToString());
                foreach (var item in table)
                {
                    items.Add((item.item_code, item.currency_id, "Currency"));
                }
            }

            // ItemConsumableTable 처리
            if (data.ContainsKey("ItemConsumableTable"))
            {
                var table = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ItemConsumableData>>(data["ItemConsumableTable"].ToString());
                foreach (var item in table)
                {
                    items.Add((item.item_code, item.item_id, "Consumable"));
                }
            }

            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// ItemId 확장 메서드");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class ItemIdExtensions");
            sb.AppendLine("    {");

            // IsCurrency 함수 생성
            var currencyIds = items.Where(x => x.itemType == "Currency").Select(x => x.itemId).ToList();
            GenerateExtensionMethod(sb, "IsCurrency", currencyIds);

            // IsConsumable 함수 생성
            var consumableIds = items.Where(x => x.itemType == "Consumable").Select(x => x.itemId).ToList();
            GenerateExtensionMethod(sb, "IsConsumable", consumableIds);

            // ItemMaterialTable에서 모든 정보 추출
            var materialIds = new List<int>();
            var characterIds = new List<int>();
            var characterPieceIds = new List<int>();
            if (data.ContainsKey("ItemMaterialTable"))
            {
                var table = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ItemMaterialData>>(data["ItemMaterialTable"].ToString());
                materialIds = table.Select(x => x.item_id).ToList();
                characterIds = table.Where(x => x.material_type == (int)MaterialType.CHARACTER).Select(x => x.item_id).ToList();
                characterPieceIds = table.Where(x => x.material_type == (int)MaterialType.CHARACTER_PIECE).Select(x => x.item_id).ToList();
            }

            // IsMaterial 함수 생성
            GenerateExtensionMethod(sb, "IsMaterial", materialIds);

            // IsCharacter 함수 생성
            GenerateExtensionMethod(sb, "IsCharacter", characterIds);

            // IsCharacterPiece 함수 생성
            GenerateExtensionMethod(sb, "IsCharacterPiece", characterPieceIds);

            // GetCharacterId 함수 생성
            GenerateGetCharacterIdMethod(sb, characterIds, characterPieceIds);

            // GetCharacterPieceId 함수 생성
            GenerateGetCharacterPieceIdMethod(sb, characterIds, characterPieceIds);

            sb.AppendLine("    }");
        }

        private static void GenerateGetCharacterIdMethod(StringBuilder sb, List<int> characterIds, List<int> characterPieceIds)
        {
            sb.AppendLine("        public static bool GetCharacterId(this ItemId id, out int charId)");
            sb.AppendLine("        {");
            sb.AppendLine("            charId = -1;");
            sb.AppendLine("            if (id.IsCharacter())");
            sb.AppendLine("            {");
            sb.AppendLine("                charId = id.Value;");
            sb.AppendLine("                return true;");
            sb.AppendLine("            }");
            sb.AppendLine("            if (id.IsCharacterPiece())");
            sb.AppendLine("            {");
            sb.AppendLine("                charId = id.Value % 10000;");
            sb.AppendLine("                return true;");
            sb.AppendLine("            }");
            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void GenerateGetCharacterPieceIdMethod(StringBuilder sb, List<int> characterIds, List<int> characterPieceIds)
        {
            // characterId -> characterPieceId 매핑 생성
            var mapping = new Dictionary<int, int>();
            for (int i = 0; i < characterIds.Count && i < characterPieceIds.Count; i++)
            {
                int charId = characterIds[i];
                // characterPieceId는 characterId + 10000 패턴
                int pieceId = characterPieceIds.FirstOrDefault(p => p % 10000 == charId);
                if (pieceId != 0)
                {
                    mapping[charId] = pieceId;
                }
            }

            sb.AppendLine("        public static ItemId GetCharacterPieceId(int characterId)");
            sb.AppendLine("        {");
            sb.AppendLine("            return characterId switch");
            sb.AppendLine("            {");

            foreach (var kvp in mapping.OrderBy(x => x.Key))
            {
                sb.AppendLine($"                {kvp.Key} => {kvp.Value},");
            }

            sb.AppendLine("                _ => default");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void GenerateExtensionMethod(StringBuilder sb, string methodName, List<int> ids)
        {
            sb.AppendLine($"        public static bool {methodName}(this ItemId id)");
            sb.AppendLine("        {");

            if (ids.Count == 0)
            {
                sb.AppendLine("            return false;");
            }
            else
            {
                sb.Append("            return ");
                for (int i = 0; i < ids.Count; i++)
                {
                    if (i > 0)
                        sb.Append(" || ");
                    sb.Append($"id == {ids[i]}");
                }
                sb.AppendLine(";");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void GenerateElpisBuildClass(StringBuilder sb, Dictionary<string, object> data)
        {
            var builds = new List<(int buildId, FacilityType facilityType, int slotIndex)>();

            // ElpisBuildInfo 처리
            if (data.ContainsKey("ElpisBuildInfo"))
            {
                var table = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ElpisBuildData>>(data["ElpisBuildInfo"].ToString());

                // build_id 기준으로 고유한 값만 추출
                var uniqueBuilds = new Dictionary<int, (FacilityType facilityType, int slotIndex)>();
                foreach (var item in table)
                {
                    if (!uniqueBuilds.ContainsKey(item.build_id))
                    {
                        uniqueBuilds[item.build_id] = ((FacilityType)item.facility_type, item.slot_index);
                    }
                }

                foreach (var kvp in uniqueBuilds)
                {
                    builds.Add((kvp.Key, kvp.Value.facilityType, kvp.Value.slotIndex));
                }
            }

            // FacilityType별로 그룹화
            var groupedBuilds = builds
                .GroupBy(b => b.facilityType)
                .OrderBy(g => (int)g.Key)
                .ToList();

            sb.AppendLine("        public static class ElpisBuild");
            sb.AppendLine("        {");

            foreach (var group in groupedBuilds)
            {
                sb.AppendLine($"            // ==================== {group.Key} ====================");

                var sortedBuilds = group.OrderBy(b => b.slotIndex).ThenBy(b => b.buildId).ToList();

                if (sortedBuilds.Count == 1)
                {
                    var build = sortedBuilds[0];
                    string name = GetFacilityName(build.facilityType);
                    sb.AppendLine($"            public const int {name} = {build.buildId};");
                }
                else
                {
                    for (int i = 0; i < sortedBuilds.Count; i++)
                    {
                        var build = sortedBuilds[i];
                        string name = GetFacilityName(build.facilityType);
                        sb.AppendLine($"            public const int {name}_{i + 1} = {build.buildId};");
                    }
                }

                sb.AppendLine();
            }

            // 마지막 빈 줄 제거
            sb.Length -= System.Environment.NewLine.Length;

            sb.AppendLine("        }");
        }

        private static string GetFacilityName(FacilityType facilityType)
        {
            return facilityType switch
            {
                FacilityType.COMMAND_CENTER => "CommandCenter",
                FacilityType.NEST => "Nest",
                FacilityType.DIMENSION_LAB => "DimensionLab",
                FacilityType.SIMULATION_CENTER => "SimulationCenter",
                _ => $"Unknown_{(int)facilityType}"
            };
        }

        private static void GenerateCheatCurrencyTypeEnum(StringBuilder sb, Dictionary<string, object> data)
        {
            var items = new List<(string itemCode, int itemId)>();

            // ItemCurrencyTable 처리
            if (data.ContainsKey("ItemCurrencyTable"))
            {
                var table = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ItemCurrencyData>>(data["ItemCurrencyTable"].ToString());
                foreach (var item in table)
                {
                    if (!string.IsNullOrEmpty(item.item_code))
                    {
                        items.Add((item.item_code, item.currency_id));
                    }
                }
            }

            // ItemConsumableTable 처리
            if (data.ContainsKey("ItemConsumableTable"))
            {
                var table = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ItemConsumableData>>(data["ItemConsumableTable"].ToString());
                foreach (var item in table)
                {
                    if (!string.IsNullOrEmpty(item.item_code))
                    {
                        items.Add((item.item_code, item.item_id));
                    }
                }
            }

            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 치트용 재화 타입 (SROptions 드롭다운용)");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public enum CheatCurrencyType");
            sb.AppendLine("    {");

            foreach (var (itemCode, itemId) in items)
            {
                sb.AppendLine($"        {itemCode} = {itemId},");
            }

            sb.AppendLine("    }");
        }

        #region JSON 파싱용 데이터 클래스

        private class ItemCurrencyData
        {
            public int currency_id;
            public string item_code;
        }

        private class ItemConsumableData
        {
            public int item_id;
            public string item_code;
        }

        private class ItemMaterialData
        {
            public int item_id;
            public string item_code;
            public int material_type;
        }

        private enum MaterialType
        {
            NONE = 0,
            CHARACTER = 1,
            CHARACTER_PIECE = 2,
        }

        private class ElpisBuildData
        {
            public int index;
            public int build_id;
            public string build_prefab;
            public int facility_type;
            public string buld_name_token;
            public string buld_desc_token;
            public int build_lv;
            public int build_time;
            public int slot_index;
            public int add_unlock_condition;
            public int item_id;
            public int item_INT;
        }

        #endregion
    }
}
