#if UNITY_EDITOR
using CookApps.SpecData.Hive.Editor;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;


namespace CookApps.AutoBattler.Editor
{
    public class GameSpecDownloadCallback : ISpecDownloadCallback
    {
        public void OnSpecDownloadCompleted()
        {
            Debug.Log("[IdMapPostprocessor] OriginalSpecData.json이 변경되었습니다. IdMap.cs를 재생성합니다...");
            IdMapGenerator.Generate();
        }
    }

    public static class IdMapGenerator
    {
        #region 파싱된 데이터 구조

        private class ParsedItemData
        {
            public List<(string itemCode, int itemId)> CurrencyItems = new();
            public List<(string itemCode, int itemId)> ConsumableItems = new();
            public List<(string itemCode, int itemId)> MaterialItems = new();
            public List<int> CharacterIds = new();
            public List<int> CharacterPieceIds = new();
        }

        private class ParsedElpisBuildData
        {
            public List<(int buildId, FacilityType facilityType, int slotIndex)> Builds = new();
        }

        #endregion

        [MenuItem("Tools/Generate IdMap")]
        public static void Generate()
        {
            // OriginalSpecData.json 경로
            string jsonPath = Path.Combine(Application.dataPath, "OriginalSpecData.json");
            if (!File.Exists(jsonPath))
            {
                Debug.LogError($"OriginalSpecData.json not found at: {jsonPath}");
                return;
            }

            // JSON 파일 읽기
            string jsonText = File.ReadAllText(jsonPath);
            var data = Newtonsoft.Json.JsonConvert.DeserializeObject<Dictionary<string, object>>(jsonText);

            // 데이터 한 번에 파싱
            var itemData = ParseItemData(data);
            var elpisData = ParseElpisBuildData(data);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// IdMap - 자동 생성된 ID 맵입니다.");
            sb.AppendLine("// Assets > Tools > Generate IdMap 메뉴로 재생성할 수 있습니다.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace CookApps.AutoBattler");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 각종 ID에 쉽게 접근하기 위한 정적 클래스");
            sb.AppendLine("    /// 사용 예: IdMap.Item.Gold, IdMap.ElpisBuild.CommandCenter");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static partial class IdMap");
            sb.AppendLine("    {");

            // Item 중첩 클래스 생성
            GenerateItemClass(sb, itemData);

            sb.AppendLine();

            // ElpisBuild 중첩 클래스 생성
            GenerateElpisBuildClass(sb, elpisData);

            sb.AppendLine("    }");
            sb.AppendLine();

            // ItemId Extension Methods 생성
            GenerateItemIdExtensions(sb, itemData);

            sb.AppendLine();

            // CheatCurrencyType enum 생성
            GenerateCheatCurrencyTypeEnum(sb, itemData);

            sb.AppendLine("}");

            // 파일 저장
            string outputPath = Path.Combine(Application.dataPath, "_Project/Scripts/Spec/IdMap.cs");
            File.WriteAllText(outputPath, sb.ToString());

            AssetDatabase.Refresh();
            Debug.Log($"IdMap.cs generated at: {outputPath}");
        }

        #region 데이터 파싱

        private static ParsedItemData ParseItemData(Dictionary<string, object> data)
        {
            var result = new ParsedItemData();

            // ItemCurrencyTable 처리
            if (data.ContainsKey("ItemCurrencyTable"))
            {
                var table = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ItemCurrencyData>>(data["ItemCurrencyTable"].ToString());
                foreach (var item in table)
                {
                    if (!string.IsNullOrEmpty(item.item_code))
                    {
                        result.CurrencyItems.Add((item.item_code, item.currency_id));
                    }
                }
            }

            // ItemConsumableTable 처리
            if (data.ContainsKey("ItemConsumableTable"))
            {
                var table = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ItemConsumableData>>(data["ItemConsumableTable"].ToString());
                foreach (var item in table)
                {
                    if (!string.IsNullOrEmpty(item.item_code))
                    {
                        result.ConsumableItems.Add((item.item_code, item.item_id));
                    }
                }
            }

            // ItemMaterialTable 처리
            if (data.ContainsKey("ItemMaterialTable"))
            {
                var table = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ItemMaterialData>>(data["ItemMaterialTable"].ToString());
                foreach (var item in table)
                {
                    if (!string.IsNullOrEmpty(item.item_code))
                    {
                        result.MaterialItems.Add((item.item_code, item.item_id));
                    }

                    if (item.material_type == (int)MaterialType.CHARACTER)
                    {
                        result.CharacterIds.Add(item.item_id);
                    }
                    else if (item.material_type == (int)MaterialType.CHARACTER_PIECE)
                    {
                        result.CharacterPieceIds.Add(item.item_id);
                    }
                }
            }

            return result;
        }

        private static ParsedElpisBuildData ParseElpisBuildData(Dictionary<string, object> data)
        {
            var result = new ParsedElpisBuildData();

            if (data.ContainsKey("ElpisBuildInfo"))
            {
                var table = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ElpisBuildData>>(data["ElpisBuildInfo"].ToString());

                // build_id 기준으로 고유한 값만 추출
                var uniqueBuilds = new Dictionary<int, (FacilityType facilityType, int slotIndex)>();
                foreach (var item in table)
                {
                    if (!uniqueBuilds.ContainsKey(item.build_id))
                    {
                        uniqueBuilds[item.build_id] = ((FacilityType)item.facility_type, item.slot_index);
                    }
                }

                foreach (var kvp in uniqueBuilds)
                {
                    result.Builds.Add((kvp.Key, kvp.Value.facilityType, kvp.Value.slotIndex));
                }
            }

            return result;
        }

        #endregion

        #region 코드 생성

        private static void GenerateItemClass(StringBuilder sb, ParsedItemData itemData)
        {
            sb.AppendLine("        public static partial class Item");
            sb.AppendLine("        {");

            // Currency 섹션
            sb.AppendLine("            // ==================== Currency Items ====================");
            foreach (var (itemCode, itemId) in itemData.CurrencyItems)
            {
                sb.AppendLine($"            public static readonly ItemId {itemCode} = {itemId};");
            }

            sb.AppendLine();
            sb.AppendLine("            // ==================== Consumable Items ====================");
            foreach (var (itemCode, itemId) in itemData.ConsumableItems)
            {
                sb.AppendLine($"            public static readonly ItemId {itemCode} = {itemId};");
            }

            sb.AppendLine();
            sb.AppendLine("            // ==================== Material Items ====================");
            foreach (var (itemCode, itemId) in itemData.MaterialItems)
            {
                sb.AppendLine($"            public static readonly ItemId {itemCode} = {itemId};");
            }

            sb.AppendLine("        }");
        }

        private static void GenerateItemIdExtensions(StringBuilder sb, ParsedItemData itemData)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// ItemId 확장 메서드");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class ItemIdExtensions");
            sb.AppendLine("    {");

            // IsCurrency 함수 생성
            var currencyIds = itemData.CurrencyItems.Select(x => x.itemId).ToList();
            GenerateExtensionMethod(sb, "IsCurrency", currencyIds);

            // IsConsumable 함수 생성
            var consumableIds = itemData.ConsumableItems.Select(x => x.itemId).ToList();
            GenerateExtensionMethod(sb, "IsConsumable", consumableIds);

            // IsMaterial 함수 생성
            var materialIds = itemData.MaterialItems.Select(x => x.itemId).ToList();
            GenerateExtensionMethod(sb, "IsMaterial", materialIds);

            // IsCharacter 함수 생성
            GenerateExtensionMethod(sb, "IsCharacter", itemData.CharacterIds);

            // IsCharacterPiece 함수 생성
            GenerateExtensionMethod(sb, "IsCharacterPiece", itemData.CharacterPieceIds);

            // GetCharacterId 함수 생성
            GenerateGetCharacterIdMethod(sb);

            // GetCharacterPieceId 함수 생성
            GenerateGetCharacterPieceIdMethod(sb, itemData.CharacterIds, itemData.CharacterPieceIds);

            sb.AppendLine("    }");
        }

        private static void GenerateGetCharacterIdMethod(StringBuilder sb)
        {
            sb.AppendLine("        public static bool GetCharacterId(this ItemId id, out int charId)");
            sb.AppendLine("        {");
            sb.AppendLine("            charId = -1;");
            sb.AppendLine("            if (id.IsCharacter())");
            sb.AppendLine("            {");
            sb.AppendLine("                charId = id.Value;");
            sb.AppendLine("                return true;");
            sb.AppendLine("            }");
            sb.AppendLine("            if (id.IsCharacterPiece())");
            sb.AppendLine("            {");
            sb.AppendLine("                charId = id.Value % 10000;");
            sb.AppendLine("                return true;");
            sb.AppendLine("            }");
            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void GenerateGetCharacterPieceIdMethod(StringBuilder sb, List<int> characterIds, List<int> characterPieceIds)
        {
            // characterId -> characterPieceId 매핑 생성
            var mapping = new Dictionary<int, int>();
            foreach (int charId in characterIds)
            {
                int pieceId = characterPieceIds.FirstOrDefault(p => p % 10000 == charId);
                if (pieceId != 0)
                {
                    mapping[charId] = pieceId;
                }
            }

            sb.AppendLine("        public static ItemId GetCharacterPieceId(int characterId)");
            sb.AppendLine("        {");
            sb.AppendLine("            return characterId switch");
            sb.AppendLine("            {");

            foreach (var kvp in mapping.OrderBy(x => x.Key))
            {
                sb.AppendLine($"                {kvp.Key} => {kvp.Value},");
            }

            sb.AppendLine("                _ => default");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void GenerateExtensionMethod(StringBuilder sb, string methodName, List<int> ids)
        {
            sb.AppendLine($"        public static bool {methodName}(this ItemId id)");
            sb.AppendLine("        {");

            if (ids.Count == 0)
            {
                sb.AppendLine("            return false;");
            }
            else
            {
                sb.Append("            return ");
                for (int i = 0; i < ids.Count; i++)
                {
                    if (i > 0)
                        sb.Append(" || ");
                    sb.Append($"id == {ids[i]}");
                }
                sb.AppendLine(";");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void GenerateElpisBuildClass(StringBuilder sb, ParsedElpisBuildData elpisData)
        {
            // FacilityType별로 그룹화
            var groupedBuilds = elpisData.Builds
                .GroupBy(b => b.facilityType)
                .OrderBy(g => (int)g.Key)
                .ToList();

            sb.AppendLine("        public static class ElpisBuild");
            sb.AppendLine("        {");

            foreach (var group in groupedBuilds)
            {
                sb.AppendLine($"            // ==================== {group.Key} ====================");

                var sortedBuilds = group.OrderBy(b => b.slotIndex).ThenBy(b => b.buildId).ToList();

                if (sortedBuilds.Count == 1)
                {
                    var build = sortedBuilds[0];
                    string name = GetFacilityName(build.facilityType);
                    sb.AppendLine($"            public const int {name} = {build.buildId};");
                }
                else
                {
                    for (int i = 0; i < sortedBuilds.Count; i++)
                    {
                        var build = sortedBuilds[i];
                        string name = GetFacilityName(build.facilityType);
                        sb.AppendLine($"            public const int {name}_{i + 1} = {build.buildId};");
                    }
                }

                sb.AppendLine();
            }

            // 마지막 빈 줄 제거
            sb.Length -= System.Environment.NewLine.Length;

            sb.AppendLine("        }");
        }

        private static string GetFacilityName(FacilityType facilityType)
        {
            return facilityType switch
            {
                FacilityType.COMMAND_CENTER => "CommandCenter",
                FacilityType.NEST => "Nest",
                FacilityType.DIMENSION_LAB => "DimensionLab",
                FacilityType.SIMULATION_CENTER => "SimulationCenter",
                _ => $"Unknown_{(int)facilityType}"
            };
        }

        private static void GenerateCheatCurrencyTypeEnum(StringBuilder sb, ParsedItemData itemData)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 치트용 재화 타입 (SROptions 드롭다운용)");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public enum CheatCurrencyType");
            sb.AppendLine("    {");

            foreach (var (itemCode, itemId) in itemData.CurrencyItems)
            {
                sb.AppendLine($"        {itemCode} = {itemId},");
            }

            foreach (var (itemCode, itemId) in itemData.ConsumableItems)
            {
                sb.AppendLine($"        {itemCode} = {itemId},");
            }

            // 캐릭터 추가
            if (itemData.CharacterIds.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("        // 캐릭터");
                foreach (int charId in itemData.CharacterIds.OrderBy(x => x))
                {
                    sb.AppendLine($"        캐릭터_{charId} = {charId},");
                }
            }

            // 캐릭터 조각 추가
            if (itemData.CharacterPieceIds.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("        // 캐릭터 조각");
                foreach (int pieceId in itemData.CharacterPieceIds.OrderBy(x => x % 10000))
                {
                    int characterId = pieceId % 10000;
                    sb.AppendLine($"        조각_{characterId} = {pieceId},");
                }
            }

            sb.AppendLine("    }");
        }

        #endregion

        #region JSON 파싱용 데이터 클래스

        private class ItemCurrencyData
        {
            public int currency_id;
            public string item_code;
        }

        private class ItemConsumableData
        {
            public int item_id;
            public string item_code;
        }

        private class ItemMaterialData
        {
            public int item_id;
            public string item_code;
            public int material_type;
        }

        private enum MaterialType
        {
            CHARACTER = 1,
            CHARACTER_PIECE = 2,
        }

        private class ElpisBuildData
        {
            public int index;
            public int build_id;
            public string build_prefab;
            public int facility_type;
            public string buld_name_token;
            public string buld_desc_token;
            public int build_lv;
            public int build_time;
            public int slot_index;
            public int add_unlock_condition;
            public int item_id;
            public int item_INT;
        }

        #endregion
    }
}
#endif
