using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace CookApps.AutoBattler.Editor
{
    public static class ItemIdMapGenerator
    {
        [MenuItem("Tools/Generate ItemIdMap")]
        public static void GenerateItemIdMap()
        {
            // OriginalSpecData.json 경로
            string jsonPath = Path.Combine(Application.dataPath, "OriginalSpecData.json");
            if (!File.Exists(jsonPath))
            {
                Debug.LogError($"OriginalSpecData.json not found at: {jsonPath}");
                return;
            }

            // JSON 파일 읽기
            string jsonText = File.ReadAllText(jsonPath);
            var data = Newtonsoft.Json.JsonConvert.DeserializeObject<Dictionary<string, object>>(jsonText);

            var items = new List<(string itemCode, int itemId, string itemType)>();

            // ItemCurrencyTable 처리
            if (data.ContainsKey("ItemCurrencyTable"))
            {
                var table = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ItemCurrencyData>>(data["ItemCurrencyTable"].ToString());
                foreach (var item in table)
                {
                    if (!string.IsNullOrEmpty(item.item_code))
                    {
                        items.Add((item.item_code, item.currency_id, "Currency"));
                    }
                }
            }

            // ItemConsumableTable 처리
            if (data.ContainsKey("ItemConsumableTable"))
            {
                var table = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ItemConsumableData>>(data["ItemConsumableTable"].ToString());
                foreach (var item in table)
                {
                    if (!string.IsNullOrEmpty(item.item_code))
                    {
                        items.Add((item.item_code, item.item_id, "Consumable"));
                    }
                }
            }

            // ItemMaterialTable 처리
            if (data.ContainsKey("ItemMaterialTable"))
            {
                var table = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ItemMaterialData>>(data["ItemMaterialTable"].ToString());
                foreach (var item in table)
                {
                    if (!string.IsNullOrEmpty(item.item_code))
                    {
                        items.Add((item.item_code, item.item_id, "Material"));
                    }
                }
            }

            // C# 코드 생성
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// ItemIdMap - 자동 생성된 아이템 ID 맵입니다.");
            sb.AppendLine("// Assets > Tools > Generate ItemIdMap 메뉴로 재생성할 수 있습니다.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace CookApps.AutoBattler");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 아이템 ID에 쉽게 접근하기 위한 정적 클래스");
            sb.AppendLine("    /// 사용 예: ItemIdMap.Gold, ItemIdMap.Gem");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class ItemIdMap");
            sb.AppendLine("    {");

            // Currency 섹션
            sb.AppendLine("        // ==================== Currency Items ====================");
            foreach (var (itemCode, itemId, itemType) in items)
            {
                if (itemType == "Currency")
                {
                    sb.AppendLine($"        public const int {itemCode} = {itemId};");
                }
            }

            sb.AppendLine();
            sb.AppendLine("        // ==================== Consumable Items ====================");
            // Consumable 섹션
            foreach (var (itemCode, itemId, itemType) in items)
            {
                if (itemType == "Consumable")
                {
                    sb.AppendLine($"        public const int {itemCode} = {itemId};");
                }
            }

            sb.AppendLine();
            sb.AppendLine("        // ==================== Material Items ====================");
            // Material 섹션
            foreach (var (itemCode, itemId, itemType) in items)
            {
                if (itemType == "Material")
                {
                    sb.AppendLine($"        public const int {itemCode} = {itemId};");
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            // 파일 저장
            string outputPath = Path.Combine(Application.dataPath, "_Project/Scripts/Spec/ItemIdMap.cs");
            File.WriteAllText(outputPath, sb.ToString());

            AssetDatabase.Refresh();
            Debug.Log($"ItemIdMap.cs generated with {items.Count} items at: {outputPath}");
        }

        // JSON 파싱용 데이터 클래스
        private class ItemCurrencyData
        {
            public int currency_id;
            public string item_code;
        }

        private class ItemConsumableData
        {
            public int item_id;
            public string item_code;
        }

        private class ItemMaterialData
        {
            public int item_id;
            public string item_code;
        }
    }
}
