// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

namespace CookApps.AutoBattler
{

    public enum CharacterEffect
    {
        NONE = 0,
        AD_UP = 1,
        AD_PERCENT_UP = 2,
        AP_UP = 3,
        AP_PERCENT_UP = 4,
        DEF_UP = 5,
        DEF_PERCENT_UP = 6,
        RES_UP = 7,
        RES_PERCENT_UP = 8,
        DEF_PENETRATION_UP = 9,
        DEF_PENETRATION_PERCENT_UP = 10,
        RES_PENETRATION_UP = 11,
        RES_PENETRATION_PERCENT_UP = 12,
        HP_RECOVERY_UP = 13,
        HP_RECOVERY_PERCENT_UP = 14,
        MOVESPEED_UP = 15,
        MOVESPEED_PERCENT_UP = 16,
    }

    public enum Grade
    {
        COMMON = 1,
        RARE = 2,
        EPIC = 3,
        LEGEND = 4,
        ANCIENT = 5,
    }

    public enum RewardType
    {
        JEWEL = 1,
        GOLD = 2,
        SOUL = 3,
        AP = 4,
        C_TICKET = 5,
        W_TICKET = 6,
        USER_USER_EXP = 7,
        CHAR_USER_EXP_ITEM = 8,
        DUNGEON_KEY1 = 9,
        DUNGEON_KEY2 = 10,
        DUNGEON_KEY3 = 11,
        KNIGHT = 12,
        KNIGHT_PIECE = 13,
        RANDOM_WEAPON_PIECE = 14,
        RUNE = 15,
        BUILDING_SUPPLIES = 16,
        RANDOM_KNIGHT_PIECE = 17,
        CHARACTER_PIECE = 18,
        CHAR_USER_EXP_ITEM_2 = 19,
        CHAR_TRANSCENDENCE_FIRE = 20,
        CHAR_TRANSCENDENCE_WATER = 21,
        CHAR_TRANSCENDENCE_EARTH = 22,
        CHAR_TRANSCENDENCE_WIND = 23,
        CHAR_TRANSCENDENCE_LIGHT = 24,
        CHAR_TRANSCENDENCE_DARK = 25,
        TIME_REWARD_ARTIFACT = 26,
        CHARACTER = 27,
        BREAD = 28,
        USER_EXP = 29,
    }

    public enum CharacterType
    {
        NONE = 0,
        EARTH = 1,
        WIND = 2,
        WATER = 3,
        FIRE = 4,
        DARK = 5,
        LIGHT = 6,
        MACHINE = 7,
    }

    public enum CharacterPosition
    {
        NONE = 0,
        WARRIOR = 1,
        TANK = 2,
        WIZARD = 3,
        RANGER = 4,
        ASSASSIN = 5,
        SUPPORTER = 6,
    }

    public enum AttackRangeShape
    {
        Rectangle = 1,
        RectangleCut1Edge = 2,
        RectangleCut2Edge = 3,
        RectangleCut3Edge = 4,
        RectangleCut4Edge = 5,
        RectangleCut5Edge = 6,
    }

    public enum DifficultyType
    {
        NORMAL = 1,
        HARD = 2,
    }

    public enum StageType
    {
        BATTLE_NORMAL = 1,
        BATTLE_ELITE = 2,
        BATTLE_BOSS = 3,
        CHEST = 4,
    }

    public enum MonsterType
    {
        NORMAL = 1,
        ELITE = 2,
        BOSS = 3,
    }

    public enum ContentType
    {
        STAGE = 1,
        CHAPTER = 2,
        DUNGEON = 3,
        ACCOUNT_LV_EXP = 4,
        STAGE_STAR = 5,
    }

    public enum ContentSubType
    {
        NONE = 0,
        NORMAL = 1,
        HARD = 2,
    }

    public enum TutorialEventType
    {
        SHOW_DIALOGUE = 1,
        OPEN_MENU = 2,
        HIGHLIGHT_BUTTON = 3,
    }

    public enum DirectionType
    {
        UP = 1,
        DOWN = 2,
        LEFT = 3,
        RIGHT = 4,
    }

    public enum FrequencyType
    {
        ONCE = 1,
        REPEAT = 2,
    }

    public enum ConfigValueType
    {
        STRING = 0,
        INT = 1,
        FLOAT = 2,
    }

    public enum AtkType
    {
        AD = 1,
        AP = 2,
        ALL = 3,
    }

    public enum SkillValueType
    {
        PERCENT = 1,
        TIME = 2,
    }

    public enum SkillType
    {
        none = 1,
        normal = 2,
        weapon = 3,
    }
}
