// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using CookApps.SpecData.Generator;

namespace CookApps.AutoBattler
{

    [GeneratorSpecData]
    public partial class SpecOption
    {
        [GeneratorId(nameof(name), typeof(string))]
        public string name;
        public string value;
    }

    [GeneratorSpecData]
    public partial class SpecChest
    {
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        public CookApps.Obfuscator.ObfuscatorInt chest_id;
        public global::CookApps.AutoBattler.RewardType type;
        public CookApps.Obfuscator.ObfuscatorInt key;
        public CookApps.Obfuscator.ObfuscatorInt value;
        public CookApps.Obfuscator.ObfuscatorDouble rate;
    }

    [GeneratorSpecData]
    public partial class SpecCharacter
    {
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// ?
        public CookApps.Obfuscator.ObfuscatorInt seq;
        public CookApps.Obfuscator.ObfuscatorInt prefab_id;
        public CookApps.Obfuscator.ObfuscatorInt chapter;
        public string nickname_token;
        public string name_token;
        public string desc_token;
        public global::CookApps.AutoBattler.Grade grade;
        public CookApps.Obfuscator.ObfuscatorInt need_piece;
        /// ?
        public global::CookApps.AutoBattler.CharacterType type;
        /// ?
        public global::CookApps.AutoBattler.CharacterPosition position;
        public CookApps.Obfuscator.ObfuscatorInt init_star;
        public CookApps.Obfuscator.ObfuscatorInt max_star;
        public CookApps.Obfuscator.ObfuscatorInt stat_hp;
        /// 공격 계산식 & 레벨업 스텟 계산식?
        public CookApps.Obfuscator.ObfuscatorInt stat_atk;
        public CookApps.Obfuscator.ObfuscatorInt stat_def;
        /// 관통?
        public CookApps.Obfuscator.ObfuscatorInt stat_atk_pierce;
        public CookApps.Obfuscator.ObfuscatorFloat inc_rate;
        public CookApps.Obfuscator.ObfuscatorFloat inc_star;
        public CookApps.Obfuscator.ObfuscatorFloat crit_power;
        public CookApps.Obfuscator.ObfuscatorFloat crit_rate;
        public CookApps.Obfuscator.ObfuscatorDouble base_inc;
        public CookApps.Obfuscator.ObfuscatorFloat atkSpd;
        public CookApps.Obfuscator.ObfuscatorInt atkRange;
        public global::CookApps.AutoBattler.AttackRangeShape atkRangeShape;
        public CookApps.Obfuscator.ObfuscatorInt[] skill_ids;
        public CookApps.Obfuscator.ObfuscatorInt equipment_id;
        public CookApps.Obfuscator.ObfuscatorInt[] upgrade_skill_ids;
        public CookApps.Obfuscator.ObfuscatorFloat scale;
    }

    [GeneratorSpecData]
    public partial class SpecStage
    {
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        public CookApps.Obfuscator.ObfuscatorInt chapter_id;
        public CookApps.Obfuscator.ObfuscatorInt dialogue_id;
        public CookApps.Obfuscator.ObfuscatorInt attr;
        public CookApps.Obfuscator.ObfuscatorInt stage_id;
        public bool is_elite;
        public CookApps.Obfuscator.ObfuscatorInt limit_count;
        public CookApps.Obfuscator.ObfuscatorInt cost;
        public CookApps.Obfuscator.ObfuscatorInt cost_hard;
        public CookApps.Obfuscator.ObfuscatorInt front_1;
        public CookApps.Obfuscator.ObfuscatorInt front_1Lv;
        public CookApps.Obfuscator.ObfuscatorInt front_2;
        public CookApps.Obfuscator.ObfuscatorInt front_2Lv;
        public CookApps.Obfuscator.ObfuscatorInt front_3;
        public CookApps.Obfuscator.ObfuscatorInt front_3Lv;
        public CookApps.Obfuscator.ObfuscatorInt mid_1;
        public CookApps.Obfuscator.ObfuscatorInt mid_1Lv;
        public CookApps.Obfuscator.ObfuscatorInt mid_2;
        public CookApps.Obfuscator.ObfuscatorInt mid_2Lv;
        public CookApps.Obfuscator.ObfuscatorInt mid_3;
        public CookApps.Obfuscator.ObfuscatorInt mid_3Lv;
        public CookApps.Obfuscator.ObfuscatorInt back_1;
        public CookApps.Obfuscator.ObfuscatorInt back_1Lv;
        public CookApps.Obfuscator.ObfuscatorInt back_2;
        public CookApps.Obfuscator.ObfuscatorInt back_2Lv;
        public CookApps.Obfuscator.ObfuscatorInt back_3;
        public CookApps.Obfuscator.ObfuscatorInt back_3Lv;
        public CookApps.Obfuscator.ObfuscatorFloat multiple;
        public CookApps.Obfuscator.ObfuscatorInt hard_add_lv;
        public CookApps.Obfuscator.ObfuscatorFloat hard_multiple;
        public CookApps.Obfuscator.ObfuscatorInt chest_id;
        public CookApps.Obfuscator.ObfuscatorInt hard_chest_id;
        public global::CookApps.AutoBattler.RewardType star_reward_type_1;
        /// ?
        public CookApps.Obfuscator.ObfuscatorInt star_reward_key_1;
        public CookApps.Obfuscator.ObfuscatorInt star_reward_count_1;
        public global::CookApps.AutoBattler.RewardType star_reward_type_2;
        /// ?
        public CookApps.Obfuscator.ObfuscatorInt star_reward_key_2;
        public CookApps.Obfuscator.ObfuscatorInt star_reward_count_2;
        public global::CookApps.AutoBattler.RewardType star_reward_type_3;
        /// ?
        public CookApps.Obfuscator.ObfuscatorInt star_reward_key_3;
        public CookApps.Obfuscator.ObfuscatorInt star_reward_count_3;
    }

    [GeneratorSpecData]
    public partial class CommanderSkill
    {
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        public CookApps.Obfuscator.ObfuscatorInt skill_id;
        public string name_token;
        public string desc_token;
    }

    [GeneratorSpecData]
    public partial class CommanderSkillUpgrade
    {
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        public CookApps.Obfuscator.ObfuscatorInt skill_group_id;
        public CookApps.Obfuscator.ObfuscatorInt level;
        public CookApps.Obfuscator.ObfuscatorInt recipe_item_id;
        public CookApps.Obfuscator.ObfuscatorInt recipe_item_amount;
    }

    [GeneratorSpecData]
    public partial class AccountLevelExp
    {
        /// 유니크 id
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 계정 레벨
        public CookApps.Obfuscator.ObfuscatorInt lv;
        /// 시작 경험치
        public CookApps.Obfuscator.ObfuscatorDouble exp_start;
        /// 마지막 경험치
        public CookApps.Obfuscator.ObfuscatorDouble exp_last;
        /// 레벨 당 필요 경험치
        public CookApps.Obfuscator.ObfuscatorDouble exp_need;
        /// 행동력 보유 가능 최대량
        public CookApps.Obfuscator.ObfuscatorInt ap_max;
        /// 리워드 id
        public CookApps.Obfuscator.ObfuscatorInt reward_id;
        /// 캐릭터 배치 가능 수
        public CookApps.Obfuscator.ObfuscatorInt squad_count;
    }

    [GeneratorSpecData]
    public partial class Chapter
    {
        /// ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 챕터 ID
        public CookApps.Obfuscator.ObfuscatorInt chapter_id;
        /// 난이도
        public global::CookApps.AutoBattler.DifficultyType difficulty;
        /// 챕터 타이틀 토큰
        public string name_token;
        /// 챕터 세부 설명 토큰
        public string desc_token;
        /// 클리어 보상 id
        public CookApps.Obfuscator.ObfuscatorInt reward_id;
        /// 진입 일러스트 ID
        public string clear_pack_bg_image;
        /// 클리어 패키지 이미지 ID
        public string clear_pack_char_image;
    }

    [GeneratorSpecData]
    public partial class Character
    {
        /// 캐릭터_id
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 캐릭터 등급
        public global::CookApps.AutoBattler.Grade grade;
        /// 전체 리스트 출력 순서
        public CookApps.Obfuscator.ObfuscatorInt seq;
        /// 캐릭터 이름 토큰
        public string name_token;
        /// 캐릭터 설명 토큰
        public string desc_token;
        /// 해금 필요 조각
        public CookApps.Obfuscator.ObfuscatorInt need_piece;
        /// 속성 시너지
        public global::CookApps.AutoBattler.CharacterType element_type;
        /// 포지션 시너지
        public global::CookApps.AutoBattler.CharacterPosition class_type;
        /// 태생 등급
        public CookApps.Obfuscator.ObfuscatorInt init_star;
        /// 최대 등급
        public CookApps.Obfuscator.ObfuscatorInt max_star;
        /// 초월 성장 비율
        public CookApps.Obfuscator.ObfuscatorFloat inc_trancendence;
        /// 체력
        public CookApps.Obfuscator.ObfuscatorInt stat_hp;
        /// 공격력
        public CookApps.Obfuscator.ObfuscatorInt stat_atk;
        /// AP AD 판정 유무
        public global::CookApps.AutoBattler.AtkType atk_type;
        /// 체력, 공격력 레벨 당 성장율
        public CookApps.Obfuscator.ObfuscatorFloat inc_rate;
        /// 방어력
        public CookApps.Obfuscator.ObfuscatorInt stat_def;
        /// 관통력
        public CookApps.Obfuscator.ObfuscatorInt stat_atk_pierce;
        /// 치명률
        public CookApps.Obfuscator.ObfuscatorFloat crit_rate;
        /// 치명타 피해량
        public CookApps.Obfuscator.ObfuscatorFloat crit_power;
        /// 공격 속도
        public CookApps.Obfuscator.ObfuscatorFloat atkSpd;
        /// 공격 범위
        public CookApps.Obfuscator.ObfuscatorInt atkRange;
        /// 공격 범위 형태
        public global::CookApps.AutoBattler.AttackRangeShape atkRangeShape;
        /// 일반 스킬 id
        public CookApps.Obfuscator.ObfuscatorInt skill_id;
        /// 전용 장비 id
        public CookApps.Obfuscator.ObfuscatorInt equipment_id;
        /// 전용 스킬 id
        public CookApps.Obfuscator.ObfuscatorInt upgrade_skill_ids;
        /// 가챠 확률
        public CookApps.Obfuscator.ObfuscatorFloat weight;
    }

    [GeneratorSpecData]
    public partial class CharacterLevelExp
    {
        /// 유니크 ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 캐릭터 레벨
        public CookApps.Obfuscator.ObfuscatorInt lv;
        /// 경험치 필요량
        public CookApps.Obfuscator.ObfuscatorDouble exp_item;
        /// 경험치 아이템 누적 필요량
        public CookApps.Obfuscator.ObfuscatorDouble exp_item_sum;
        /// 골드 필요량
        public CookApps.Obfuscator.ObfuscatorDouble gold;
        /// 골드 누적 필요량
        public CookApps.Obfuscator.ObfuscatorDouble gold_sum;
        /// 2차 재화 필요량
        public CookApps.Obfuscator.ObfuscatorDouble exp_item_2;
        /// 2차 재화 누적 필요량
        public CookApps.Obfuscator.ObfuscatorDouble exp_item_2_sum;
        /// 초월 가능 여부
        public bool is_transcendence;
    }

    [GeneratorSpecData]
    public partial class CharacterTranscendence
    {
        /// 유니크 ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 시너지 종류
        public global::CookApps.AutoBattler.CharacterType type;
        /// 캐릭터 등급
        public global::CookApps.AutoBattler.Grade grade;
        /// 캐릭터 초월 레벨
        public CookApps.Obfuscator.ObfuscatorInt transcendence_lv;
        /// 캐릭터 맥스 레벨
        public CookApps.Obfuscator.ObfuscatorInt max_lv;
        /// 캐릭터 초월 아이템 필요 종류
        public global::CookApps.AutoBattler.RewardType char_transcendence_item;
        /// 캐릭터 초월 아이템 필요량
        public CookApps.Obfuscator.ObfuscatorDouble char_transcendence_count;
        /// 캐릭터 초월 아이템 누적 필요량
        public CookApps.Obfuscator.ObfuscatorDouble char_transcendence_item_sum;
    }

    [GeneratorSpecData]
    public partial class CharacterEnhance
    {
        /// 유니크id
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 캐릭터 등급
        public global::CookApps.AutoBattler.Grade grade;
        /// 태생 별 개수
        public CookApps.Obfuscator.ObfuscatorInt star;
        /// 조각 필요량
        public CookApps.Obfuscator.ObfuscatorInt piece;
        /// 최대 레벨
        public CookApps.Obfuscator.ObfuscatorInt max_level;
    }

    [GeneratorSpecData]
    public partial class Dialogue
    {
        /// 유니크 ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 그룹  ID
        public CookApps.Obfuscator.ObfuscatorInt dialouge_id;
        /// 발화자 ID
        public CookApps.Obfuscator.ObfuscatorInt character_id;
        /// 발화자 이름 토큰
        public string character_name_desc_token;
        /// 다이얼로그 토큰
        public string text_desc_token;
        /// 다이얼로그 상단 이미지
        public string bg_image;
        /// 이미지 크기
        public CookApps.Obfuscator.ObfuscatorFloat bg_image_scale;
    }

    [GeneratorSpecData]
    public partial class GameConfig
    {
        /// 아이디
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 키 값
        public string config_key;
        /// 자료형 타입
        public global::CookApps.AutoBattler.ConfigValueType config_value_type;
        /// 값
        public string config_value;
    }

    [GeneratorSpecData]
    public partial class Monster
    {
        /// 몬스터 ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 몬스터 등급
        public global::CookApps.AutoBattler.Grade grade;
        /// 몬스터 이름 토큰
        public string name_token;
        /// 몬스터 설명 토큰
        public string desc_token;
        /// 몬스터 타입
        public global::CookApps.AutoBattler.MonsterType monster_type;
        /// 속성 시너지 타입
        public global::CookApps.AutoBattler.CharacterType type;
        /// 포지션 시너지 타입
        public global::CookApps.AutoBattler.CharacterPosition position;
        /// 태생 등급
        public CookApps.Obfuscator.ObfuscatorInt init_star;
        /// 최대 등급
        public CookApps.Obfuscator.ObfuscatorInt max_star;
        /// 승급 성장율
        public CookApps.Obfuscator.ObfuscatorFloat inc_star;
        /// 체력 스탯
        public CookApps.Obfuscator.ObfuscatorInt stat_hp;
        /// 공격력 스탯
        public CookApps.Obfuscator.ObfuscatorInt stat_atk;
        /// 체력, 공격력 성장율
        public CookApps.Obfuscator.ObfuscatorFloat inc_rate;
        /// 방어력
        public CookApps.Obfuscator.ObfuscatorInt stat_def;
        /// 관통력
        public CookApps.Obfuscator.ObfuscatorInt stat_atk_pierce;
        /// 치명률
        public CookApps.Obfuscator.ObfuscatorFloat crit_rate;
        /// 치명타 피해량
        public CookApps.Obfuscator.ObfuscatorFloat crit_power;
        /// 공격속도
        public CookApps.Obfuscator.ObfuscatorFloat atk_spd;
        /// 공격 범위
        public CookApps.Obfuscator.ObfuscatorInt atk_range;
        /// 공격 범위 형태
        public global::CookApps.AutoBattler.AttackRangeShape atk_range_shape;
        /// 일반 스킬 ID
        public CookApps.Obfuscator.ObfuscatorInt skill_id;
    }

    [GeneratorSpecData]
    public partial class Skill
    {
        /// 유니크 id
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 스킬 id
        public CookApps.Obfuscator.ObfuscatorInt skill_id;
        /// 스킬 타입
        public global::CookApps.AutoBattler.SkillType skill_type;
        /// 캐릭터 ID
        public CookApps.Obfuscator.ObfuscatorInt character_id;
        /// 전용 무기 id
        public CookApps.Obfuscator.ObfuscatorInt weapon_id;
        /// #스킬 사용자
        public string character_name;
        /// AP AD 판정 유무
        public global::CookApps.AutoBattler.AtkType atk_type;
        /// 스킬 이름 토큰
        public string skill_name_token;
        /// 스킬 설명 토큰
        public string skill_desc_token;
        /// #스킬 설명
        public string skill_desc;
        /// 스킬 계수 타입
        public global::CookApps.AutoBattler.SkillValueType skill_value_type;
        /// 스킬 계수
        public CookApps.Obfuscator.ObfuscatorFloat base_rate;
        /// 스킬 쿨타임
        public CookApps.Obfuscator.ObfuscatorFloat cool;
    }

    [GeneratorSpecData]
    public partial class Stage
    {
        /// 전체 ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 난이도
        public global::CookApps.AutoBattler.DifficultyType difficulty;
        /// 챕터
        public CookApps.Obfuscator.ObfuscatorInt chapter_id;
        /// 스테이지 번호
        public CookApps.Obfuscator.ObfuscatorInt stage_number;
        /// 다이얼로그 ID
        public CookApps.Obfuscator.ObfuscatorInt dialogue_id;
        /// 스테이지 타입
        public global::CookApps.AutoBattler.StageType stage_type;
        /// 플레이 제한 횟수
        public CookApps.Obfuscator.ObfuscatorInt limit_count;
        /// 행동력
        public CookApps.Obfuscator.ObfuscatorInt need_ap;
        /// 리워드 2차 분류
        public global::CookApps.AutoBattler.ContentSubType reward_content_type;
        /// 어려움 난이도 행동력
        public CookApps.Obfuscator.ObfuscatorInt ap_HARD;
        /// 클리어 보상 id
        public CookApps.Obfuscator.ObfuscatorInt reward_id;
        /// 어려움 클리어 보상 id
        public CookApps.Obfuscator.ObfuscatorInt reward_HARD_id;
    }

    [GeneratorSpecData]
    public partial class StageMonster
    {
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 챕터 id
        public CookApps.Obfuscator.ObfuscatorInt chapter_id;
        /// 난이도
        public global::CookApps.AutoBattler.DifficultyType difficulty;
        /// 스테이지 번호
        public CookApps.Obfuscator.ObfuscatorInt stage_number;
        /// 좌표값 (x,y)
        public string coordinate;
        /// 몬스터 id
        public CookApps.Obfuscator.ObfuscatorInt monster_id;
        /// 몬스터 레벨
        public CookApps.Obfuscator.ObfuscatorInt monster_lv;
        /// 공격력 멀티플
        public CookApps.Obfuscator.ObfuscatorInt multiple_atk;
        /// 체력 멀티플
        public CookApps.Obfuscator.ObfuscatorInt multiple_hp;
    }

    [GeneratorSpecData]
    public partial class Tutorial
    {
        /// 유니크 id
        [GeneratorId(nameof(ID), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt ID;
        /// 오픈 컨텐츠 대분류
        public string tuto_group_id;
        /// 다이얼로그 id
        public CookApps.Obfuscator.ObfuscatorInt dialouge_id;
        /// 다이얼로그 출력 위치
        public string dialouge_location;
        /// 다음 유니크 id
        public CookApps.Obfuscator.ObfuscatorInt seq;
        public global::CookApps.AutoBattler.TutorialEventType event_type;
        /// 오픈 콘텐츠 타입
        public string tutorial_open_type;
        /// 오픈 대상 세부 id
        public CookApps.Obfuscator.ObfuscatorInt open_key;
        /// 포커싱 영역
        public string focus_object_name;
        /// 포커싱 영역 너비
        public string focus_object_scale;
        /// 버튼 클릭 영역
        public string focus_btn_name;
        /// 화살표의 방향 (위 아래)
        public global::CookApps.AutoBattler.DirectionType arrow_y_up;
    }

    [GeneratorSpecData]
    public partial class RewardInfo
    {
        /// 유니크 id
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 컨텐츠 메인 분류
        public global::CookApps.AutoBattler.ContentType content_type;
        /// 컨텐츠 서브 분류
        public global::CookApps.AutoBattler.ContentSubType content_sub_type;
        /// 컨텐츠 추가 구분 값
        public CookApps.Obfuscator.ObfuscatorInt content_key_value;
        /// 보상 id
        public CookApps.Obfuscator.ObfuscatorInt reward_id;
        /// 보상 공급 확률 유무
        public string prob_type;
        /// 보상 획득 빈도
        public global::CookApps.AutoBattler.FrequencyType frequency_type;
        /// 보상 타입
        public global::CookApps.AutoBattler.RewardType reward_type;
        /// 보상 타입_소분류
        public CookApps.Obfuscator.ObfuscatorInt sub_value;
        /// 보상 키 값
        public CookApps.Obfuscator.ObfuscatorInt reward_key;
        /// 보상 수량
        public CookApps.Obfuscator.ObfuscatorInt reward_value;
        /// 보상 지급 확률
        public CookApps.Obfuscator.ObfuscatorDouble rate;
    }

    [GeneratorSpecData]
    public partial class Item
    {
        /// 유니크 ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 보상 타입 이름
        public global::CookApps.AutoBattler.RewardType reward_type;
        /// 보상 등급
        public global::CookApps.AutoBattler.Grade grade;
        /// 보상 이름 토큰
        public string name_token;
        /// 보상 설명 토큰
        public string desc_token;
        /// 보상 획득 채널 토큰
        public string desc_token_1;
        /// 인벤토리 표시 유무
        public bool info_show;
        /// 사용 가능 유무
        public bool is_consumable;
        /// 합성 요구량
        public CookApps.Obfuscator.ObfuscatorInt merge_count;
        /// 세부 ID 특정 가능 여부
        public bool is_common;
    }
}
