// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

namespace CookApps.AutoBattler
{

    /// #SheetIndex
    public enum EffectCodeNameType
    {
        NONE = 0,
        AD_UP = 1,
        AD_PERCENT_UP = 2,
        AP_UP = 3,
        AP_PERCENT_UP = 4,
        HP_UP = 5,
        HP_PERCENT_UP = 6,
        RES_UP = 9,
        RES_PERCENT_UP = 10,
        AD_PIERCE_UP = 11,
        AD_PIERCE_PERCENT_UP = 12,
        AP_PIERCE_UP = 13,
        AP_PIERCE_PERCENT_UP = 14,
        HP_RECOVERY_UP = 15,
        HP_RECOVERY_PERCENT_UP = 16,
        MOVESPEED_UP = 17,
        MOVESPEED_PERCENT_UP = 18,
        VIEW_SCALE_UP = 19,
        PURE_DAMAGE_PROB_UP = 20,
        CRIT_RATE_PERCENT_UP = 21,
        CRIT_POWER_PERCENT_UP = 22,
        ATK_SPEED_PERCENT_UP = 23,
        AD_REDUCE_PERCENT_UP = 24,
        AP_REDUCE_PERCENT_UP = 25,
        HIT_PROB_PERCENT_UP = 26,
        AVOID_PROB_PERCENT_UP = 27,
        BLOCKING_PROB_PERCENT_UP = 28,
        DEF_PERCENT_UP = 29,
        DEF_UP = 30,
        CRIT_RATE_UP = 31,
        ATK_SPEED_UP = 32,
        CRIT_POWER_UP = 33,
        BATTLE_ITEM_SUPERNOVA = 96101,
        BATTLE_ITEM_SUPERNOVA_DRAGGING_EFFECT = 96102,
        BATTLE_ITEM_DYNAMITE = 96201,
        BATTLE_ITEM_SUPPLY = 96301,
        DROPPING_BOMBS = 96401,
        COMMANDER_SKILL_EXPLOSION = 300001,
        COMMANDER_SKILL_FREEZING = 300002,
        COMMANDER_SKILL_AIRBORNE = 300003,
        COMMANDER_SKILL_LIFEHEAL = 300004,
        COMMANDER_SKILL_TELEPORT = 300005,
        COMMANDER_SKILL_CURSE = 300006,
        COMMANDER_SKILL_EARTHEN_SOLDIERS = 300300,
        TILE_BURN = 1000000001,
        DAMAGE = 1000000002,
        MAX_HP_DAMAGE = 1000000003,
        CC_STUN = 1100000001,
        SHIELD = 1100000002,
        CC_KNOCKBACK = 1100000003,
        CC_AIRBORNE = 1100000005,
        CC_MISA_RESTRAINT = 1100000006,
        CC_TARGET_IMPOSSIBLE = 1100000007,
        CC_BLIND = 1100000008,
        CC_SEAL = 1100000009,
        CC_AGGRO = 1100000010,
        CC_FREEZ = 1100000011,
        CC_SLIENCE = 1100000012,
        CC_PARALYSIS = 1100000013,
        CC_CHARM = 1100000014,
        CC_PETRIFY = 1100000015,
        CHAPTER_FIRE = 1200000001,
        CHAPTER_ICE = 1200000002,
        CHAPTER_LANDMINE = 1200000003,
        CHAPTER_SANDSTORM = 1200000004,
        CHAPTER_RANDOM_MOVE = 1200000005,
        CHAPTER_TRAP = 1200000006,
        RULE_AD = 1210000001,
        RULE_AD_REDUCE_UP = 1210000002,
        RULE_AP = 1210000003,
        JOBS_BRAVE = 1300000001,
        JOBS_ENDURE = 1300000002,
        JOBS_PIERCE = 1300000003,
        JOBS_ESPER = 1300000004,
        JOBS_RECOVERY = 1300000005,
        JOBS_AMBUSH = 1300000006,
        JOBS_CRITICAL_STACK = 1300000007,
        DEBUFF_SPECIAL_MARIE_ARACNE = 1900000017,
        DEBUFF_SPECIAL_ODETTE_COLD = 1900000018,
        BUFF_SPECIAL_BLIN_HEAT = 1900000019,
        BUFF_SPECIAL_RUKIDA_FOXFIRE = 1900000020,
        BUFF_SPECIAL_MEDITATION = 1900000026,
        BUFF_SPECIAL_ANGER = 1900000027,
        BUFF_SPECIAL_NO_DAMAGE_SHIELD = 1900000028,
        BUFF_SPECIAL_APRIL_STANDER = 1900000030,
        BUFF_SPECIAL_TETORRA_ANGER = 1900000031,
        BUFF_SPECIAL_SHIRAYUKI_AVOID_AND_ATTACK = 1900000032,
        BUFF_SPECIAL_ENKI_PASSIVE_HEALUP = 1900000033,
        BUFF_SPECIAL_ADRIA_PASSIVE_TEAM_HELP = 1900000034,
        BUFF_AD_UP = 2000000001,
        BUFF_AD_PERCENT_UP = 2000000002,
        BUFF_AP_UP = 2000000003,
        BUFF_AP_PERCENT_UP = 2000000004,
        BUFF_AP_REDUCE_UP = 2000000007,
        BUFF_AP_REDUCE_PERCENT_UP = 2000000008,
        BUFF_AD_PIERCE_UP = 2000000009,
        BUFF_AD_PIERCE_PERCENT_UP = 2000000010,
        BUFF_AP_PIERCE_UP = 2000000011,
        BUFF_AP_PIERCE_PERCENT_UP = 2000000012,
        BUFF_HP_RECOVERY_UP = 2000000013,
        BUFF_HP_RECOVERY_PERCENT_UP = 2000000014,
        BUFF_MOVESPEED_UP = 2000000015,
        BUFF_MOVESPEED_PERCENT_UP = 2000000016,
        BUFF_DAMAGE_REDUCE_UP = 2000000017,
        BUFF_COOL_DOWN_SPEED_PERCENT_UP = 2000000018,
        BUFF_ATK_SPEED_UP = 2000000019,
        BUFF_SKILL_POWER_UP = 2000000020,
        BUFF_IMMUNE = 2000000021,
        BUFF_NORMAL_ATTACK_SHIELD = 2000000022,
        BUFF_AD_REDUCE_UP = 2000000023,
        BUFF_AD_REDUCE_PERCENT_UP = 2000000024,
        BUFF_AVOID_PROB_PERCENT_UP = 2000000025,
        BUFF_CRIT_UP = 2000000026,
        BUFF_CRIT_PERCENT_UP = 2000000027,
        BUFF_CRI_POWER_UP = 2000000028,
        BUFF_CRI_POWER_PERCENT_UP = 2000000029,
        BUFF_DEF_UP = 2000000030,
        BUFF_DEF_PERCENT_UP = 2000000031,
        BUFF_HIT_UP = 2000000032,
        BUFF_HIT_PERCENT_UP = 2000000033,
        BUFF_RANGE_UP = 2000000034,
        BUFF_BLOCK_UP = 2000000035,
        BUFF_BLOCK_PERCENT_UP = 2000000036,
        BUFF_HOT_UP = 2000000037,
        BUFF_SHIELD_UP = 2000000038,
        DEBUFF_ATK_SPEED_DOWN = 2100000001,
        DEBUFF_COOL_DOWN_SPEED_PERCENT_DOWN = 2100000002,
        DEBUFF_AD_PERCENT_DOWN = 2100000003,
        DEBUFF_FIRE = 2100000004,
        DEBUFF_ICE = 2100000005,
        DEBUFF_SILENCE = 2100000006,
        DEBUFF_AD_DOWN = 2100000007,
        DEBUFF_AIRBORNE = 2100000008,
        DEBUFF_AD_REDUCE_PERCENT_DOWN = 2100000009,
        DEBUFF_HEAL_RATE_DOWN = 2100000010,
        DEBUFF_MISA = 2100000011,
        DEBUFF_FREEZING = 2100000012,
        DEBUFF_SLOW = 2100000013,
        DEBUFF_AP_PERCENT_DOWN = 2100000014,
        DEBUFF_RES_PERCENT_DOWN = 2100000015,
        DEBUFF_DEF_PERCENT_DOWN = 2100000016,
        DEBUFF_ATK_DOWN = 2100000017,
        DEBUFF_DEF_DOWN = 2100000018,
        DEBUFF_CRIT_DOWN = 2100000019,
        DEBUFF_CRI_POWER_DOWN = 2100000020,
        DEBUFF_PIERCE_DOWN = 2100000021,
        DEBUFF_HIT_DOWN = 2100000022,
        DEBUFF_AVOID_DOWN = 2100000023,
        DEBUFF_MOVE_DOWN = 2100000024,
        DEBUFF_BLOCK_DOWN = 2100000025,
        DEBUFF_HP_RECOVERT_DOWN = 2100000026,
        DEBUFF_POISON = 2100000027,
        DEBUFF_BURN = 2100000028,
        DEBUFF_BLEEDING = 2100000029,
        DEBUFF_CHILL = 2100000030,
    }

    public enum GradeType
    {
        UNCOMMON = 0,
        COMMON = 1,
        NORMAL = 2,
        MAGIC = 3,
        RARE = 4,
        EPIC = 5,
        UNIQUE = 6,
        LEGENDARY = 7,
        ANCIENT = 8,
        MYTHIC = 9,
    }

    public enum SynergyType
    {
        NONE = 0,
        NORMAL = 1,
        FIRE = 2,
        WIND = 3,
        LIGHTNING = 4,
        EARTH = 5,
        WATER = 6,
        NOBLESSE = 7,
        TROUBLESHOOTER = 8,
        SUPERNOVA = 9,
        UROBOROS = 10,
        ARCANA = 11,
        ECLIPSE = 12,
    }

    public enum CharacterPositionType
    {
        NONE = 0,
        GUARDIAN = 1,
        TANK = 2,
        WIZARD = 3,
        RANGER = 4,
        ASSASSIN = 5,
        SUPPORTER = 6,
        ESPER = 7,
        SHARPSHOOTER = 8,
        GHOST = 9,
        ORACLE = 10,
        ELECTRIC = 11,
        STRIKER = 12,
    }

    public enum AttackRangeShape
    {
        Rectangle = 1,
        RectangleCut1Edge = 2,
        RectangleCut2Edge = 3,
        RectangleCut3Edge = 4,
        RectangleCut4Edge = 5,
        RectangleCut5Edge = 6,
    }

    public enum DifficultyType
    {
        NORMAL = 1,
        HARD = 2,
        NONE = 3,
    }

    public enum StageType
    {
        BATTLE_NORMAL = 1,
        BATTLE_ELITE = 2,
        BATTLE_BOSS = 3,
        CHEST = 4,
    }

    public enum CharacterType
    {
        NORMAL = 1,
        ELITE = 2,
        BOSS = 3,
        CHARACTER = 4,
        OBSTACLE = 5,
        BATTLEITEM = 6,
        MONSTER = 7,
        SPECIALBOSS = 8,
        NPC = 9,
    }

    public enum ContentType
    {
        STAGE = 1,
        CHAPTER = 2,
        DUNGEON = 3,
        ACINT_LV_EXP = 4,
        STAGE_STAR = 5,
        END_DIALOGUE = 6,
        ACCOUNT_LV_EXP = 7,
        GACHA = 8,
        TUTORIAL_START = 9,
    }

    public enum TutorialEventType
    {
        SHOW_DIALOGUE = 1,
        OPEN_MENU = 2,
        HIGHLIGHT_BUTTON = 3,
    }

    public enum DirectionType
    {
        UP = 1,
        DOWN = 2,
        LEFT = 3,
        RIGHT = 4,
    }

    public enum FrequencyType
    {
        ONCE = 1,
        REPEAT = 2,
    }

    public enum ConfigValueType
    {
        STRING = 0,
        INT = 1,
        FLOAT = 2,
    }

    public enum AtkType
    {
        AD = 1,
        AP = 2,
        ALL = 3,
        NONE = 4,
    }

    public enum SkillValueType
    {
        PERCENT = 1,
        TIME = 2,
        COOL = 3,
        INT = 4,
        NONE = 5,
    }

    public enum SkillType
    {
        NONE = 1,
        NORMAL = 2,
        WEAPON = 3,
        PASSIVE = 4,
        ACTIVE = 5,
    }

    public enum QuotesType
    {
        GET_CHARACTER = 1,
        INFORMATION = 2,
        VICTORY = 3,
        USE_SKILL = 4,
        LEVEL_UP = 5,
    }

    public enum QuotesPlayType
    {
        ONLY = 1,
        RANDOM = 2,
    }

    public enum GuideMissionType
    {
        NONE = 0,
        CLEAR_STAGE = 1,
        ENTER_CHAPTER = 2,
        SUMMON_CHARACTER = 3,
        LEVELUP_CHARACTER_TARGET = 4,
        EXCEED_CHARACTER_TARGET = 5,
        TRANSCENDENCE_CHARACTER_TARGET = 6,
        USE_BUILDING = 7,
        UPGRADE_BUILDING = 8,
        INSTALL_BUILDING = 9,
        UPGRADE_DIMENSION_CUBE_CORE_RESEARCH = 10,
        CLEAR_BABEL = 11,
    }

    public enum DialogueEventType
    {
        STAGE_CLEAR = 1,
        POPUP_OPEN = 2,
        FIRST_IN = 3,
        STAGE_START = 4,
        GUIDE_START = 5,
        FAIL = 6,
        PROLOGUE = 7,
    }

    public enum InGameVfxNameType
    {
        NONE = 1,
        Skill_401011 = 2,
        Skill_401011_1 = 3,
        fx_common_buff_atkup_01 = 4,
        fx_common_buff_atkup_02 = 5,
        fx_common_buff_ctdown_01 = 6,
        fx_common_buff_ctdown_02 = 7,
        fx_common_buff_heal = 8,
        fx_common_buff_shield_01 = 9,
        fx_common_buff_shield_02 = 10,
        fx_common_buff_spdup_01 = 11,
        fx_common_buff_spdup_02 = 12,
        fx_common_area_darkness = 13,
        fx_common_area_earth = 14,
        fx_common_area_fire = 15,
        fx_common_area_light = 16,
        fx_common_area_water = 17,
        Skill_404021 = 18,
        Skill_404021_1 = 19,
        Skill_404021_2 = 20,
        Skill_404021_3 = 21,
        Skill_302011 = 22,
        Skill_306011 = 23,
        Skill_306011_1 = 24,
        fx_common_hit_01 = 25,
        fx_common_skill_hit_01 = 26,
        Skill_304021 = 27,
        fx_common_debuff_atkdown_01 = 28,
        fx_common_debuff_atkdown_02 = 29,
        Skill_401031 = 30,
        fx_common_summon_awful = 31,
        fx_common_summon_enemy = 32,
        Skill_101011 = 33,
        Skill_102011 = 34,
        Skill_303011 = 35,
        Skill_403011 = 36,
        Skill_406011 = 37,
        Skill_405021 = 38,
        Skill_305011 = 39,
        fx_common_cast_darkness = 40,
        fx_common_cast_earth = 41,
        fx_common_cast_fire = 42,
        fx_common_cast_light = 43,
        fx_common_cast_water = 44,
        fx_common_assassin_awful = 45,
        fx_common_assassin_enemy = 46,
        Projectile_303011 = 47,
        Projectile_403011 = 48,
        Projectile_406011 = 49,
        Projectile_404021 = 50,
        Projectile_304021 = 51,
        Projectile_306011 = 52,
        Skill_403011_1 = 53,
        fx_common_hit_02 = 54,
        fx_common_debuff_stun = 55,
        Projectile_104011 = 61,
        Projectile_104021 = 62,
        Projectile_203011 = 63,
        Projectile_204011 = 64,
        fx_common_trap_hold_01 = 65,
        fx_common_trap_hold_02 = 66,
        Skill_101031 = 67,
        Skill_103011 = 69,
        Skill_104011 = 70,
        Skill_104011_1 = 71,
        Skill_104021 = 72,
        Skill_106011 = 73,
        Skill_202011 = 74,
        Skill_202021 = 75,
        Skill_203011 = 76,
        Skill_204011 = 77,
        Skill_205011 = 78,
        fx_common_chapter1 = 79,
        fx_common_commander_skill_01 = 80,
        Skill_102021 = 81,
        fx_common_trap_fire = 83,
        fx_common_trap_ice_01 = 84,
        fx_common_trap_ice_02 = 85,
        Skill_101021 = 86,
        Skill_104021_1 = 87,
        fx_common_synergy_water = 88,
        fx_common_synergy_fire = 89,
        fx_common_synergy_darkness = 90,
        Skill_102031 = 91,
        Skill_201011 = 92,
        Skill_202031 = 93,
        fx_common_area_landing = 94,
        fx_common_debuff_silence = 95,
        fx_common_hit_03 = 96,
        fx_common_bufftrap_ad = 97,
        fx_common_bufftrap_ap = 98,
        fx_common_bufftrap_defense = 99,
        fx_common_synergy_light = 100,
        fx_common_synergy_ground = 101,
        fx_common_synergy_wind = 102,
        fx_common_commander_skill_03 = 103,
        fx_common_commander_skill_04 = 104,
        fx_common_commander_skill_05 = 105,
        fx_common_commander_skill_06_01 = 106,
        fx_common_commander_skill_06_02 = 107,
        Projectile_104031 = 108,
        Projectile_204051 = 111,
        fx_common_buff_apup = 112,
        fx_common_buff_apup_01 = 113,
        fx_common_buff_dfup = 114,
        fx_common_buff_dfup_01 = 115,
        fx_common_debuff_dfdown = 116,
        fx_common_debuff_dfdown_01 = 117,
        fx_common_debuff_healdown = 118,
        fx_common_debuff_healdown_01 = 119,
        fx_common_buff_provoke = 120,
        fx_common_buff_provoke_01 = 121,
        fx_common_buff_apdfup_01 = 122,
        fx_common_buff_apdfup_02 = 123,
        fx_common_buff_immune_01 = 124,
        fx_common_buff_immune_02 = 125,
        Skill_101041 = 126,
        Skill_101051 = 127,
        Skill_101061 = 128,
        Skill_201031 = 129,
        Skill_201031_1 = 130,
        Skill_201031_2 = 131,
        Skill_201031_3 = 132,
        Skill_102041 = 133,
        Skill_102051 = 134,
        Skill_102061 = 135,
        Skill_103021 = 136,
        Skill_103031 = 137,
        Skill_103041 = 138,
        Skill_104031 = 139,
        Skill_104061 = 140,
        Skill_104071 = 141,
        Skill_104081 = 142,
        Skill_105011 = 143,
        Skill_105021 = 144,
        Skill_105031 = 145,
        Skill_106021 = 146,
        Skill_106031 = 147,
        Skill_106041 = 148,
        Skill_203021 = 149,
        Skill_202051 = 150,
        Skill_202051_1 = 151,
        Skill_202061 = 152,
        Skill_202071 = 153,
        Skill_202081 = 154,
        Skill_202091 = 155,
        Skill_401021 = 156,
        Skill_302021 = 157,
        Skill_402011 = 158,
        Skill_402021 = 159,
        Skill_403021 = 160,
        Skill_404011 = 161,
        Skill_404031 = 162,
        Skill_204031 = 163,
        Skill_204032 = 164,
        Skill_204033 = 165,
        Skill_204041 = 166,
        Skill_204042 = 167,
        Skill_204043 = 168,
        Skill_204051 = 169,
        Skill_204052 = 170,
        Skill_204053 = 171,
        Skill_405011 = 172,
        Skill_406021 = 173,
        Skill_406031 = 174,
        fx_common_cast_wind = 175,
        fx_common_area_wind = 176,
        Skill_401021_1 = 177,
        Skill_406021_1 = 178,
        Skill_404031_1 = 179,
        fx_common_trap_airborne = 180,
        Skill_405011_1 = 181,
        TargetLineRenderer = 182,
        Skill_402011_1 = 183,
        fx_common_debuff_misa_01 = 184,
        fx_common_debuff_misa_02 = 185,
        DropFx = 186,
        Skill_202061_1 = 187,
        fx_common_commander_skill_02 = 188,
        fx_common_synergy_lightning_01 = 189,
        fx_common_trap_explosion = 190,
        fx_common_buff_normal_attack_shield_01 = 191,
        fx_common_buff_normal_attack_shield_02 = 192,
        fx_prologue_boss_prepare_01 = 193,
        fx_prologue_boss_prepare_02 = 194,
        fx_common_commander_skill_300 = 195,
        fx_common_synergy_lightning_02 = 196,
        fx_common_synergy_lightning_03 = 197,
        fx_common_cast_supernova_02 = 198,
        fx_common_synergy_fire_02 = 199,
        fx_common_synergy_fire_03 = 200,
        fx_common_synergy_ground_02 = 201,
        fx_common_synergy_ground_03 = 202,
        fx_common_synergy_water_02 = 203,
        fx_common_synergy_water_03 = 204,
        fx_common_synergy_wind_02 = 205,
        fx_common_synergy_wind_03 = 206,
        fx_common_job_espar_01 = 207,
        fx_common_supply_chocobar = 208,
        fx_common_supply_vitamin = 209,
        fx_common_supply_emp_bomb = 210,
        fx_common_supply_energy_drink = 211,
        fx_common_supply_emergency_armor = 212,
        fx_common_emp_bomb = 213,
        fx_troubleshooter_drop_bomb = 214,
        fx_common_job_guardian_01 = 215,
        fx_common_job_sharpshooter_01 = 216,
        fx_common_job_sharpshooter_02 = 217,
        fx_common_job_striker_01 = 218,
        fx_common_asterism_troubleshooter_01 = 219,
        fx_common_asterism_ts_bomb_01 = 220,
        fx_common_asterism_ts_bomb_02 = 221,
        fx_common_asterism_ts_chocolate_01 = 222,
        fx_common_asterism_ts_ctdown_01 = 223,
        fx_common_asterism_ts_emp_01 = 224,
        fx_common_asterism_ts_shield_01 = 225,
        fx_common_asterism_ts_stimpack_01 = 226,
        Skill_17553404 = 227,
        Skill_17563405 = 228,
        Skill_17663506 = 229,
        Skill_406011_wave = 230,
        fx_common_asterism_nb_shield_01 = 231,
        fx_common_asterism_sn_aura_01 = 232,
        fx_common_asterism_sn_aura_02 = 233,
        fx_common_asterism_sn_aura_03 = 234,
        Skill_401031_1 = 235,
        Skill_401031_2 = 236,
        fx_common_asterism_ts_jet_01 = 237,
        fx_common_debuff_marie_aracne = 239,
        Skill_Passive_17663506 = 240,
        Skill_Passive_401011 = 241,
        fx_common_job_striker_02 = 242,
        fx_common_debuff_spddown_01 = 243,
        fx_common_debuff_spddown_02 = 244,
        fx_common_debuff_ctup_01 = 245,
        fx_common_debuff_ctup_02 = 246,
        Projectile_103011 = 247,
        fx_common_asterism_ts_missile_01 = 248,
        Skill_9002_1 = 249,
        Skill_9002_2 = 250,
        Skill_80109002 = 251,
        Skill_7001 = 252,
        Skill_7002 = 253,
        Projectile_9002 = 254,
        Skill_7002_1 = 255,
        Skill_80109002_1 = 256,
        Skill_80109002_2 = 257,
        Skill_304021_1 = 258,
        Skill_304021_2 = 259,
        Skill_9002_3 = 260,
        fx_common_prologue_shield_01 = 261,
        Skill_401011_Prologue_1 = 262,
        Skill_401011_1_Prologue_1 = 263,
        Skill_9002_4 = 264,
        Skill_401011_Prologue_2 = 265,
        Skill_401011_1_Prologue_2 = 266,
        fx_common_prologue_artesia_charge = 267,
        fx_common_asterism_nb_crown_01 = 268,
        fx_common_supply_varient = 269,
        Projectile_17553404 = 270,
        fx_common_asterism_sn_item_01 = 271,
        fx_common_asterism_sn_get_01 = 272,
        Skill_17663506_1 = 273,
        Skill_Passive_17663506_1 = 274,
        fx_common_asterism_nb_Icon_01 = 275,
        fx_common_asterism_ts_Icon_01 = 276,
        fx_common_asterism_sn_Icon_01 = 277,
        fx_common_area_position = 278,
    }

    public enum GlobalEffectProviderType
    {
        EQIUP = 1,
        MONSTER_MULTIPLE = 99,
    }

    public enum TermType
    {
        NONE = 0,
        DAILY = 1,
        WEEKLY = 3,
    }

    public enum QuestType
    {
        CLEAR_DAILY_QUEST = 1,
        CLEAR_WEEKLY_QUEST = 2,
        CLEAR_STAGE = 3,
        LEVELUP_CHARACTER = 4,
        SUMMON_CHARACTER = 5,
        BATTLE_PVP = 6,
        GET_IDLE_REWARD = 7,
        BABEL_CLEAR = 8,
    }

    public enum EventType
    {
        ATTENDANCE = 1,
        ACC_PLAY_TIME = 2,
        USE_AP = 3,
        USE_GOLD = 4,
    }

    public enum DungeonType
    {
        PURGE = 1,
        TRIAL = 2,
    }

    public enum TrialType
    {
        BATTLE_NORMAL = 0,
        BRONZE = 1,
        SILVER = 2,
        GOLD = 3,
        PLATINUM = 4,
        DIAMOND = 5,
    }

    public enum CalcUnit
    {
        Numeric = 0,
        Percentage = 1,
    }

    public enum RankingType
    {
        SCORE = 1,
        RATE = 2,
        NUMBER = 3,
    }

    public enum PvpRewardType
    {
        PVP_REWARD_TIER_UP = 1,
        PVP_REWARD_DAILY = 2,
        PVP_REWARD_SEASON = 3,
        PVP_REWARD_VICTORY = 4,
        PVP_REWARD_LOSE = 5,
    }

    public enum InGameType
    {
        STAGE = 1,
        TRIAL = 2,
        PVP = 3,
        PVP_DEFENSE = 4,
        TRIAL_BOSS = 5,
        PROLOGUE = 6,
        TEST = 7,
    }

    public enum UserGradeType
    {
        BRONZE = 1,
        SILVER = 2,
        GOLD = 3,
        PLATINUM = 4,
        DIAMOND = 5,
    }

    public enum PVPTierType
    {
        BRONZE = 1,
        SILVER = 2,
        GOLD = 3,
        PLATINUM = 4,
        DIAMOND = 5,
    }

    public enum ObstacleType
    {
        WALL = 1,
        NEUTRAL_WALL = 2,
        EFFECT_CODE = 3,
        SHELTER = 4,
        TRAP = 5,
        NONEFIX = 6,
        BUFFZONE = 7,
        DEBUFFZONE = 8,
    }

    public enum ObstacleUseType
    {
        OBSTRUCTION = 1,
        PROTECTION = 2,
        DISPOSABLE = 3,
        RENEWAL = 4,
        PERMANENT = 5,
    }

    public enum ObstacleLocationType
    {
        NONE = 0,
        ALLIANCE = 1,
    }

    public enum OpenConditionType
    {
        TRIAL_DUNGEON = 1,
        PVP = 2,
        QUEST = 3,
        SESSION_TIME = 4,
        ATTENDANCE = 5,
        AP_USE = 6,
        SUMMON = 7,
    }

    public enum ItemCategoryType
    {
        CURRENCY = 1,
        CHARACTER = 2,
        ETC = 3,
    }

    public enum PromotionLevelType
    {
        PROMOTION_DEFAULT = 1,
        PROMOTION_SPECIAL_1 = 2,
        PROMOTION_SPECIAL_2 = 3,
        PROMOTION_SPECIAL_3 = 4,
        PROMOTION_SPECIAL_4 = 5,
    }

    public enum CommanderRangeShapeType
    {
        SHAPE_PLUS = 1,
        SHAPE_SINGLE = 2,
        SHAPE_SQUARE = 3,
        SHAPE_GARO = 4,
        SHAPE_SERO = 5,
    }

    public enum CommanderTargetType
    {
        TARGET_PLAYER = 1,
        TARGET_ENEMY = 2,
        TARGET_ALL = 3,
    }

    public enum PriceType
    {
        ITEM = 0,
        CASH = 1,
    }

    public enum ShopMainGroupType
    {
        NONE = 0,
        SHOP_MAIN = 1,
        BANNER = 2,
    }

    public enum ShopSubGroupType
    {
        NONE = 0,
        COMMON = 1,
        PACKAGE = 2,
    }

    public enum ShopTermType
    {
        NONE = 0,
        PERIOD = 1,
        TIME = 2,
        PERIOD_TIME = 3,
    }

    public enum ShopBannerConditionType
    {
        NONE = 0,
        FIRST_STAGE_LOSE = 1,
        STAGE_CLEAR = 2,
        FIRST_DUNGEON_LOSE = 3,
        DUNGEON_CLEAR = 4,
        FIRST_PVP_LOSE = 5,
        ENTER_SHOP_POP = 6,
        ENTER_GACHA_POP = 7,
    }

    public enum ShopBannerShowType
    {
        NONE = 0,
        IMMEDIATE = 1,
        LOBBY = 2,
    }

    public enum GachaType
    {
        NONE = 0,
        COMMON_CHARACTER = 1,
        COMMON_WEAPON = 2,
        PICK_UP_CHARACTER = 3,
    }

    public enum GachaTermType
    {
        NONE = 0,
        PERIOD = 1,
    }

    public enum DialogueAnimationType
    {
        NONE = 0,
        SCALE_UP = 1,
        SCALE_DOWN = 2,
        CURVE_ANIMATION = 3,
        MASK = 4,
    }

    public enum DialogueSceneType
    {
        Chapter = 0,
    }

    public enum DialogueEventGroup
    {
        None = 0,
        Choice = 1,
        Character = 2,
    }

    public enum DialogTransitionType
    {
        Dissolve = 0,
        Crossfade = 1,
        Slide = 2,
    }

    public enum DialogueEffectType
    {
        None = 0,
        Shake = 1,
    }

    public enum SynergyCoverType
    {
        NONE = 0,
        SQUAD_ALL = 1,
        SQUAD_STELLA = 2,
        KNIGHT_ALL = 3,
        SYNERGY_ELEMENTAL = 4,
        SYNERGY_STELLA = 5,
        SQUAD_ONCE = 6,
    }

    public enum AttackerType
    {
        NONE = 0,
        CHARCTER = 1,
        COMMANDER_SKILL = 2,
        CHAPTER_RULE = 3,
        SYNERGY_STAR_ASTERISM = 4,
    }

    public enum BenefitType
    {
        NONE = 0,
        BUILDING = 1,
        MULTI_BUILDING = 2,
        MAX_LEVEL_UP = 3,
        AREA_EXPAND = 4,
    }

    public enum BuildType
    {
        NONE = 0,
        ONLYONE = 1,
        MULTIPLE = 2,
    }

    public enum DimensionType
    {
        NONE = 0,
        KNIGHT = 1,
        ELEMENTAL = 2,
        STELLA = 3,
    }

    public enum ImmuneType
    {
        NONE = 0,
        NORMAL = 1,
        ELETE = 2,
        BOSS = 3,
        SPECIAL = 4,
        SCARECROW = 5,
    }

    public enum TutorialTriggerType
    {
        NONE = 0,
        CHARACTER_DEAD = 1,
        CHARACTER_EXCEED = 2,
        CHARACTER_PLACEMENT = 3,
        CHARACTER_TRANSCENDENCE = 4,
        COMMANDER_SKILL_ACTIVE = 5,
        COMMANDER_SKILL_READY = 6,
        GAME_START = 7,
        SHOW_POP_COMPLETE = 8,
        START_STAGE = 9,
        START_TUTORIAL = 10,
        SKILL_READY = 11,
        SET_LV_CHARACTER_TARGET = 12,
        ENEMY_DEAD_ALL = 13,
        DIALOGUE_POP_END = 14,
        CLOSE_POP_COMPLETE = 15,
        COMEBACK_HUBBLE = 16,
        BUILDING_COMPLETE = 17,
        DIMENSION_UPGRADE_COMPLETE = 18,
        ENTER_ELPIS = 19,
        HUBBLE_EXPANSION_COMPLETE = 20,
        IDLE_REWARD_CLAIM = 21,
        MOVE_OBJECT_AFTER = 22,
        COMBAT_START = 23,
        STAY_DEFAULT_LOBBY = 24,
        GUIDE_START = 25,
        LAYER_ENTER = 26,
        BATTLE_READY = 27,
        SELECT_BUILD = 28,
        FOCUS_OBJECT = 29,
        COMBAT_END = 30,
        PREPARATION_START = 31,
        SHOP_PURCHASE = 32,
        UNIT_PLACED = 33,
        SYNERGY_ACTIVATED = 34,
    }

    public enum TutorialActionType
    {
        NONE = 0,
        FOCUS_UI = 1,
        CHARACTER_PLACEMENT_UI = 2,
        FORCED_TOUCH_UI = 3,
        SHOW_DIALOGUE_POP = 4,
        FORCED_TOUCH_BUILD = 5,
        FOCUS_OBJECT = 6,
        MOVE_OBJECT = 7,
        TOAST_MESSAGE = 8,
        SPAWN_ENEMY = 9,
        SHOW_DIALOGUE_POP_CALLBACK = 10,
        FORCED_TOUCH_BUILD_UI = 11,
        FOCUS_MULTIPLE_OBJECTS = 12,
        FORCED_TOUCH_LEVELUP_10 = 13,
    }

    public enum FacilityType
    {
        NONE = 0,
        COMMAND_CENTER = 1,
        NEST = 2,
        DIMENSION_LAB = 3,
        SIMULATION_CENTER = 4,
    }

    public enum CoreResearchType
    {
        NONE = 0,
        KnightAttack = 1,
        KnightDefense = 2,
        KnightHealth = 3,
        Fire = 4,
        Wind = 5,
        Earth = 6,
        Lightning = 7,
        Water = 8,
        Noblesse = 9,
        Supernova = 10,
        Troubleshooter = 11,
        Vigilante = 12,
        Arcana = 13,
        Eclipse = 14,
    }

    public enum MaterialType
    {
        NONE = 0,
        CHARACTER = 1,
        CHARACTER_PIECE = 2,
        CHAR_USER_EXCEED = 3,
        KNIGHT_PIECE = 4,
    }

    public enum NaninovelTriggerType
    {
        NONE = 0,
        NANINOVEL_END = 1,
        STAGE_CLEAR_NANI = 2,
        CHAPTER_CLEAR = 3,
        GUIDE_TUTORIAL_COMPLETE = 4,
        PROLOGUE_END = 5,
        STAGE_START = 6,
        SPECIAL = 7,
        STAGE_ENTER_NANI = 8,
        ENTER_CHAPTER_NANI = 9,
        ENTER_ELPIS_NANI = 10,
        SCENE_ENTER = 11,
    }

    public enum EnhanceType
    {
        NONE = 0,
        ATK = 1,
        DEF = 2,
        HP = 3,
    }

    public enum GuidePopupType
    {
        NONE = 0,
        PREBATTLE_SCENE = 1,
    }
}
