// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using System.Linq;
using System.Security.Cryptography;
using System.Text;
using CookApps.SpecData.Hive.Generator;

namespace CookApps.AutoBattler
{
    [GeneratorSpecDataResource]
    public partial class SpecDataResourceLoader
    {
        private static readonly byte[] _key = {41, 120, 96, 104, 53, 82, 76, 85, 102, 72, 44, 85, 94, 87, 76, 124};
    }
}
