// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using CookApps.SpecData.Generator;

namespace CookApps.AutoBattler
{

    [GeneratorSpecData]
    public partial class SpecOption
    {
        [GeneratorId(nameof(name), typeof(string))]
        public string name;
        public string value;
    }

    [GeneratorSpecData]
    public partial class SpecChest
    {
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        public CookApps.Obfuscator.ObfuscatorInt chest_id;
        public global::CookApps.AutoBattler.ItemType type;
        public CookApps.Obfuscator.ObfuscatorInt key;
        public CookApps.Obfuscator.ObfuscatorInt value;
        public CookApps.Obfuscator.ObfuscatorDouble rate;
    }

    [GeneratorSpecData]
    public partial class TestSpecCharacter
    {
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// ?
        public CookApps.Obfuscator.ObfuscatorInt seq;
        public CookApps.Obfuscator.ObfuscatorInt prefab_id;
        public CookApps.Obfuscator.ObfuscatorInt chapter;
        public string nickname_token;
        public string name_token;
        public string desc_token;
        public global::CookApps.AutoBattler.GradeType grade;
        public CookApps.Obfuscator.ObfuscatorInt need_piece;
        /// ?
        public global::CookApps.AutoBattler.ElementType type;
        /// ?
        public global::CookApps.AutoBattler.CharacterPositionType position;
        public CookApps.Obfuscator.ObfuscatorInt init_star;
        public CookApps.Obfuscator.ObfuscatorInt max_star;
        public CookApps.Obfuscator.ObfuscatorInt stat_hp;
        /// 공격 계산식 & 레벨업 스텟 계산식?
        public CookApps.Obfuscator.ObfuscatorInt stat_atk;
        public CookApps.Obfuscator.ObfuscatorInt stat_def;
        /// 관통?
        public CookApps.Obfuscator.ObfuscatorInt stat_atk_pierce;
        public CookApps.Obfuscator.ObfuscatorFloat inc_rate;
        public CookApps.Obfuscator.ObfuscatorFloat inc_star;
        public CookApps.Obfuscator.ObfuscatorFloat crit_power;
        public CookApps.Obfuscator.ObfuscatorFloat crit_rate;
        public CookApps.Obfuscator.ObfuscatorDouble base_inc;
        public CookApps.Obfuscator.ObfuscatorFloat atkSpd;
        public CookApps.Obfuscator.ObfuscatorInt atkRange;
        public global::CookApps.AutoBattler.AttackRangeShape atkRangeShape;
        public CookApps.Obfuscator.ObfuscatorInt[] skill_ids;
        public CookApps.Obfuscator.ObfuscatorInt equipment_id;
        public CookApps.Obfuscator.ObfuscatorInt[] upgrade_skill_ids;
        public CookApps.Obfuscator.ObfuscatorFloat scale;
    }

    [GeneratorSpecData]
    public partial class SpecCommanderSkill
    {
        /// 유니크 id
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 지휘자 스킬 id
        public CookApps.Obfuscator.ObfuscatorInt commander_skill_id;
        /// 개방 챕터 id
        public CookApps.Obfuscator.ObfuscatorInt open_key_chapter_id;
        /// 지휘자 스킬 이름 토큰
        public string name_token;
        /// 지휘자 스킬 설명 토큰
        public string desc_token;
        /// 스킬 벨류 타입
        public global::CookApps.AutoBattler.SkillValueType skill_value_type;
        /// 실제 계수
        public CookApps.Obfuscator.ObfuscatorFloat base_rate;
    }

    [GeneratorSpecData]
    public partial class SpecAccountLevelExp
    {
        /// 유니크 id
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 계정 레벨
        public CookApps.Obfuscator.ObfuscatorInt lv;
        /// 시작 경험치
        public CookApps.Obfuscator.ObfuscatorInt exp_start;
        /// 마지막 경험치
        public CookApps.Obfuscator.ObfuscatorInt exp_last;
        /// 레벨 당 필요 경험치
        public CookApps.Obfuscator.ObfuscatorInt exp_need;
        /// 행동력 보유 가능 최대량
        public CookApps.Obfuscator.ObfuscatorInt ap_max;
        /// 리워드 id
        public CookApps.Obfuscator.ObfuscatorInt reward_id;
        /// 캐릭터 배치 가능 수
        public CookApps.Obfuscator.ObfuscatorInt squad_count;
    }

    [GeneratorSpecData]
    public partial class SpecChapter
    {
        /// ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 챕터 ID
        public CookApps.Obfuscator.ObfuscatorInt chapter_id;
        /// 보여지는 챕터 번호
        public CookApps.Obfuscator.ObfuscatorInt display_number;
        /// 난이도
        public global::CookApps.AutoBattler.DifficultyType difficulty_type;
        /// 챕터 타이틀 토큰
        public string name_token;
        /// 챕터 세부 설명 토큰
        public string desc_token;
        /// 클리어 보상 id
        public CookApps.Obfuscator.ObfuscatorInt reward_id;
        /// 진입 일러스트 ID
        public string clear_pack_bg_image;
        /// 클리어 패키지 이미지 ID
        public string clear_pack_char_image;
    }

    [GeneratorSpecData]
    public partial class SpecCharacter
    {
        /// 유니크ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 캐릭터_id
        public CookApps.Obfuscator.ObfuscatorInt character_id;
        /// 프리팹id
        public CookApps.Obfuscator.ObfuscatorInt prefab_id;
        /// 캐릭터 등급
        public global::CookApps.AutoBattler.GradeType grade_type;
        /// 전체 리스트 출력 순서
        public CookApps.Obfuscator.ObfuscatorInt seq;
        /// 캐릭터 이름 토큰
        public string name_token;
        /// 캐릭터 설명 토큰
        public string desc_token;
        /// 해금 필요 조각
        public CookApps.Obfuscator.ObfuscatorInt need_piece;
        /// 개체 타입
        public global::CookApps.AutoBattler.CharacterType character_type;
        /// 속성 시너지
        public global::CookApps.AutoBattler.ElementType element_type;
        /// 포지션 시너지
        public global::CookApps.AutoBattler.CharacterPositionType character_position_type;
        /// 사이즈
        public CookApps.Obfuscator.ObfuscatorInt size;
        /// 태생 등급
        public CookApps.Obfuscator.ObfuscatorInt init_star;
        /// 최대 등급
        public CookApps.Obfuscator.ObfuscatorInt max_star;
        /// 초월 성장 비율
        public CookApps.Obfuscator.ObfuscatorFloat inc_trancendence;
        /// 체력
        public CookApps.Obfuscator.ObfuscatorInt stat_hp;
        /// 공격력
        public CookApps.Obfuscator.ObfuscatorInt stat_atk;
        /// 체력, 공격력 1레벨 당 성장율
        public CookApps.Obfuscator.ObfuscatorFloat inc_lv_rate;
        /// 체력, 공격력 10레벨 당 성장율
        public CookApps.Obfuscator.ObfuscatorFloat inc_lv_bonus_rate;
        /// 물리 방어력
        public CookApps.Obfuscator.ObfuscatorInt stat_def;
        /// 마법 방어력
        public CookApps.Obfuscator.ObfuscatorInt stat_res;
        /// 물리 관통력
        public CookApps.Obfuscator.ObfuscatorFloat stat_atk_pierce;
        /// 마법 관통력
        public CookApps.Obfuscator.ObfuscatorFloat stat_res_pierce;
        /// 치명률
        public CookApps.Obfuscator.ObfuscatorFloat crit_rate;
        /// 치명타 피해량
        public CookApps.Obfuscator.ObfuscatorFloat crit_power;
        /// 공격 속도
        public CookApps.Obfuscator.ObfuscatorFloat atk_speed;
        /// 이동 속도
        public CookApps.Obfuscator.ObfuscatorFloat move_speed;
        /// 공격 범위
        public CookApps.Obfuscator.ObfuscatorInt atk_range;
        /// 높이
        public CookApps.Obfuscator.ObfuscatorFloat height;
        /// 넉백 가능 여부
        public bool is_knock_back;
        /// 공격 범위 형태
        public global::CookApps.AutoBattler.InGameVfxNameType projectile_vfx_name_type;
        /// 일반 스킬 id
        public CookApps.Obfuscator.ObfuscatorInt[] skill_ids;
        /// 전용 장비 id
        public CookApps.Obfuscator.ObfuscatorInt equipment_id;
        /// 전용 스킬 id
        public CookApps.Obfuscator.ObfuscatorInt upgrade_skill_ids;
        /// 가챠 확률
        public CookApps.Obfuscator.ObfuscatorFloat weight;
    }

    [GeneratorSpecData]
    public partial class SpecCharacterLevelExp
    {
        /// 유니크 ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 캐릭터 레벨
        public CookApps.Obfuscator.ObfuscatorInt level;
        /// 기본 레벨업 필요 아이템
        public global::CookApps.AutoBattler.ItemType base_levelup_item_type;
        /// 경험치 필요량
        public CookApps.Obfuscator.ObfuscatorInt base_levelup_item_count;
        /// 경험치 아이템 누적 필요량
        public CookApps.Obfuscator.ObfuscatorInt base_levelup_item_sum;
        /// 골드 필요량
        public CookApps.Obfuscator.ObfuscatorInt need_gold;
        /// 골드 누적 필요량
        public CookApps.Obfuscator.ObfuscatorInt need_gold_sum;
        /// 2차 레벨업 필요 아이템
        public global::CookApps.AutoBattler.ItemType sec_levelup_item_type;
        /// 2차 재화 필요량
        public CookApps.Obfuscator.ObfuscatorInt sec_levelup_item_count;
        /// 2차 재화 누적 필요량
        public CookApps.Obfuscator.ObfuscatorInt sec_levelup_item_sum;
        /// 초월 가능 여부
        public bool is_transcendence;
    }

    [GeneratorSpecData]
    public partial class SpecCharacterTranscendence
    {
        /// 유니크 ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 시너지 종류
        public global::CookApps.AutoBattler.ElementType element_type;
        /// 캐릭터 등급
        public global::CookApps.AutoBattler.GradeType grade_type;
        /// 캐릭터 초월 레벨
        public CookApps.Obfuscator.ObfuscatorInt transcendence_lv;
        /// 캐릭터 맥스 레벨
        public CookApps.Obfuscator.ObfuscatorInt max_lv;
        /// 캐릭터 초월 아이템 필요 종류
        public global::CookApps.AutoBattler.ItemType item_type;
        /// 캐릭터 초월 아이템 필요량
        public CookApps.Obfuscator.ObfuscatorInt char_transcendence_count;
        /// 캐릭터 초월 아이템 누적 필요량
        public CookApps.Obfuscator.ObfuscatorInt char_transcendence_item_sum;
    }

    [GeneratorSpecData]
    public partial class SpecCharacterEnhance
    {
        /// 유니크id
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 캐릭터 등급
        public global::CookApps.AutoBattler.GradeType grade_type;
        /// 태생 별 개수
        public CookApps.Obfuscator.ObfuscatorInt star;
        /// 조각 필요량
        public CookApps.Obfuscator.ObfuscatorInt piece;
        /// 최대 레벨
        public CookApps.Obfuscator.ObfuscatorInt max_level;
    }

    [GeneratorSpecData]
    public partial class SpecCharacterQuotes
    {
        /// index
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 유닛 ID
        public CookApps.Obfuscator.ObfuscatorInt prefab_id;
        /// #캐릭터 이름
        public string character_name;
        /// 대사 재생 타입
        public global::CookApps.AutoBattler.QuotesPlayType quotes_play_type;
        /// 대사 타입
        public global::CookApps.AutoBattler.QuotesType quotes_type;
        /// 대사 내용 토큰
        public string dialog_token;
        /// 사운드 토큰
        public string sound_token_kr;
    }

    [GeneratorSpecData]
    public partial class SpecDialogue
    {
        /// 유니크 ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 대화 발생 이벤트 타입
        public global::CookApps.AutoBattler.DialogueEventType dialogue_event_type;
        /// 세부 타겟
        public string sub_key_value;
        /// 그룹  ID
        public CookApps.Obfuscator.ObfuscatorInt dialouge_group_id;
        /// 순서
        public CookApps.Obfuscator.ObfuscatorInt order;
        /// 발화자 ID
        public CookApps.Obfuscator.ObfuscatorInt prefab_id;
        /// 발화자 이름 토큰
        public string character_name_token;
        /// 다이얼로그 토큰
        public string text_desc_token;
        /// 다이얼로그 상단 이미지
        public string bg_image;
        /// 이미지 크기
        public CookApps.Obfuscator.ObfuscatorFloat bg_image_scale;
        /// 대화 종료 시 reward_id
        public CookApps.Obfuscator.ObfuscatorInt reward_id;
    }

    [GeneratorSpecData]
    public partial class SpecEvent
    {
        /// ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 이벤트ID
        public CookApps.Obfuscator.ObfuscatorInt event_id;
        /// 이벤트 타입
        public global::CookApps.AutoBattler.EventType event_type;
        /// 기간 타입
        public global::CookApps.AutoBattler.TermType term_type;
        /// 기간 반복 타입
        public global::CookApps.AutoBattler.FrequencyType frequency_type;
        /// 이벤트 시작 시간
        [GeneratorDateTime(nameof(start_at))]
        public string start_at;
        /// 이벤트 종료 시간
        [GeneratorDateTime(nameof(end_at))]
        public string end_at;
        /// 이벤트 이름 토큰
        public string name_token;
        /// 이벤트 설명 토큰
        public string desc_token;
    }

    [GeneratorSpecData]
    public partial class SpecEventCondition
    {
        /// ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 이벤트ID
        public CookApps.Obfuscator.ObfuscatorInt event_id;
        /// 이벤트 컨디션 ID
        public CookApps.Obfuscator.ObfuscatorInt event_condition_id;
        /// 필요 조건 값
        public CookApps.Obfuscator.ObfuscatorInt need_count;
        /// 보상 종류
        public global::CookApps.AutoBattler.ItemType item_type;
        /// 보상 키 값
        public CookApps.Obfuscator.ObfuscatorInt item_key;
        /// 보상 수량
        public CookApps.Obfuscator.ObfuscatorInt item_count;
    }

    [GeneratorSpecData]
    public partial class SpecLanguage
    {
        /// 아이디
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 키 값
        public string token_key;
        /// 값
        public string language_kr;
    }

    [GeneratorSpecData]
    public partial class SpecGameConfig
    {
        /// 아이디
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 키 값
        public string config_key;
        /// 자료형 타입
        public global::CookApps.AutoBattler.ConfigValueType config_value_type;
        /// 값
        public string config_value;
    }

    [GeneratorSpecData]
    public partial class SpecGachaScenario
    {
        /// 유니크 id
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 가챠 누적 횟수
        public CookApps.Obfuscator.ObfuscatorInt gacha_acc_count;
        /// 보상 종류
        public global::CookApps.AutoBattler.ItemType item_type;
        /// 보상 세부 key
        public CookApps.Obfuscator.ObfuscatorInt item_key;
        /// 보상 수량
        public CookApps.Obfuscator.ObfuscatorInt item_count;
    }

    [GeneratorSpecData]
    public partial class SpecGuideMission
    {
        /// 유니크 ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 가이드 순서
        public CookApps.Obfuscator.ObfuscatorInt order;
        /// 가이드 타입
        public global::CookApps.AutoBattler.GuideMissionType guide_mission_type;
        /// 가이드 이름 토큰
        public string name_token;
        /// 가이드 설명 토큰
        public string desc_token;
        /// 출력 다이얼로그 id
        public CookApps.Obfuscator.ObfuscatorInt dialogue;
        /// 타겟 id
        public CookApps.Obfuscator.ObfuscatorInt sub_key;
        /// 필요 행위 횟수
        public CookApps.Obfuscator.ObfuscatorInt need_count;
        /// 보상 종류
        public global::CookApps.AutoBattler.ItemType item_type;
        /// 보상 키 값
        public CookApps.Obfuscator.ObfuscatorInt item_key;
        /// 보상 수량
        public CookApps.Obfuscator.ObfuscatorInt item_count;
    }

    [GeneratorSpecData]
    public partial class SpecQuest
    {
        /// ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 퀘스트ID
        public CookApps.Obfuscator.ObfuscatorInt quest_id;
        /// 반복 기간 타입
        public global::CookApps.AutoBattler.TermType term_type;
        /// 퀘스트 타입
        public global::CookApps.AutoBattler.QuestType quest_type;
        /// 퀘스트 이름 토큰
        public string name_token;
        /// 퀘스트 설명 토큰
        public string desc_token;
        /// 타겟 id
        public CookApps.Obfuscator.ObfuscatorInt sub_key;
        /// 필요 행위 횟수
        public CookApps.Obfuscator.ObfuscatorInt need_count;
        /// 보상 종류
        public global::CookApps.AutoBattler.ItemType item_type;
        /// 보상 키 값
        public CookApps.Obfuscator.ObfuscatorInt item_key;
        /// 보상 수량
        public CookApps.Obfuscator.ObfuscatorInt item_count;
    }

    [GeneratorSpecData]
    public partial class SpecSkill
    {
        /// 유니크 id
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 스킬 id
        public CookApps.Obfuscator.ObfuscatorInt skill_id;
        /// 스킬 타입
        public global::CookApps.AutoBattler.SkillType skill_type;
        /// 캐릭터 ID
        public CookApps.Obfuscator.ObfuscatorInt prefab_id;
        /// 전용 무기 id
        public CookApps.Obfuscator.ObfuscatorInt weapon_id;
        /// #스킬 사용자
        public string character_name;
        /// AP AD 판정 유무
        public global::CookApps.AutoBattler.AtkType atk_type;
        /// 스킬 이름 토큰
        public string skill_name_token;
        /// 스킬 설명 토큰
        public string skill_desc_token;
        /// # 사용 이펙트
        public global::CookApps.AutoBattler.InGameVfxNameType[] skill_vfxs;
        /// #변수 의미
        public global::CookApps.AutoBattler.SkillValueType skill_value_type;
        /// 스킬 계수
        public CookApps.Obfuscator.ObfuscatorFloat base_rate;
    }

    [GeneratorSpecData]
    public partial class SpecStage
    {
        /// 전체 ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 스테이지 ID
        public CookApps.Obfuscator.ObfuscatorInt stage_id;
        /// 난이도
        public global::CookApps.AutoBattler.DifficultyType difficulty_type;
        /// 챕터
        public CookApps.Obfuscator.ObfuscatorInt chapter_id;
        /// 스테이지 번호
        public CookApps.Obfuscator.ObfuscatorInt stage_number;
        /// 다이얼로그 ID
        public CookApps.Obfuscator.ObfuscatorInt dialogue_id;
        /// 스테이지 타입
        public global::CookApps.AutoBattler.StageType stage_type;
        /// 플레이 제한 횟수
        public CookApps.Obfuscator.ObfuscatorInt limit_count;
        /// 행동력
        public CookApps.Obfuscator.ObfuscatorInt need_ap;
        /// 어려움 난이도 행동력
        public CookApps.Obfuscator.ObfuscatorInt ap_HARD;
        /// 클리어 보상 id
        public CookApps.Obfuscator.ObfuscatorInt reward_id;
        /// 장애물
        public CookApps.Obfuscator.ObfuscatorInt[] obstacle_grid_id;
        /// 장애물 id
        public CookApps.Obfuscator.ObfuscatorInt obstacle_id;
        /// 부서지는 장애물
        public CookApps.Obfuscator.ObfuscatorInt[] neutral_grid_id;
        /// 장애물 id
        public CookApps.Obfuscator.ObfuscatorInt neutral_wall_id;
        /// 챕터 룰
        public CookApps.Obfuscator.ObfuscatorInt[] effect_code_rule_tile;
        /// 이펙트 코드
        public global::CookApps.AutoBattler.EffectCodeNameType effect_code_name;
        /// 이텍트 코드 스텟
        public CookApps.Obfuscator.ObfuscatorFloat effect_code_stat;
        /// 챕터 룰2
        public CookApps.Obfuscator.ObfuscatorInt[] effect_code_rule_tile_2;
        /// 이펙트 코드2
        public global::CookApps.AutoBattler.EffectCodeNameType effect_code_name_2;
        /// 이텍트 코드 스텟2
        public CookApps.Obfuscator.ObfuscatorFloat effect_code_stat_2;
        /// 챕터 룰3
        public CookApps.Obfuscator.ObfuscatorInt[] effect_code_rule_tile_3;
        /// 이펙트 코드3
        public global::CookApps.AutoBattler.EffectCodeNameType effect_code_name_3;
        /// 이텍트 코드 스텟3
        public CookApps.Obfuscator.ObfuscatorFloat effect_code_stat_3;
    }

    [GeneratorSpecData]
    public partial class SpecStageMonster
    {
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 챕터 id
        public CookApps.Obfuscator.ObfuscatorInt chapter_id;
        /// 난이도
        public global::CookApps.AutoBattler.DifficultyType difficulty_type;
        /// 스테이지 번호
        public CookApps.Obfuscator.ObfuscatorInt stage_number;
        /// 좌표값 (x,y)
        public string coordinate;
        /// 몬스터 id
        public CookApps.Obfuscator.ObfuscatorInt monster_id;
        /// 몬스터 레벨
        public CookApps.Obfuscator.ObfuscatorInt monster_lv;
        /// 공격력 멀티플
        public CookApps.Obfuscator.ObfuscatorFloat multiple_atk;
        /// 체력 멀티플
        public CookApps.Obfuscator.ObfuscatorFloat multiple_hp;
    }

    [GeneratorSpecData]
    public partial class SpecStageReward
    {
        /// 유니크 id
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 스테이지 난이도
        public global::CookApps.AutoBattler.DifficultyType difficulty_type;
        /// 스테이지 보상 id
        public CookApps.Obfuscator.ObfuscatorInt reward_id;
        /// 보상 확률 유무
        public bool prob_type;
        /// 별 단계 구분
        public CookApps.Obfuscator.ObfuscatorInt star_count;
        /// 보상 획득 빈도
        public global::CookApps.AutoBattler.FrequencyType frequency_type;
        /// 보상 타입
        public global::CookApps.AutoBattler.ItemType item_type;
        /// 보상 키 값
        public CookApps.Obfuscator.ObfuscatorInt item_key;
        /// 보상 수량
        public CookApps.Obfuscator.ObfuscatorInt item_count;
        /// 보상 지급 확률
        public CookApps.Obfuscator.ObfuscatorDouble rate;
    }

    [GeneratorSpecData]
    public partial class SpecDungeonTrial
    {
        /// 전체 ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 던전 타입
        public global::CookApps.AutoBattler.DungeonType dungeon_type;
        /// 던전 id
        public CookApps.Obfuscator.ObfuscatorInt dungeon_id;
        /// 공략 desc 토큰
        public string guide_desc_token;
        /// 스테이지 타입
        public global::CookApps.AutoBattler.TrialType trial_type;
        /// 별 입장 조건
        public CookApps.Obfuscator.ObfuscatorInt need_star;
        /// 어려움 난이도 행동력
        public CookApps.Obfuscator.ObfuscatorInt ap_HARD;
        /// 캐릭터 배치 가능 수
        public CookApps.Obfuscator.ObfuscatorInt squad_count;
        /// 장애물
        public CookApps.Obfuscator.ObfuscatorInt[] obstacle_grid_id;
        /// 챕터 룰
        public CookApps.Obfuscator.ObfuscatorInt[] chapter_rule_tile;
        /// 이펙트 코드
        public global::CookApps.AutoBattler.EffectCodeNameType effect_code_name;
        /// 이텍트 코드 스텟
        public CookApps.Obfuscator.ObfuscatorFloat effect_code_stat;
    }

    [GeneratorSpecData]
    public partial class SpecDungeonMonster
    {
        /// 전체 ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 던전 타입
        public global::CookApps.AutoBattler.DungeonType dungeon_type;
        /// 챕터 id
        public CookApps.Obfuscator.ObfuscatorInt dungeon_id;
        /// 좌표값 (x,y)
        public string coordinate;
        /// 몬스터 id
        public CookApps.Obfuscator.ObfuscatorInt monster_id;
        /// 몬스터 레벨
        public CookApps.Obfuscator.ObfuscatorInt monster_lv;
        /// 공격력 멀티플
        public CookApps.Obfuscator.ObfuscatorFloat multiple_atk;
        /// 체력 멀티플
        public CookApps.Obfuscator.ObfuscatorFloat multiple_hp;
    }

    [GeneratorSpecData]
    public partial class SpecDungeonReward
    {
        /// 유니크 id
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 던전 타입
        public global::CookApps.AutoBattler.DungeonType dungeon_type;
        /// 던전 id
        public CookApps.Obfuscator.ObfuscatorInt dungeon_id;
        /// 보상 타입
        public global::CookApps.AutoBattler.ItemType item_type;
        /// 보상 키 값
        public CookApps.Obfuscator.ObfuscatorInt item_key;
        /// 보상 수량
        public CookApps.Obfuscator.ObfuscatorInt item_count;
    }

    [GeneratorSpecData]
    public partial class SpecSynergy
    {
        /// 유니크 id
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 속성 시너지
        public global::CookApps.AutoBattler.CharacterPositionType character_position_type;
        /// 포지션 시너지
        public global::CookApps.AutoBattler.ElementType element_type;
        /// 시너지 이름 토큰
        public string name_token;
        /// 시너지 효과 설명 토큰
        public string desc_token;
        /// 시너지 단계
        public CookApps.Obfuscator.ObfuscatorInt grade;
        /// 단계 발동 최소 명수 조건
        public CookApps.Obfuscator.ObfuscatorInt min_count;
        /// 단계 발동 최대 명수 조건
        public CookApps.Obfuscator.ObfuscatorInt max_count;
        /// 계수 타입
        public global::CookApps.AutoBattler.SkillValueType skill_value_type;
        /// 계수
        public CookApps.Obfuscator.ObfuscatorFloat stat_value;
    }

    [GeneratorSpecData]
    public partial class SpecTutorial
    {
        /// 유니크 id
        [GeneratorId(nameof(ID), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt ID;
        /// 오픈 컨텐츠 대분류
        public string tuto_group_id;
        /// 다이얼로그 id
        public CookApps.Obfuscator.ObfuscatorInt dialouge_id;
        /// 다이얼로그 출력 위치
        public string dialouge_location;
        /// 다음 유니크 id
        public CookApps.Obfuscator.ObfuscatorInt seq;
        public global::CookApps.AutoBattler.TutorialEventType event_type;
        /// 오픈 콘텐츠 타입
        public string tutorial_open_type;
        /// 오픈 대상 세부 id
        public CookApps.Obfuscator.ObfuscatorInt open_key;
        /// 포커싱 영역
        public string focus_object_name;
        /// 포커싱 영역 너비
        public string focus_object_scale;
        /// 버튼 클릭 영역
        public string focus_btn_name;
        /// 화살표의 방향 (위 아래)
        public global::CookApps.AutoBattler.DirectionType direction_type;
    }

    [GeneratorSpecData]
    public partial class SpecItem
    {
        /// 유니크 ID
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 아이템 타입 이름
        public global::CookApps.AutoBattler.ItemType item_type;
        /// 보상 등급
        public global::CookApps.AutoBattler.GradeType grade_type;
        /// 보상 이름 토큰
        public string name_token;
        /// 보상 설명 토큰
        public string desc_token;
        /// 보상 획득 채널 토큰
        public string desc_token_1;
        /// 인벤토리 표시 유무
        public bool info_show;
        /// 사용 가능 유무
        public bool is_consumable;
        /// 합성 요구량
        public CookApps.Obfuscator.ObfuscatorInt merge_count;
        /// 세부 ID 특정 가능 여부
        public bool is_common;
    }

    [GeneratorSpecData]
    public partial class SpecIdleReward
    {
        /// 유니크 아이디
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 보상 해금 챕터
        public CookApps.Obfuscator.ObfuscatorInt chapter_id;
        /// 리워드 타입
        public global::CookApps.AutoBattler.ItemType item_type;
        /// 기본 지급 갯수
        public CookApps.Obfuscator.ObfuscatorFloat min_count;
        /// 스테이지 클리어 당 방치 보상 추가량
        public CookApps.Obfuscator.ObfuscatorFloat add_count;
        /// 지급 기준 시간 (분)
        public CookApps.Obfuscator.ObfuscatorInt supply_time_m;
    }

    [GeneratorSpecData]
    public partial class SpecInGameVfx
    {
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        public global::CookApps.AutoBattler.InGameVfxNameType vfx_name_type;
        public string addressable_path;
    }

    [GeneratorSpecData]
    public partial class SpecRewardInfo
    {
        /// 유니크 id
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 보상 id
        public CookApps.Obfuscator.ObfuscatorInt reward_id;
        /// 컨텐츠 메인 분류
        public global::CookApps.AutoBattler.ContentType content_type;
        /// 난이도
        public global::CookApps.AutoBattler.DifficultyType difficulty_type;
        /// 컨텐츠 추가 구분 값
        public CookApps.Obfuscator.ObfuscatorInt content_key_value;
        /// 보상 타입_소분류
        public CookApps.Obfuscator.ObfuscatorInt sub_value;
        /// 보상 타입
        public global::CookApps.AutoBattler.ItemType item_type;
        /// 보상 키 값
        public CookApps.Obfuscator.ObfuscatorInt item_key;
        /// 보상 수량
        public CookApps.Obfuscator.ObfuscatorInt item_count;
    }
}
