// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

namespace CookApps.AutoBattler
{

    public enum CharacterEffect
    {
        NONE = 0,
        AD_UP = 1,
        AD_PERCENT_UP = 2,
        AP_UP = 3,
        AP_PERCENT_UP = 4,
        DEF_UP = 5,
        DEF_PERCENT_UP = 6,
        RES_UP = 7,
        RES_PERCENT_UP = 8,
        DEF_PENETRATION_UP = 9,
        DEF_PENETRATION_PERCENT_UP = 10,
        RES_PENETRATION_UP = 11,
        RES_PENETRATION_PERCENT_UP = 12,
        HP_RECOVERY_UP = 13,
        HP_RECOVERY_PERCENT_UP = 14,
        MOVESPEED_UP = 15,
        MOVESPEED_PERCENT_UP = 16,
    }

    public enum Grade
    {
        COMMON = 1,
        RARE = 2,
        EPIC = 3,
        LEGEND = 4,
    }

    public enum RewardType
    {
        COIN = 1,
        JEWEL = 2,
        BREAD = 3,
        KTICKET = 4,
        EXPITEM = 5,
        DUNGEON_KEY1 = 6,
        DUNGEON_KEY2 = 7,
        DUNGEON_KEY3 = 8,
        BUILDING_SUPPLIES = 9,
        ETICKET = 10,
        EXP = 11,
        KNIGHT_PIECE = 12,
        RANDOM_KNIGHT_PIECE = 13,
        RANDOM_WEAPON_PIECE = 14,
        RUNE = 15,
    }

    public enum CharacterType
    {
        EARTH = 1,
        WIND = 2,
        WATER = 3,
        FIRE = 4,
        DARK = 5,
        MACHINE = 6,
        LIGHT = 7,
    }

    public enum CharacterPosition
    {
        WARRIOR = 1,
        TANK = 2,
        WIZARD = 3,
        RANGER = 4,
        ASSASSIN = 5,
        SUPPORTER = 6,
    }

    public enum AttackRangeShape
    {
        Rectangle = 1,
        RectangleCut1Edge = 2,
        RectangleCut2Edge = 3,
        RectangleCut3Edge = 4,
        RectangleCut4Edge = 5,
        RectangleCut5Edge = 6,
    }
}
