# fastlane/Fastfile

platform :android do
  desc "Upload a new Android version to the Google Play Store"
  lane :google do |options|
    if options[:release]
      apply_liapp_android_for_unity(
        aab: "#{ENV['ANDROID_BUILD_FILE_PATH']}"
      )

      upload_to_play_store(
        track: 'internal',
        release_status: 'completed',
        aab: ENV['ANDROID_BUILD_FILE_PATH'],
        mapping: ENV['ANDROID_SYMBOL_FILE_PATH']
      )

      sh("firebase", "crashlytics:symbols:upload", "--app=#{ENV['CRASHLYTICS_APP_ID']}", ENV['ANDROID_SYMBOL_FILE_PATH'])
    end

    if ENV['GITHUB_OUTPUT'].to_s.length > 0
      sh("echo \"app-output-path=#{ENV['ANDROID_BUILD_FILE_PATH']}\" >> \"$GITHUB_OUTPUT\"")
      sh("echo \"symbol-output-path=#{ENV['ANDROID_SYMBOL_FILE_PATH']}\" >> \"$GITHUB_OUTPUT\"")
    end
  end
end

platform :ios do
  desc "Deliver a new iOS version to Apple App Store"
  lane :apple do |options|
    app_store_connect_api_key(
      key_id: ENV['APPSTORE_KEY_ID'],
      issuer_id: ENV['APPSTORE_ISSUER_ID'],
      key_content: ENV["APPSTORE_P8"]
    )

    update_info_plist(
      xcodeproj: "#{ENV['IOS_BUILD_PATH']}/Unity-iPhone.xcodeproj",
      plist_path: 'Info.plist',
      block: proc do |plist|
        plist['ITSAppUsesNonExemptEncryption'] = false
      end
    )

    setup_ci

    profile_type = (options[:release] ? 'appstore' : 'adhoc')

    match(
      type: profile_type,
      storage_mode: 'git',
      git_url: ENV['MATCH_URL'],
      git_branch: ENV['MATCH_GIT_BRANCH'],
      git_basic_authorization: ENV['MATCH_GIT_BASIC_AUTHORIZATION'],
      app_identifier: ENV['IOS_BUNDLE_ID']
    )

    # Unity has specific requirements around codesigning that we have to handle
    # See https://github.com/fastlane/fastlane/discussions/17458 for context
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "#{ENV['IOS_BUILD_PATH']}/Unity-iPhone.xcodeproj"
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_#{profile_type}_team-id"],
      code_sign_identity: 'iPhone Distribution',
      targets: 'Unity-iPhone',
      path: "#{ENV['IOS_BUILD_PATH']}/Unity-iPhone.xcodeproj",
      profile_name: ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_#{profile_type}_profile-name"],
      profile_uuid: ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_#{profile_type}"]
    )

    build_app(
      workspace: "#{ENV['IOS_BUILD_PATH']}/Unity-iPhone.xcworkspace",
      scheme: 'Unity-iPhone',
      xcargs: '-allowProvisioningUpdates'
    )

    if options[:release]
      apply_liapp_ios_for_unity(signing_identity: 'Apple Distribution: cookapps')
      upload_to_testflight(skip_waiting_for_build_processing: true)

      upload_symbols_to_crashlytics(
        binary_path: "#{ENV['IOS_BUILD_PATH']}/Pods/FirebaseCrashlytics/upload-symbols",
        app_id: ENV['CRASHLYTICS_APP_ID']
      )
    end

    if ENV['GITHUB_OUTPUT'].to_s.length > 0
      sh("echo \"app-output-path=#{Actions.lane_context[SharedValues::IPA_OUTPUT_PATH]}\" >> \"$GITHUB_OUTPUT\"")
      sh("echo \"symbol-output-path=#{Actions.lane_context[SharedValues::DSYM_OUTPUT_PATH]}\" >> \"$GITHUB_OUTPUT\"")
    end
  end
end
