using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using CookApps.AutoBattler;
using Newtonsoft.Json.Linq;
using UnityEditor;

public class CacheSpecDataGenerator : Editor
{
    public static List<string> IgnoreSheetList = new List<string>
    {
        
    };

    [MenuItem("Tools/Generate Cache SpecData")]
    public static void GenerateCustomizedSpecData()
    {
        string json = SpecDataResourceLoader.LoadSpecData();

        JObject specData = JObject.Parse(json);

        StringBuilder sb = new StringBuilder();

        sb.AppendLine("//=====================================================");
        sb.AppendLine("//  자동 생성 코드입니다. 수정하지 마세요");
        sb.AppendLine("//  made by 김윤하, mail : yhkim2@cookapps.com ");
        sb.AppendLine("//=====================================================");

        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");

        sb.AppendLine("namespace CookApps.AutoBattler");
        sb.AppendLine("{");

        sb.AppendLine("\tpublic partial class SpecDataManager");
        sb.AppendLine("\t{");

        List<string> sheetList = new List<string>();
        List<string> sheetList2 = new List<string>();

        foreach (JProperty property in specData.Properties())
        {
            string className = property.Name;

            bool isIgnore = IgnoreSheetList.Any(sheetName => sheetName.Equals(className));

            if(isIgnore) continue;

            sb.AppendLine($"\t\tpublic List<{className}> {className}List {{get; private set;}}");

            sheetList.Add(className + "List");
            sheetList2.Add(className);
        }

        sb.AppendLine();

        sb.AppendLine("\t\tprivate void GenerateCacheSpecData()");
        sb.AppendLine("\t\t{");

        for (int i = 0; i < sheetList.Count; ++i)
        {
            sb.AppendLine("\t\t\t" + sheetList[i] + " = " + sheetList2[i] + ".All.ToList();");
        }

        sb.AppendLine("\t\t}");

        sb.AppendLine("\t}");

        sb.AppendLine("}");

        string path = "Assets/_Project/Scripts/Spec/SpecDataManager.AutoGeneratedCache.cs";

        File.WriteAllText(path, sb.ToString());
        AssetDatabase.Refresh();
    }
}
