using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Generator
{
    /// <summary>
    /// gRPC Service 클래스에 자동 에러 체크 기능을 추가하는 Source Generator
    /// [GrpcService] 어트리뷰트가 있는 모든 partial class에 대해
    /// ExecuteWithAutoErrorCheck 메서드를 자동으로 생성합니다.
    /// </summary>
    [Generator]
    public class GrpcServiceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not SyntaxReceiver receiver)
                return;

            var compilation = context.Compilation;

            // Cysharp.Threading.Tasks가 있는지 확인
            var hasCysharp = compilation.ReferencedAssemblyNames
                .Any(ai => ai.Name.Equals("UniTask", System.StringComparison.OrdinalIgnoreCase) ||
                           ai.Name.Contains("Cysharp.Threading.Tasks"));

            // IGrpcServiceInterceptor 인터페이스를 한 번만 생성
            if (receiver.CandidateClasses.Count > 0)
            {
                var interfaceSource = GenerateServiceInterceptorInterface();
                context.AddSource("IGrpcServiceInterceptor.g.cs", SourceText.From(interfaceSource, Encoding.UTF8));
            }

            foreach (var classDeclaration in receiver.CandidateClasses)
            {
                var model = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
                var classSymbol = model.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

                if (classSymbol == null)
                    continue;

                // [GrpcService] 어트리뷰트가 있는지 확인
                var hasGrpcServiceAttribute = classSymbol.GetAttributes()
                    .Any(ad => ad.AttributeClass?.Name == "GrpcServiceAttribute");

                if (!hasGrpcServiceAttribute)
                    continue;

                // partial class인지 확인
                if (!classDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword))
                    continue;

                // 네임스페이스 가져오기
                var namespaceName = classSymbol.ContainingNamespace?.ToDisplayString();
                if (namespaceName == "<global namespace>")
                    namespaceName = null;

                // 생성할 코드 작성
                var source = GeneratePartialClass(
                    namespaceName,
                    classSymbol.Name,
                    classDeclaration.Modifiers.ToString(),
                    hasCysharp
                );

                // 파일 이름 생성
                var fileName = string.IsNullOrEmpty(namespaceName)
                    ? $"{classSymbol.Name}.g.cs"
                    : $"{namespaceName}.{classSymbol.Name}.g.cs";

                // 소스 추가
                context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
            }
        }

        private string GeneratePartialClass(string namespaceName, string className, string modifiers, bool hasCysharp)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using CookApps.NetLite;");
            sb.AppendLine("using CookApps.NetLite.Feat.Grpc;");

            if (hasCysharp)
            {
                sb.AppendLine("using Cysharp.Threading.Tasks;");
            }

            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using Grpc.Core;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            // 들여쓰기 설정
            var indent = string.IsNullOrEmpty(namespaceName) ? "" : "    ";

            sb.AppendLine($"{indent}{modifiers} class {className}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine($"{indent}    /// gRPC 서비스 호출을 가로채어 로딩 표시 및 에러 처리를 수행하는 인터셉터");
            sb.AppendLine($"{indent}    /// </summary>");
            sb.AppendLine($"{indent}    public virtual IGrpcServiceInterceptor ServiceInterceptor {{ get; set; }}");
            sb.AppendLine($"{indent}    ");
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine($"{indent}    /// ExecuteAsync를 호출하고 자동으로 ThrowIfError를 실행합니다.");
            sb.AppendLine($"{indent}    /// 로딩 인디케이터 표시, 공통 에러 핸들링, 재시도가 자동으로 처리됩니다.");
            sb.AppendLine($"{indent}    /// RPC 오류(Unavailable, DeadlineExceeded) 발생 시 자동으로 재시도하며,");
            sb.AppendLine($"{indent}    /// 재시도가 발생하면 showLoadingIndicator 설정과 무관하게 로딩 인디케이터가 표시됩니다.");
            sb.AppendLine($"{indent}    /// Source Generator에 의해 자동 생성된 메서드입니다.");
            sb.AppendLine($"{indent}    /// </summary>");
            sb.AppendLine($"{indent}    /// <param name=\"showLoadingIndicator\">로딩 인디케이터 표시 여부 (기본값: false)</param>");
            sb.AppendLine($"{indent}    /// <param name=\"maxRetries\">최대 재시도 횟수 (기본값: 3)</param>");
            sb.AppendLine($"{indent}    /// <param name=\"delaySecond\">재시도 간 대기 시간(초) (기본값: 1)</param>");

            var taskType = hasCysharp ? "UniTask" : "Awaitable";
            sb.AppendLine($"{indent}    protected async {taskType}<TResponse> ExecuteWithCommonErrorCheck<TRequest, TResponse>(");
            sb.AppendLine($"{indent}        AsyncUnaryCallDelegate<TRequest, TResponse> call,");
            sb.AppendLine($"{indent}        TRequest request,");
            sb.AppendLine($"{indent}        double? deadline = null,");
            sb.AppendLine($"{indent}        CancellationToken cancellationToken = default,");
            sb.AppendLine($"{indent}        bool showLoadingIndicator = false,");
            sb.AppendLine($"{indent}        int maxRetries = 3,");
            sb.AppendLine($"{indent}        float delaySecond = 1f)");
            sb.AppendLine($"{indent}        where TResponse : IGrpcMessageResponse<TResponse>, new()");
            sb.AppendLine($"{indent}        where TRequest : IGrpcMessageRequest<TRequest>, new()");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        bool loadingIndicatorShown = false;");
            sb.AppendLine($"{indent}        TResponse lastResponse = default;");
            sb.AppendLine($"{indent}        Exception lastException = null;");
            sb.AppendLine($"{indent}        ");
            sb.AppendLine($"{indent}        try");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            if (showLoadingIndicator && ServiceInterceptor != null)");
            sb.AppendLine($"{indent}            {{");
            sb.AppendLine($"{indent}                ServiceInterceptor.ShowLoadingIndicator();");
            sb.AppendLine($"{indent}                loadingIndicatorShown = true;");
            sb.AppendLine($"{indent}            }}");
            sb.AppendLine($"{indent}            ");
            sb.AppendLine($"{indent}            for (var attempt = 0; attempt < maxRetries; attempt++)");
            sb.AppendLine($"{indent}            {{");
            sb.AppendLine($"{indent}                try");
            sb.AppendLine($"{indent}                {{");
            sb.AppendLine($"{indent}                    lastResponse = await ExecuteAsync(call, request, deadline, cancellationToken);");
            sb.AppendLine($"{indent}                    return lastResponse;");
            sb.AppendLine($"{indent}                }}");
            sb.AppendLine($"{indent}                catch (RpcException ex) when (IsRetryable(ex.StatusCode))");
            sb.AppendLine($"{indent}                {{");
            sb.AppendLine($"{indent}                    lastException = ex;");
            sb.AppendLine($"{indent}                    ");
            sb.AppendLine($"{indent}                    // 마지막 시도인 경우 재시도하지 않음");
            sb.AppendLine($"{indent}                    if (attempt >= maxRetries - 1)");
            sb.AppendLine($"{indent}                    {{");
            sb.AppendLine($"{indent}                        break;");
            sb.AppendLine($"{indent}                    }}");
            sb.AppendLine($"{indent}                    ");
            sb.AppendLine($"{indent}                    // 재시도 발생 - 로딩 인디케이터 무조건 표시");
            sb.AppendLine($"{indent}                    if (!loadingIndicatorShown && ServiceInterceptor != null)");
            sb.AppendLine($"{indent}                    {{");
            sb.AppendLine($"{indent}                        ServiceInterceptor.ShowLoadingIndicator();");
            sb.AppendLine($"{indent}                        loadingIndicatorShown = true;");
            sb.AppendLine($"{indent}                    }}");
            sb.AppendLine($"{indent}                    ");

            if (hasCysharp)
            {
                sb.AppendLine($"{indent}                    await UniTask.Delay(TimeSpan.FromSeconds(delaySecond * (attempt + 1)), cancellationToken: cancellationToken);");
            }
            else
            {
                sb.AppendLine($"{indent}                    await Awaitable.WaitForSecondsAsync(delaySecond * (attempt + 1));");
            }
            sb.AppendLine($"{indent}                }}");
            sb.AppendLine($"{indent}                catch (Exception ex)");
            sb.AppendLine($"{indent}                {{");
            sb.AppendLine($"{indent}                    lastException = ex;");
            sb.AppendLine($"{indent}                    // 재시도 불가능한 에러 - 루프 탈출");
            sb.AppendLine($"{indent}                    break;");
            sb.AppendLine($"{indent}                }}");
            sb.AppendLine($"{indent}            }}");
            sb.AppendLine($"{indent}            ");
            sb.AppendLine($"{indent}            // 에러가 발생한 경우 HandleCommonError 호출");
            sb.AppendLine($"{indent}            if (lastException != null)");
            sb.AppendLine($"{indent}            {{");
            sb.AppendLine($"{indent}                bool handledByCommon = ServiceInterceptor?.HandleCommonError(lastException) ?? false;");
            sb.AppendLine($"{indent}                if (handledByCommon)");
            sb.AppendLine($"{indent}                {{");
            sb.AppendLine($"{indent}                    // 공통으로 처리됨 - default 반환");
            sb.AppendLine($"{indent}                    return default;");
            sb.AppendLine($"{indent}                }}");
            sb.AppendLine($"{indent}            }}");
            sb.AppendLine($"{indent}            ");
            sb.AppendLine($"{indent}            // 재시도 실패 또는 처리되지 않은 에러 - lastResponse 리턴");
            sb.AppendLine($"{indent}            return lastResponse;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}        catch (Exception e)");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            // 재시도 로직 외부에서 발생한 에러 (예: ShowLoadingIndicator 호출 시)");
            sb.AppendLine($"{indent}            bool handledByCommon = ServiceInterceptor?.HandleCommonError(e) ?? false;");
            sb.AppendLine($"{indent}            if (handledByCommon)");
            sb.AppendLine($"{indent}            {{");
            sb.AppendLine($"{indent}                return default;");
            sb.AppendLine($"{indent}            }}");
            sb.AppendLine($"{indent}            ");
            sb.AppendLine($"{indent}            // 처리되지 않은 에러 - lastResponse 리턴");
            sb.AppendLine($"{indent}            return lastResponse;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}        finally");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            // 로딩 인디케이터 정리");
            sb.AppendLine($"{indent}            if (loadingIndicatorShown)");
            sb.AppendLine($"{indent}            {{");
            sb.AppendLine($"{indent}                ServiceInterceptor?.HideLoadingIndicator();");
            sb.AppendLine($"{indent}            }}");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}    ");
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine($"{indent}    /// RPC 상태 코드가 재시도 가능한지 확인합니다.");
            sb.AppendLine($"{indent}    /// </summary>");
            sb.AppendLine($"{indent}    private static bool IsRetryable(StatusCode statusCode)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        return statusCode is StatusCode.Unavailable or StatusCode.DeadlineExceeded;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");

            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private string GenerateServiceInterceptorInterface()
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine("namespace CookApps.NetLite.Feat.Grpc");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// gRPC 서비스 호출을 가로채어 로딩 표시, 에러 처리 등을 수행하는 인터셉터 인터페이스");
            sb.AppendLine("    /// Source Generator에 의해 자동 생성됩니다.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public interface IGrpcServiceInterceptor");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 로딩 인디케이터를 표시합니다.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        void ShowLoadingIndicator();");
            sb.AppendLine("        ");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 로딩 인디케이터를 숨깁니다.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        void HideLoadingIndicator();");
            sb.AppendLine("        ");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 공통 에러를 처리합니다.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"exception\">발생한 예외</param>");
            sb.AppendLine("        /// <returns>공통으로 처리된 경우 true, 커스텀 처리가 필요한 경우 false</returns>");
            sb.AppendLine("        bool HandleCommonError(Exception exception);");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }

    /// <summary>
    /// [GrpcService] 어트리뷰트가 있는 partial class를 찾는 SyntaxReceiver
    /// </summary>
    class SyntaxReceiver : ISyntaxReceiver
    {
        public List<ClassDeclarationSyntax> CandidateClasses { get; } = new List<ClassDeclarationSyntax>();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            // partial class 선언을 찾음
            if (syntaxNode is ClassDeclarationSyntax classDeclaration &&
                classDeclaration.AttributeLists.Count > 0 &&
                classDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword))
            {
                CandidateClasses.Add(classDeclaration);
            }
        }
    }
}
