// <auto-generated>
// IdMap - 자동 생성된 ID 맵입니다.
// Assets > Tools > Generate IdMap 메뉴로 재생성할 수 있습니다.
// </auto-generated>

namespace CookApps.AutoBattler
{
    /// <summary>
    /// 각종 ID에 쉽게 접근하기 위한 정적 클래스
    /// 사용 예: IdMap.Item.Gold, IdMap.ElpisBuild.CommandCenter
    /// </summary>
    public static partial class IdMap
    {
        public static partial class Item
        {
            // ==================== Currency Items ====================
            public static readonly ItemId Jewel = 110001;
            public static readonly ItemId Gold = 210001;

            // ==================== Consumable Items ====================
            public static readonly ItemId Soul = 350001;
            public static readonly ItemId ActionPoint = 410001;
            public static readonly ItemId CharacterTicket = 550001;
            public static readonly ItemId 전용무기티켓 = 650001;
            public static readonly ItemId UserExp = 710001;
            public static readonly ItemId CharExp = 810001;
            public static readonly ItemId PvpTicket = 1350001;
            public static readonly ItemId BuildItem = 1620001;
            public static readonly ItemId 기사의디멘션큐브 = 1730001;
            public static readonly ItemId 불의디멘션큐브 = 1730101;
            public static readonly ItemId 바람의디멘션큐브 = 1730102;
            public static readonly ItemId 대지의디멘션큐브 = 1730103;
            public static readonly ItemId 폭풍의디멘션큐브 = 1730104;
            public static readonly ItemId 대양의디멘션큐브 = 1730105;
            public static readonly ItemId 노블레스디멘션큐브 = 1730201;
            public static readonly ItemId 슈퍼노바디멘션큐브 = 1730202;
            public static readonly ItemId 트러블슈터디멘션큐브 = 1730203;
            public static readonly ItemId 엘피스코어 = 1850001;
            public static readonly ItemId 속성석 = 1130001;

            // ==================== Material Items ====================
        }

        public static class ElpisBuild
        {
            // ==================== COMMAND_CENTER ====================
            public const int CommandCenter = 100301;

            // ==================== NEST ====================
            public const int Nest_1 = 200101;
            public const int Nest_2 = 200102;
            public const int Nest_3 = 200103;

            // ==================== DIMENSION_LAB ====================
            public const int DimensionLab = 100101;

            // ==================== SIMULATION_CENTER ====================
            public const int SimulationCenter = 100201;
        }
    }

    /// <summary>
    /// ItemId 확장 메서드
    /// </summary>
    public static class ItemIdExtensions
    {
        public static bool IsCurrency(this ItemId id)
        {
            return id == 110001 || id == 210001;
        }

        public static bool IsConsumable(this ItemId id)
        {
            return id == 350001 || id == 410001 || id == 550001 || id == 650001 || id == 710001 || id == 810001 || id == 1350001 || id == 1620001 || id == 1730001 || id == 1730101 || id == 1730102 || id == 1730103 || id == 1730104 || id == 1730105 || id == 1730201 || id == 1730202 || id == 1730203 || id == 1850001 || id == 1130001;
        }

        public static bool IsMaterial(this ItemId id)
        {
            return false;
        }

        public static bool IsCharacter(this ItemId id)
        {
            return id == 2101 || id == 2102 || id == 2201 || id == 2202 || id == 2301 || id == 2302 || id == 2401 || id == 2501 || id == 2502 || id == 3101 || id == 3102 || id == 3103 || id == 3201 || id == 3202 || id == 3203 || id == 3204 || id == 3301 || id == 3302 || id == 3303 || id == 3401 || id == 3402 || id == 3403 || id == 3404 || id == 3405 || id == 3501 || id == 3502 || id == 3503 || id == 3504 || id == 3505 || id == 3506;
        }

        public static bool IsCharacterPiece(this ItemId id)
        {
            return id == 1032101 || id == 1032102 || id == 1032201 || id == 1032202 || id == 1032301 || id == 1032302 || id == 1032401 || id == 1032501 || id == 1032502 || id == 1053101 || id == 1053102 || id == 1053103 || id == 1053201 || id == 1053202 || id == 1053203 || id == 1053204 || id == 1053301 || id == 1053302 || id == 1053303 || id == 1053401 || id == 1053402 || id == 1053403 || id == 1053404 || id == 1053405 || id == 1053501 || id == 1053502 || id == 1053503 || id == 1053504 || id == 1053505 || id == 1053506;
        }

        public static bool GetCharacterId(this ItemId id, out int charId)
        {
            charId = -1;
            if (id.IsCharacter())
            {
                charId = id.Value;
                return true;
            }
            if (id.IsCharacterPiece())
            {
                charId = id.Value % 10000;
                return true;
            }
            return false;
        }

        public static ItemId GetCharacterPieceId(int characterId)
        {
            return characterId switch
            {
                2101 => 1032101,
                2102 => 1032102,
                2201 => 1032201,
                2202 => 1032202,
                2301 => 1032301,
                2302 => 1032302,
                2401 => 1032401,
                2501 => 1032501,
                2502 => 1032502,
                3101 => 1053101,
                3102 => 1053102,
                3103 => 1053103,
                3201 => 1053201,
                3202 => 1053202,
                3203 => 1053203,
                3204 => 1053204,
                3301 => 1053301,
                3302 => 1053302,
                3303 => 1053303,
                3401 => 1053401,
                3402 => 1053402,
                3403 => 1053403,
                3404 => 1053404,
                3405 => 1053405,
                3501 => 1053501,
                3502 => 1053502,
                3503 => 1053503,
                3504 => 1053504,
                3505 => 1053505,
                3506 => 1053506,
                _ => default
            };
        }

    }

    /// <summary>
    /// 치트용 재화 타입 (SROptions 드롭다운용)
    /// </summary>
    public enum CheatCurrencyType
    {
        Jewel = 110001,
        Gold = 210001,
        Soul = 350001,
        ActionPoint = 410001,
        CharacterTicket = 550001,
        전용무기티켓 = 650001,
        UserExp = 710001,
        CharExp = 810001,
        PvpTicket = 1350001,
        BuildItem = 1620001,
        기사의디멘션큐브 = 1730001,
        불의디멘션큐브 = 1730101,
        바람의디멘션큐브 = 1730102,
        대지의디멘션큐브 = 1730103,
        폭풍의디멘션큐브 = 1730104,
        대양의디멘션큐브 = 1730105,
        노블레스디멘션큐브 = 1730201,
        슈퍼노바디멘션큐브 = 1730202,
        트러블슈터디멘션큐브 = 1730203,
        엘피스코어 = 1850001,
        속성석 = 1130001,

        // 캐릭터
        캐릭터_2101 = 2101,
        캐릭터_2102 = 2102,
        캐릭터_2201 = 2201,
        캐릭터_2202 = 2202,
        캐릭터_2301 = 2301,
        캐릭터_2302 = 2302,
        캐릭터_2401 = 2401,
        캐릭터_2501 = 2501,
        캐릭터_2502 = 2502,
        캐릭터_3101 = 3101,
        캐릭터_3102 = 3102,
        캐릭터_3103 = 3103,
        캐릭터_3201 = 3201,
        캐릭터_3202 = 3202,
        캐릭터_3203 = 3203,
        캐릭터_3204 = 3204,
        캐릭터_3301 = 3301,
        캐릭터_3302 = 3302,
        캐릭터_3303 = 3303,
        캐릭터_3401 = 3401,
        캐릭터_3402 = 3402,
        캐릭터_3403 = 3403,
        캐릭터_3404 = 3404,
        캐릭터_3405 = 3405,
        캐릭터_3501 = 3501,
        캐릭터_3502 = 3502,
        캐릭터_3503 = 3503,
        캐릭터_3504 = 3504,
        캐릭터_3505 = 3505,
        캐릭터_3506 = 3506,

        // 캐릭터 조각
        조각_2101 = 1032101,
        조각_2102 = 1032102,
        조각_2201 = 1032201,
        조각_2202 = 1032202,
        조각_2301 = 1032301,
        조각_2302 = 1032302,
        조각_2401 = 1032401,
        조각_2501 = 1032501,
        조각_2502 = 1032502,
        조각_3101 = 1053101,
        조각_3102 = 1053102,
        조각_3103 = 1053103,
        조각_3201 = 1053201,
        조각_3202 = 1053202,
        조각_3203 = 1053203,
        조각_3204 = 1053204,
        조각_3301 = 1053301,
        조각_3302 = 1053302,
        조각_3303 = 1053303,
        조각_3401 = 1053401,
        조각_3402 = 1053402,
        조각_3403 = 1053403,
        조각_3404 = 1053404,
        조각_3405 = 1053405,
        조각_3501 = 1053501,
        조각_3502 = 1053502,
        조각_3503 = 1053503,
        조각_3504 = 1053504,
        조각_3505 = 1053505,
        조각_3506 = 1053506,
    }
}
