// <auto-generated>
// IdMap - 자동 생성된 ID 맵입니다.
// Assets > Tools > Generate IdMap 메뉴로 재생성할 수 있습니다.
// </auto-generated>

namespace CookApps.AutoBattler
{
    /// <summary>
    /// 각종 ID에 쉽게 접근하기 위한 정적 클래스
    /// 사용 예: IdMap.Item.Gold, IdMap.ElpisBuild.CommandCenter
    /// </summary>
    public static class IdMap
    {
        public static class Item
        {
            // ==================== Currency Items ====================
            public static readonly ItemId Jewel = 110001;
            public static readonly ItemId Gold = 210001;

            // ==================== Consumable Items ====================
            public static readonly ItemId Soul = 350001;
            public static readonly ItemId ActionPoint = 410001;
            public static readonly ItemId CharacterTicket = 550001;
            public static readonly ItemId 전용무기티켓 = 650001;
            public static readonly ItemId UserExp = 710001;
            public static readonly ItemId CharExp = 810001;
            public static readonly ItemId PvpTicket = 1350001;
            public static readonly ItemId BuildItem = 1620001;
            public static readonly ItemId 기사의디멘션큐브 = 1730001;
            public static readonly ItemId 기사방어력큐브 = 1730002;
            public static readonly ItemId 기사체력큐브 = 1730003;
            public static readonly ItemId 불의디멘션큐브 = 1730101;
            public static readonly ItemId 바람의디멘션큐브 = 1730102;
            public static readonly ItemId 대지의디멘션큐브 = 1730103;
            public static readonly ItemId 폭풍의디멘션큐브 = 1730104;
            public static readonly ItemId 대양의디멘션큐브 = 1730105;
            public static readonly ItemId 노블레스디멘션큐브 = 1730201;
            public static readonly ItemId 슈퍼노바디멘션큐브 = 1730202;
            public static readonly ItemId 트러블슈터디멘션큐브 = 1730203;
            public static readonly ItemId 엘피스코어 = 1850001;

            // ==================== Material Items ====================
        }

        public static class ElpisBuild
        {
            // ==================== COMMAND_CENTER ====================
            public const int CommandCenter = 100301;

            // ==================== NEST ====================
            public const int Nest_1 = 200101;
            public const int Nest_2 = 200102;
            public const int Nest_3 = 200103;

            // ==================== DIMENSION_LAB ====================
            public const int DimensionLab = 100101;

            // ==================== SIMULATION_CENTER ====================
            public const int SimulationCenter = 100201;
        }
    }
}
