// <auto-generated>
// ItemIdMap - 자동 생성된 아이템 ID 맵입니다.
// Assets > Tools > Generate ItemIdMap 메뉴로 재생성할 수 있습니다.
// </auto-generated>

namespace CookApps.AutoBattler
{
    /// <summary>
    /// 아이템 ID에 쉽게 접근하기 위한 정적 클래스
    /// 사용 예: ItemIdMap.Gold, ItemIdMap.Gem
    /// </summary>
    public static class ItemIdMap
    {
        // ==================== Currency Items ====================
        public const int Jewel = 110001;
        public const int Gold = 210001;

        // ==================== Consumable Items ====================
        public const int Soul = 350001;
        public const int ActionPoint = 410001;
        public const int CharacterTicket = 550001;
        public const int 전용무기티켓 = 650001;
        public const int UserExp = 710001;
        public const int CharExp = 810001;
        public const int PvpTicket = 1350001;
        public const int BuildItem = 1620001;
        public const int 기사공격력큐브 = 1730001;
        public const int 기사방어력큐브 = 1730002;
        public const int 기사체력큐브 = 1730003;
        public const int 불의디멘션큐브 = 1730101;
        public const int 바람의디멘션큐브 = 1730102;
        public const int 대지의디멘션큐브 = 1730103;
        public const int 폭풍의디멘션큐브 = 1730104;
        public const int 대양의디멘션큐브 = 1730105;
        public const int 노블레스디멘션큐브 = 1730201;
        public const int 슈퍼노바디멘션큐브 = 1730202;
        public const int 트러블슈터디멘션큐브 = 1730203;

        // ==================== Material Items ====================
    }
}
