name: 🚨 Clean up a working directory

on:
  workflow_dispatch:
    inputs:
      machine-label:
        description: >
          Input the label of the machine in which you want to clean the working directory.
          You must enter a unique label assigned to the target machine. (ex. mac-mini-m1-0)
        required: true
        type: string

permissions:
  contents: read

jobs:
  clean:
    name: Git clean
    runs-on:
      group: Default
      labels:
        - self-hosted
        - macOS
        - ARM64
        - ${{ inputs.machine-label }}
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
